### ISSUE TITLE
wkhtmltopdf   --encoding  utf-8  not work on ubuntu  

### ISSUE THREAD

**Issue by panshaoning** [wkhtmltopdf/wkhtmltopdf#3233] opened 2016-12-07 07:59 UTC
I  down wkhtmltopdf from  http://download.gna.org/wkhtmltopdf/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz   

I use as this   command   : 
wkhtmltopdf   --encoding  utf-8     http://www.iumind.com    /tmp/iumind.pdf

or this command
`wkhtmltopdf   --encoding  utf-8     --custom-header 'meta' 'charset=utf-8'       http://www.iumind.com    /tmp/iumind.pdf`

my page also  had 
```html
< meta content=\"text/html;charset=utf-8\" http-equiv=\"Content-Type\" > 
< meta content=\"utf-8\" http-equiv=\"encoding\" >
```

But  Chinese characters   were   err.

such as 

[http://www.iumind.com/1.jpg](url)

**Comment by glonlas** [comment] 2016-12-11 06:02
I have the same issue with Chinese characters too. Thank you to have post this issue.

**Comment by glonlas** [comment] 2016-12-11 16:04
Hi @panshaoning,

I found a fix on my Ubuntu 14.04. The Chinese font was missing.

Try:
`apt-get install fonts-wqy-zenhei`

You can find a list of Japanese, Korean and Chinese font here: [Chinese, Japanese, and Korean Fonts](https://help.ubuntu.com/community/Fonts#Chinese.2C_Japanese.2C_and_Korean_Fonts)

I hope it will fix your issue.

**Comment by cdman** [comment] 2017-01-05 10:47
I think I have a similar problem. Platform: Ubuntu 16.04 with wkhtmltopdf 0.12.2.4.

Steps to reproduce it:

`wkhtmltopdf https://www.google.ro output.pdf` - works as expected (notice the diacritics in the upper left corner)

```
wget http://www.google.ro
wkhtmltopdf index.html output.pdf
```

Notice the incorrect characters in the upper left corner. The file (`index.html`) contains `<meta content="text/html; charset=UTF-8" http-equiv="Content-Type">` but I also tried adding `<meta charset="UTF-8">` into it to no avail. I also tried adding `--encoding UTF-8` (with "utf-8", "UTF-8", "utf8" and "UTF8") to the command line, but the characters are still not showing up correctly.

I have a lot of `font-*` packages installed (and a lot of them not) but I'm not sure which of them (if any) should I install. Given that when loading through HTTPS it works as expected, I would assume that the correct font is installed but not being used.

**Comment by Tomsgu** [comment] 2018-09-26 17:41
Closing as it seems to be missing font issue as @glonlas commented. Please feel free to re-open this issue if I am wrong.

**Closed by Tomsgu** 2018-09-26 17:41 UTC
Labels: NeedInfo

**Comment by cdman** [comment] 2019-12-29 06:24
The issue described by me in [the fourth comment](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3233#issuecomment-270616292) very much persists. Just re-verified it on a up-to-date Ubuntu 19.10 installation with wkhtmltopdf version 0.12.5-1.

I think the HTTP/HTTPS comment from my original comment is misleading since now I retrieved the page both times trough HTTPS and the issue still persist.

I don't think this has anything to do with the installed fonts, since how can the first invocation produce the correct PDF while the second one doesn't on the same machine having the same fonts installed?

I do think this has something to do with wkhtmltopdf / chrome not detecting the correct character encoding when retrieving the file from disk (and they should detect it based on the meta tag) vs. when loading it from the server and can use the headers to detect the encoding.

Let me know if I should file a separate issue for this, since it does sound that the original issue was a missing a font package.

**Comment by ashkulz** [comment] 2019-12-30 07:06
@cdman is it possible that it links to web fonts which are broken when you convert a local file? Does the bug still persist when you run with wget's `--convert-links` option?

**Comment by cdman** [comment] 2020-01-02 06:09
@ashkulz - that doesn't seem to be it. Ie. doing:

```
wget --convert-links https://www.google.ro
wkhtmltopdf index.html output.pdf
```

Still produces a "broken" pdf for me (where by broken I mean: non-latin characters are not correctly displayed) while `wkhtmltopdf https://www.google.ro output.pdf` works as expected.

PS. Happy new year!

**Comment by ashkulz** [comment] 2020-01-02 12:16
@cdman: it seems you're using the wrong encoding.
```
$ wget -S https://www.google.ro
--2020-01-02 17:43:58--  https://www.google.ro/
Resolving www.google.ro (www.google.ro)... 172.217.166.67, 2404:6800:4009:80d::2003
Connecting to www.google.ro (www.google.ro)|172.217.166.67|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Date: Thu, 02 Jan 2020 12:13:58 GMT
  Expires: -1
  Cache-Control: private, max-age=0
  Content-Type: text/html; charset=ISO-8859-2
  P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
  Server: gws
[snipped]
```
Does `wkhtmltopdf --encoding ISO-8859-2 index.html output.pdf` work for you, as that's the encoding that is used (as set via HTTP headers)?

**Comment by cdman** [comment] 2020-01-19 11:59
ashkulz@ - thank you for the continued support. Yes, there seem to be some mismatch between what the HTTP headers claim vs. what the `<meta>` tag inside the document claim.

Regardless, the `--encoding` option doesn't seem to work as tkuisma@ noted in #4492. I also tested `wkhtmltopdf --encoding ISO-8859-2 index.html output.pdf` and it doesn't produce the expected output (seems to still interpret the source file as an UTF-8 one).

**Comment by ashkulz** [comment] 2020-01-19 14:01
@cdman that issue seems to be about the non-patched build, while you're using the patched version. I suspect what's going on is that when you use HTTP headers, that overrides the document-provided encoding -- but the command-line option uses `setDefaultTextEncoding` -- maybe it just uses it if there's no explicitly defined encoding.

At the end of the day, the file is broken (declares UTF-8 but uses ISO-8859-2) and workarounds can only happen up to a certain point 🤷‍♂

**Comment by alpenist** [comment] 2022-01-30 21:15
> The issue described by me in [the fourth comment](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3233#issuecomment-270616292) very much persists. Just re-verified it on a up-to-date Ubuntu 19.10 installation with wkhtmltopdf version 0.12.5-1.
> 
> I think the HTTP/HTTPS comment from my original comment is misleading since now I retrieved the page both times trough HTTPS and the issue still persist.
> 
> I don't think this has anything to do with the installed fonts, since how can the first invocation produce the correct PDF while the second one doesn't on the same machine having the same fonts installed?
> 
> I do think this has something to do with wkhtmltopdf / chrome not detecting the correct character encoding when retrieving the file from disk (and they should detect it based on the meta tag) vs. when loading it from the server and can use the headers to detect the encoding.
> 
> Let me know if I should file a separate issue for this, since it does sound that the original issue was a missing a font package.

I confirm that this is exactly what is happening. I have tried to generate a URL resource pdf from an online server encoding was totally correct including header, footer, body as well as the outlines.  When I tried to generate the same resource locally I was surprised that only the body text is encoded correctly! I suspected similar causes to what you said incorrect encoding is picked up when loading from disk (in my case I used a view from the disk .. which failed to encode correctly) .. I wonder if there are any workarounds for this.!
