### ISSUE TITLE
problem while rendering PDF

### ISSUE THREAD

**Issue by sasiracer** [wkhtmltopdf/wkhtmltopdf#3202] opened 2016-11-16 13:35 UTC
Hi 
I am using wkhtmltopdf 0.12.3 (with patched qt). While using column-count html renders properly but in PDF it's not rendering properly. How can i make this properly. i have more then 500 data i need to show in column vice rendering After fills first page it should move the next page.

Thanks in advance

**Comment by Tomsgu** [comment] 2018-09-26 17:17
Duplicate of #2266

**Closed by Tomsgu** 2018-09-26 17:17 UTC
Labels: Question
