### ISSUE TITLE
Images are rendered dark

### ISSUE THREAD

**Issue by reeteshranjan** [wkhtmltopdf/wkhtmltopdf#2208] opened 2015-02-17 07:36 UTC
When generating an image or pdf of an html page with images, I see that the images are rendered darker. Please see the attachments. The file html-view.png shows the view of the HTML page as seen in the browser. The same page with all CSS and images available at the same locations is fed to wkhtmltopdf to generate the PDF, and everything else comes out fine including the fonts and colors except the image getting darker.

I had a similar issue with other part of my project where I was using imagemagick to crop images on uploading, and it was creating a very similar effect of darkening the images. I found that specifying the color space as RGB while cropping retained the original colors and did not make the output dark. I was trying to look into the wkhtmltopdf code to see if I can find something similar to add; but it's mammoth. Could you please point me to the image generation code where you think there could be a fix similar to what I needed to do with imagemagick to preserve the image quality?

Please note that I did try some other relevant sounding pointers of using the --image-quality option; but it did not help.

I also noticed that the outcome has different anomalies with different images. For some images, the images actually become 'lighter' rather than darker. This again was very similar to the image magick experience that I managed to solve.

Looking forward to quick help on this one.
# 

HTML View
![html-view](https://cloud.githubusercontent.com/assets/5516599/6224619/b07f1146-b6a4-11e4-85f8-1fbc9adeaf9a.png)

Generated Views
BMP
![bmp-generated](https://cloud.githubusercontent.com/assets/5516599/6224618/b07a1b14-b6a4-11e4-8e41-d4b18ed12556.png)
JPG
![jpg-generated](https://cloud.githubusercontent.com/assets/5516599/6224620/b0812436-b6a4-11e4-9217-300e24e54172.png)
PDF
![pdf-generated](https://cloud.githubusercontent.com/assets/5516599/6224621/b085dd1e-b6a4-11e4-81f1-07fc23fd2078.png)
PNG
![png-generated](https://cloud.githubusercontent.com/assets/5516599/6224622/b086e74a-b6a4-11e4-865d-fdc92d4da558.png)

**Comment by reeteshranjan** [comment] 2015-02-17 08:05
I wanted to mention that the image being rendered here is a PNG.

**Comment by rsteinwand** [comment] 2015-02-17 13:23
How does the image render in different browsers, including older ones?

**Comment by reeteshranjan** [comment] 2015-02-17 14:31
Are you asking me about the original image or the generated files?

**Comment by rsteinwand** [comment] 2015-02-17 14:36
Does the html view look dark in other web browsers? (Chrome, IE, Firefox, etc.)

I've run into that in the past in certain browsers.

**Comment by rsteinwand** [comment] 2015-02-17 14:40
You might also try the 0.13 beta, which uses a newer version of QT.

**Comment by reeteshranjan** [comment] 2015-02-17 15:46
I went right down to IE8 and the html view looks great. So I think nothing is wrong about the original image quality.

I was using 0.12.1.1 compiled from source so far. I am looking to use the PDF generation for production. Would it still be advised to use the beta 0.13?

Also are we having a real fix of this issue in the qt included in 0.13?

**Comment by rsteinwand** [comment] 2015-02-17 16:13
I believe 0.12 uses an older version of QT, where 0.13 (which isn't ready for production) has a newer version. 

Very little development will be done on 0.12 going forward so all you can do at this point is try a different image optimization program.

FYI. I'm not part of the development team.

**Comment by ashkulz** [comment] 2015-02-17 16:29
Although your comments are appreciated: smile:

**Comment by reeteshranjan** [comment] 2015-02-17 18:50
Thanks for all the answers. I also did not assume whether you are part of dev team or not, and was asking thinking you may know the details. Thanks for all the help again.

Hoping to hear more deeper details from the development team.

**Comment by ashkulz** [comment] 2015-02-18 05:38
@reeteshranjan: at the moment, the development team is just me and I don't have enough free time to devote to this project. I think that you will have to convert your images to the RGB color profile, see #2185 where a similar problem is discussed. It seems to be due to QTBUG-32543 where other color profiles are not supported.

**Comment by reeteshranjan** [comment] 2015-02-18 07:40
I can see that there is some issue with the original image itself. I tried to download the image from the html view and see that the image is dark itself and what wkhtmltopdf is doing is nothing extra. However; I could not see this as browsers somehow show the image properly.

However; the image color space reported by my Mac is RGB only, not CMYK, so the issue you have referred to does not apply for me. In any case, I need to go back to imagemagick to see why it is creating the images as dark.

Thanks for all the help.

**Comment by amelishko** [comment] 2015-03-31 09:52
@ashkulz any ETA for this one?

Can you please give me a direction on how to fix it? I really want to get rid of it but i don't know where to start.

Thanks for all the help, wkhtmltopdf is a fantastic project.

Mick

**Comment by ashkulz** [comment] 2015-06-29 11:46
Can someone confirm that this issue happens with `0.12.1`? If not, then it is most likely a duplicate of #2214 where we have identified the change which broke it.

**Comment by ashkulz** [comment] 2015-07-14 01:21
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which may fix this issue. Please report back if it is not solved with the above version.

*Please note that the above downloads will be removed after the `0.12.3` release*.

**Comment by ZacharyYGateley** [comment] 2015-08-14 22:27
I have been running into a darkness issue that appears to maybe have something to do with the colorspace RGB vs sRGB. I have been testing with wkhtmltoimage, but the issue is evident with wkhtmltopdf as well. Our server runs on Ubuntu with 0.12.2-6a13a51. I tested on my Windows machine with the current stable version 0.12.2.4, but the issue occurs also with Windows 0.12.3-dev-79ff51e as well.

I have a web page that appears with only this on the page:
![patch-web](https://cloud.githubusercontent.com/assets/6866355/9284986/15ed883c-4296-11e5-8a7b-723fdc093775.png)

It includes the following image:
![orig](https://cloud.githubusercontent.com/assets/6866355/9285010/46218cec-4296-11e5-9bf1-b55755b8dbae.png)
With Image Magick 6.8.0-1, I identify this image to be in colorspace "RGB"

When I run wkhtmltoimage, on the web page, the result is a golden border (CSS) that is the correct color but the image inside (html img tag) is darker:
![patch-dev](https://cloud.githubusercontent.com/assets/6866355/9285040/80194e94-4296-11e5-893e-6c22df850495.png)
With Image Magick, the image identifies as colorspace "sRGB" and is darker.

If I convert the image that results from the wkhtmltoimage to colorspace "RGB" with Image Magick, the darkness issue of the image disappears but the border is too light:
![patch-rgb](https://cloud.githubusercontent.com/assets/6866355/9285087/01b5d8d2-4297-11e5-8cc2-265e9f3caeaf.png)

When I ran wkhtmltopdf on the web page, the resulting pdf had the darkness issue as well. The CSS border color is correct but the image (html img tag) is darker:
![patch-pdf](https://cloud.githubusercontent.com/assets/6866355/9285156/b2e20d38-4297-11e5-96fb-b756b0f3b73c.png)

I hope this is in some way helpful. Thanks.

**Comment by ashkulz** [comment] 2015-08-31 08:26
@zacgat: can you post/attach the HTML, CSS and the image for the above?

**Comment by unixmonkey** [comment] 2017-10-26 19:04
I have an HTML file that reproduces the above results (much darker image after converting to PDF compared to previewing in a web browser or image editor):

```html
<!doctype html>
<html>
  <head>
    <title>Darker images</title>
    <style>
      .cityscape {
        border: 10px solid #ffc40e;
      }
    </style>
  </head>
  <body>
    <img class="cityscape" src="https://images.datahubus.com/core_data/image/file/59e506/e7f50c/fd0324/f29cf3/3c496229-14b7-4530-8ef2-7e4273d9a20e_C72A5718.jpg" width="2400">
  </body>
</html>
```

[images-darker-0.12.4.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1419717/images-darker-0.12.4.pdf)

Reproduced with `wkhtmltox-0.12.4_osx-cocoa-x86-64`, as well as `0.12.3`

It doesn't make any difference that I can tell if the image is in an `img` tag, or as a background image in CSS. The sky is much darker, and the building far right is much less orange in the PDF output.

Thank you for all that you do to keep this project going strong.

**Comment by 91juhwang** [comment] 2017-10-27 14:10
My issue has been resolved.

The large photo had the following color profile: ProPhoto RGB. Once it is converted to sRGB, it works fine.

**Comment by alloylab** [comment] 2018-06-15 14:21
have you tried this on 0.12.5?

**Comment by Tomsgu** [comment] 2018-08-08 12:25
Closing as this should be fixed. I cannot reproduce the issue in `0.12.5`. Please feel free to re-open it if you still experience the problem.

**Closed by Tomsgu** 2018-08-08 12:25 UTC
Labels: NeedInfo
