### ISSUE TITLE
Empty row after pagebreak and <thead> in table

### ISSUE THREAD

**Issue by LaCodon** [wkhtmltopdf/wkhtmltopdf#3027] opened 2016-07-05 10:56 UTC
Sometimes, an empty row is rendered at the beginning of a new page directly after the repeated `thead`element if the table reaches over several pages.

After a while of testing, it occured to me that this issue is caused by the border between the single rows which either apears on the first page and triggers the issue or is not displayed on thus doesn't produce the issue. However, removing the border didn't solve the problem.

I attached several files which produce the error. This command was used: `wkhtmltopdf --disable-smart-shrinking --margin-top 24mm --margin-right 0 --margin-left 0 --margin-bottom 20mm --header-html header.html --footer-html footer.html page.html wkhtmltopdf_OUT.pdf` on Windows with this version: `wkhtmltopdf 0.12.3.2 (with patched qt)` (but the same happens on my debian machine).

In fits1.pdf, the error does not occure. Moving the whole table down 1px results in bug.pdf. Moving the table another 1px down, the error doesn't occure again and the last row on the first page jumps onto the next, as shown in fits2.pdf

Because of the dynamic creation of pdfs within my application, I can't adjust the table position so that the error does not occure, which is my actual problem.

Does anyone have an idea for a workaround or is the bug fixable?

Regards, LaCodon

[Errordemo.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/347573/Errordemo.zip)

**Comment by klifa90** [comment] 2017-04-28 21:00
Is there any fix for this? Im currently facing the same issue.
![Check image](https://cloud.githubusercontent.com/assets/7662392/25547221/8aa03aee-2c3c-11e7-9e58-6b797e761a24.png)

**Closed** 2018-06-15 16:54 UTC
Labels: NeedInfo

**Comment by alloylab** [comment] 2018-06-15 17:59
is this still an issue on 0.12.5?

**Comment by LaCodon** [comment] 2018-06-15 18:13
I'm sorry but I haven't worked with wkhtmltopdf for a long while, so I can't help you with that question

**Comment by nvn01234** [comment] 2019-04-11 08:35
I have same problem. These are some information you may need to fix that issue.

**wkhtmltopdf version(s) affected**: [0.12.3 (with patched qt)](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz)

**OS information**
Server's OS: Ubuntu 14.04.5 LTS
Installed Font: "Times New Roman" via command `sudo apt install ttf-mscorefonts-installer`

**Description**
An empty space appeared below thead in page [4]. Note that I had `page-break-inside: avoid` in head.
```css
tr, td, th, thead, tfoot {
    page-break-inside: avoid !important;
}
```

**How to reproduce**
This is the html file (input.html) and pdf file generated by server (output.pdf): [input_output.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3067626/input_output.zip)
Command: 
```bash
cat input.html | wkhtmltopdf --page-size A4 --footer-font-name "Times New Roman" --orientation Landscape --footer-center "Trang [page] / [topage]" --footer-font-size 8 --quiet --dpi 400 - output.pdf
```

**Expected behavior**
The space should not appear below thead when page-break occur.

**Possible Solution**  
You can check the last row in page [3]. The height of the space seems to be same as height of that row. That row should be placed in page [4] instead of page [3] for better look. The calculation for page-break may cause this problem.
