### ISSUE TITLE
Div not display inline

### ISSUE THREAD

**Issue by shuhankuang** [wkhtmltopdf/wkhtmltopdf#1979] opened 2014-09-29 08:31 UTC
wkhtmltopdf 0.12.1 (with patched qt) Mac

I use purecss.io css framework. 

**_web page view**_
![image](https://dl.dropboxusercontent.com/u/2808098/git/01.png)

**_pdf view**_
![image](https://dl.dropboxusercontent.com/u/2808098/git/02.png)

if I add the css to div, it will work. but it will affect some elements. :(

```
div {float:left}
```

**Comment by alloylab** [comment] 2018-06-15 13:50
have you tried this on 0.12.5?

**Comment by Tomsgu** [comment] 2018-08-22 14:05
Closing as there is no feedback from the author and the issue is unclear in advance.

**Closed by Tomsgu** 2018-08-22 14:05 UTC
Labels: NeedInfo
