### ISSUE TITLE
wkhtmltopdf does not support Odoo 12 on Ubuntu 18.10

### ISSUE THREAD

**Issue by bamuqabel** [wkhtmltopdf/wkhtmltopdf#4311] opened 2019-03-28 14:15 UTC
**wkhtmltopdf version(s) affected**: 0.12.5 

**OS information**
Ubuntu Server 18.10

**Description**
I installed wkhtmltopdf on Ubuntu Server 18.10. The installation went well, but when I try to print my Odoo reports I get the message "Unable to find Wkhtmltopdf on this system. The report will be shown in html".

Is this related to the version of Ubuntu that is not supported by Wkhtmltopdf?

Thanks for your help.

**Comment by sherpya** [comment] 2019-04-03 15:47
odoo 12 template triggers FPE in wkhtmltopdf executable, I get the same result using stretch executable that works on my debian sid, so I suppose it's on dependend library

**Comment by sherpya** [comment] 2019-04-03 17:10
it's a bug in qt https://bugreports.qt.io/browse/QTBUG-45963?focusedCommentId=282116&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel

as workaround uninstall fonts-noto-color-emoji

**Comment by sherpya** [comment] 2019-04-03 17:15
duplicate of #4149

**Comment by ashkulz** [comment] 2019-04-04 09:47
Duplicate of #4149

**Closed by ashkulz** 2019-04-04 09:47 UTC
Labels: MayWorkWith0.13
