### ISSUE TITLE
[topage] seems to be one too many

### ISSUE THREAD

**Issue by cukal** [wkhtmltopdf/wkhtmltopdf#4015] opened 2018-07-20 11:57 UTC
Thanks for this piece of HTML to PDF printing mastery! 
Small note: I'm using ```--footer-right "[page] of [topage]"``` as footer. 
```[topage]``` always seems to count 1 page too many, like an amplifier that goes all the way to 11. 
If it would print 15 pages that last page would read ```page 15 of 16```, not 15 of 15.

Maybe I am doing something wrong?

**Comment by Tomsgu** [comment] 2018-07-21 06:03
Duplicate of #3889. You can also see #3952.

**Closed by Tomsgu** 2018-07-21 06:03 UTC

**Comment by ashkulz** [comment] 2020-06-07 08:27
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
