### ISSUE TITLE
issue with flex layout

### ISSUE THREAD

**Issue by ekbarber** [wkhtmltopdf/wkhtmltopdf#3421] opened 2017-04-04 15:55 UTC
I'm having trouble getting a flex layout to work in wkhtmltopdf 0.12.3.2 (with patched qt). I've looked through #1522 but haven't found a solution.  I'm trying to get 2 charts to render in equal sizes next to each. I'm using flex because it's possible for there to only be 1 chart, in which case I want it to render in the center and take up the full width.

When rendered in Chrome, it looks like the following.
![image](https://cloud.githubusercontent.com/assets/4382558/24665864/986b807a-192c-11e7-9f52-3dab0952afca.png)

However, once run through wkhtmltopdf, it comes out as
![image](https://cloud.githubusercontent.com/assets/4382558/24665878/a7c3396e-192c-11e7-8cde-af243a3fe036.png)

The html I use is 

```
<div class="part flex">
  <div class="part-content">
    <div class="chart"></div>
    <div class="chart"></div>
    <div class="clear"></div>
  </div>
  
</div>
```

And the css that goes along with that is:

```
div.part.flex > div.part-content{
	display: -webkit-box;
	display: -webkit-flex;
	display: flex;
}
div.part.flex > div.part-content > div:not(.clear){
	-webkit-box-flex: 1;
	-webkit-flex: 1;
	flex:1;
}
```

**Comment by dbanks6990** [comment] 2017-08-22 05:00
Did you ever get this to work?

**Comment by NiR-** [comment] 2017-08-23 12:10
Hello @dbanks6990, 

Based on HTML and CSS you provided, I tried to reproduce your issue but I was unable.

![image](https://user-images.githubusercontent.com/557933/29614922-5dcfc030-880c-11e7-9429-7232fa11dc8e.png)

What is in `.chart` element? Some images? Or some content generated by javascript? Are you sure this/these element(s) have a width of 100%? You can add some border to see which block does not have the right size.

**Comment by Tomsgu** [comment] 2018-08-09 11:33
Closing as there is no feedback since 2017.

**Closed by Tomsgu** 2018-08-09 11:33 UTC
Labels: Invalid
