### ISSUE TITLE
Request: One-page outputs

### ISSUE THREAD

**Issue by joshjacobson** [wkhtmltopdf/wkhtmltopdf#3058] opened 2016-08-02 18:54 UTC
As specified in the title, it'd be great to have an option for producing a 1 page .pdf.

There are two possible implementations:
1. Dynamically adjust page-height and page-width such that entire html is on single page of the necessary dimension to contain the entire output. (preferred)
2. Scale down the contents to fit a desired singe page size.

**Comment by PhilterPaper** [comment] 2016-08-04 14:52
Well, that kind of defeats the purpose of PDF, doesn't it? (At least, the first choice, to adjust page size.) If you want an indefinitely-long page, perhaps you should just stick with HTML and a browser. PDF is meant for dividing up content into _printable_ pages.

As for choice 2 (scale down), that _might_ be done, within reason, but you'd have to specify a minimum font size, lest text become microscopic in size!

**Comment by joshjacobson** [comment] 2016-08-04 14:55
@PhilterPaper I can understand your point of view, but there are indefinite use cases for different forms of content. There are use cases for .pdf that are outside of what you're imagining and are also outside of what I'd imaging. For my personal instance, HTML and a browser have 0 utility while a much longer single page .pdf would solve my need.

**Comment by ashkulz** [comment] 2016-11-24 06:55
Duplicate of #1627

**Closed by ashkulz** 2016-11-24 06:55 UTC
