### ISSUE TITLE
wkhtmltopdf dependency problem in Ubuntu 18 LTS

### ISSUE THREAD

**Issue by thite** [wkhtmltopdf/wkhtmltopdf#3914] opened 2018-05-14 18:10 UTC
Cannot install wkhtmltopdf in Ubuntu 18 LTS from link -
https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz

**Comment by ashkulz** [comment] 2018-05-15 04:28
Duplicate of #3001 -- use the 0.12.5 builds, there is a package for bionic.

**Closed** 2018-05-15 04:29 UTC
Labels: Duplicate
