### ISSUE TITLE
Multiple pages - undefined spacing on first colum on page

### ISSUE THREAD

**Issue by teufelmartin** [wkhtmltopdf/wkhtmltopdf#3120] opened 2016-09-13 16:36 UTC
i'm getting an issue that starting on page 4 spacing within the first row of each page is getting bigger an bigger.

Please see attached my html and pdf.

HTML:
https://gist.github.com/teufelmartin/546591ca91fc175a2a649fb44270caad

PDF:
https://we.tl/2emYvEZKmD

Maybe someone has an idea.

Thank you,
Martin

**Comment by PhilterPaper** [comment] 2016-09-13 17:25
#2978 is an earlier problem with rows increasing in size. I don't think a cure was found, but maybe you'll find something useful in the discussion.

**Comment by teufelmartin** [comment] 2016-09-14 07:08
Thank you, but nothing mentioned in the discussion really helps.

**Comment by navbhu** [comment] 2016-09-20 08:14
@teufelmartin  Which version of wkhtmltopdf are you using?  and when converting your html to pdf I'm getting only 21 pages (without images). I used 0.12.4 dev.

**Comment by teufelmartin** [comment] 2016-09-20 08:29
@navbhu is use wkhtmltopdf 0.12.3 (with patched qt) and the following command which results in 36 pages.
`wkhtmltopdf --dpi '72' --image-dpi '72' --image-quality '100' --margin-bottom '1.55cm' --margin-left '0cm' --margin-right '0cm' --margin-top '3.5cm' --page-height '22.5cm' --page-width '21cm' --no-pdf-compression --no-outline --enable-javascript --enable-local-file-access --print-media-type 'demo.html' 'demo.pdf'`

**Comment by navbhu** [comment] 2016-09-20 09:48
@teufelmartin I just tried this command  `wkhtmltopdf  --print-media-type 'demo.html' 'demo.pdf'` which results in PDF with 21 pages.

**Comment by Tomsgu** [comment] 2018-09-25 20:54
Closing as a duplicate of already mentioned issue #2978.

**Closed by Tomsgu** 2018-09-25 20:54 UTC
Labels: NeedInfo
