### ISSUE TITLE
Text is truncating at right side when i am converting in to pdf, but looks good in browser viewed as html

### ISSUE THREAD

**Issue by ruthraprakash** [wkhtmltopdf/wkhtmltopdf#4080] opened 2018-09-11 10:48 UTC
Hi, I have attached sample html file which contains css too which is working fine in browser. The design looks good in responsive too. But when i am converting this html file into Pdf using wkhtmltopdf, overflow text right to that box is truncated instead of wrapping. I tried using break-word also. This doesnt working. Can Someone give suggestion for this. I need to use disable-smart-shrinking also.

I am giving

 argument as 

"--header-spacing 5 --margin-top 20mm --disable-smart-shrinking read.html newpdf.pdf"

![image](https://user-images.githubusercontent.com/41108744/45355306-aaa2dc80-b5dd-11e8-9298-e921ae1fa3bf.png)

[samplehtmlfile.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2370645/samplehtmlfile.txt)

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Order-Customer</title>
	<style>
	
	 html, body, div, span, applet, object, iframe,
    h1, h2, h3, h4, h5, h6, p, blockquote, pre,
    a, abbr, acronym, address, big, cite, code,
    del, dfn, em, img, ins, kbd, q, s, samp,
    small, strike, strong, sub, sup, tt, var,
    b, u, i, center,
    dl, dt, dd, ol, ul, li,
    fieldset, form, label, legend,
    table, caption, tbody, tfoot, thead, tr, th, td,
    article, aside, canvas, details, embed,
    figure, figcaption, footer, header, hgroup,
    menu, nav, output, ruby, section, summary,
    time, mark, audio, video {
        margin: 0;
        padding: 0;
        border: 0;
        font-size: 100%;
        font: inherit;
        vertical-align: baseline;
    }
	
	ol, ul {
        list-style: none;
    }
	.content {
       /* width: 960px;*/
        margin: 0 auto;
        padding-left: 20px;
        padding-right: 20px;
        margin-top: 20px;
    }

    body {
        font-size: 16px;
        color: #333;
        line-height: 1.5;
        font-family: 'LatoLatinWeb', Tahoma, Verdana, sans-serif;
    }
	
	.data-block {
        padding-bottom: 20px;
        page-break-after: always !important;        
    }
	 .data-item {
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 20px;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: horizontal;
        -webkit-box-direction: normal;
        -ms-flex-flow: row nowrap;
        flex-flow: row nowrap;
        -webkit-box-pack: justify;
        -ms-flex-pack: justify;
        justify-content: space-between;
        page-break-inside: avoid !important;
    }
	.data-item__date {
        padding-left: 27px;
        -ms-flex-negative: 0;
        flex-shrink: 0;
    }
	.data-columns {
        -webkit-box-flex: 1;
        -ms-flex-positive: 1;
        flex-grow: 1;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: horizontal;
        -webkit-box-direction: normal;
        -ms-flex-flow: row nowrap;
        flex-flow: row nowrap;
        -webkit-box-pack: justify;
        -ms-flex-pack: justify;
        justify-content: space-between;
    }

    .data-columns__heading {
        margin-bottom: 10px;
    }

    .data-columns__item {
        width: 49%;
        -ms-flex-negative: 0;
        flex-shrink: 0;
    }

	</style>
</head>
<body>
<main class="content">
<div class="data-block">
<div class="data-block__content">
<div class="data-item">
                <div class="data-item__wrapper">
                    <div class="data-columns">
                        <div class="data-columns__item">
                            <p class="data-columns__heading">
                                <b>Sam Anderson</b>
                            </p>
                            <p>Customer card no:1233, He bought 50 items from card and through payment</p>
                        </div>
                        <div class="data-columns__item">
                                <p class="data-columns__heading label"> Comment</p>
                        </div>
                    </div>
                    <div class="data-item__date">07 Sep 2018</div>
                </div>
                    <div class="data-item__comments">
                        <p><b>Orders:</b></p>
                        <ul class="Order">
                                <li class="comments__comment">Please make the payment via online. Your orders will be delivered soon. Incase of any problem please contact our customer support</li>
                                <li class="comments__comment">Goods once sold cannot taken back. Please go through our documents carefully before investing it.</li>
                        </ul>
                    </div>
</div>
</div>
</div>
</main>
</body>
</html>

**Comment by ruthraprakash** [comment] 2018-09-11 15:31
Moreover i am using flex layout also..

**Comment by Tomsgu** [comment] 2018-09-26 15:26
flex is not supported in version 0.12.x.
Closing as duplicate of #3207

**Closed by Tomsgu** 2018-09-26 15:26 UTC
