### ISSUE TITLE
Table Header fields overlapping data when table spans 2 pages

### ISSUE THREAD

**Issue by Petoj87** [wkhtmltopdf/wkhtmltopdf#2367] opened 2015-05-20 06:54 UTC
I have the following html:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<body>
    <h1>Header</h1>
    <div>
        <span id="filterModeLabel" class="FilterMode">Show all</span>
        <table>
		<thead>
			<tr>
				<th>FirstName</th><th>LastName</th>
			</tr>
		</thead>
		<tbody>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
			<tr><td>Lisa</td><td>Test</td></tr>
		</tbody>
	</table>
    </div>
</body>
</html>
```

if i run this with wkhtmltopdf(0.12.2.1) i get the following on page 2:
![wkhtmltopdf error](https://cloud.githubusercontent.com/assets/1308309/7720440/9fa1c8f2-fecd-11e4-8b50-28c3b495949e.png)

i tried to check if the same error occurred in the alpha but the header is not rendered at all on page 2 and i have no idea how to enable it!

**Comment by loicbaechler** [comment] 2015-06-09 13:46
I have the same error on my ppc64ed server. Did you solve your problem?
I try with wkhtmltopdf(0.12.1.2)without success.

**Comment by Petoj87** [comment] 2015-06-09 13:48
Im sorry to say that i have not solved this error, i haven't even tried to solve it as its only a minor issue right now, at moment our tables don't span 2 pages in production but its only a matter for time until they do...

**Comment by Mathlight** [comment] 2015-06-10 13:09
Would love to see this problem fixed.

Here's an link to an Gist of my .html input: https://gist.github.com/Mathlight/fd0b651581c8cf23b92b#file-htmltopdf_big_file

On my Windows machine it will output an file of 370 pages and on the ubuntu server 570 (plus/minus). But that's just an font thing.

I've got exactly the same problem as you describe and would love to fix this problem. Maybe an temp fix of disabling the repeating headers, but don't know where i can do that (will dive into the docs right away!).

Here's an screenshot of the renderd PDF:
![screen shot 06-10-15 at 03 08 pm](https://cloud.githubusercontent.com/assets/3198886/8083112/91d7fb04-0f82-11e5-84d0-a665431a23ee.PNG)

**Comment by Mathlight** [comment] 2015-06-10 13:29
After some scrolling through the Issue tracker here, I found the solution.

Adding the following in the CSS fixes the table headers:

```
thead { display: table-header-group }
tfoot { display: table-row-group }
tr { page-break-inside: avoid }
```

Solution mention by @jwynia: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1770#issuecomment-73530576

**Comment by loicbaechler** [comment] 2015-06-11 08:25
Thank you! It works for me

**Comment by ashkulz** [comment] 2015-06-15 04:41
This is a duplicate of #1524, the workaround was mentioned in that issue.

**Closed by ashkulz** 2015-06-15 04:41 UTC

**Comment by joshuapinter** [comment] 2015-08-04 19:53
@Mathlight Absolutely brilliant solution by @jwynia. Works great.

**Comment by motoservo** [comment] 2015-11-08 01:45
I have this same issue and after trying a few suggestions here and on #1524 but finding that nothing was helping I started looking to see what more I could learn about this mis-rendering. I'm using Phantom 1.9 and the text overlays where both the thead and tr occupy the top spot after a page break. Oddly, in Phantom 2.0, for whatever reason, nothing occupies the top spot and there's just an empty space with the designated background color. But the thead is missing, altogether.

A strange thing I just discovered is that by setting a style...
thead th {
	height: 2.1cm;
}
The issue is resolved and to works fine. The really strange thing is, 2cm or less doesn't fix it. Only 2.1cm or higher. For those of you struggling with this issue you may want to try setting a height and see what happens.

Let me know what you find?

**Comment by johnheitor** [comment] 2016-07-31 17:25
A huge thanks to your solution  Mathlight, was pulling my hair out.

**Comment by gcgustavo** [comment] 2016-09-22 13:25
Big thanks to @Mathlight ! Worked like a charm !

**Comment by kaiza** [comment] 2016-11-29 21:56
@Mathlight 's solution worked for me but from what I can tell the only thing that's actually required is:

`tr { page-break-inside: avoid }`

**Comment by ilyakrasnov** [comment] 2017-01-04 12:16
Thanks a lot @Mathlight that solved it for me too! 👍

**Comment by sebasjimenez10** [comment] 2017-01-06 16:19
Thanks a lot @Mathlight worked like a charm 😄

**Comment by dinhnhat0401** [comment] 2017-02-21 07:59
Not working for me
<img src="https://i.imgflip.com/1k1jym.jpg" width=50%>
http://stackoverflow.com/questions/42341604/wicked-pdf-avoid-page-break-inside-not-working

**Comment by Zarnaik** [comment] 2017-03-12 13:45
Thanks @motoservo! The solution proposed by @Mathlight was not working for me.

@dinhnhat0401, try the solution motoservo described. Simply add `thead th { height: 1.1cm; }` to your print css.

**Comment by ankurpohekar** [comment] 2017-04-05 10:50
thead { display: table-header-group }
tfoot { display: table-row-group }
tr { page-break-inside: avoid }

This is the correct Solution for overlapping  between table row and table head in multi page PDF

**Comment by kiran3010p** [comment] 2017-05-09 13:16
The solution is not working for me. Our requirement we need to get the data data from DB means dynamic data.

**Comment by nasirkhan** [comment] 2017-06-24 05:45
Many of you suggested to hide the table header. But it was a must for me to show the header. The following CSS resolved the page header overlap issue, i hope this might help you too. 

I put my table info a DIV which has a class `export-table` and added the following CSS and it resolved the issue. 

```
@media print {
    .export-table {
        overflow: visible !important;
    }
}
```


You can updated your css like follows,

```
@media print {
    .class-name-which-holds-the-table {
        overflow: visible !important;
    }
}
```

**Comment by naardehaaien** [comment] 2017-06-30 10:53
Hi guys,

I tried the same, but will not work here, this is my code:

below some <link rel="stylesheet href="...."> lines, I put:
```
    <style type="text/css">
        thead { display: table-header-group }
        tfoot { display: table-row-group }
        tr { page-break-inside: avoid }
    </style>
```

the table is as

```
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Power</h3>
    </div>
    <div class="box-body">
        <table class="table table-striped table-bordered tree split-rows">
            <thead>
                <tr>
                    <th></th>
                    <th>Cables</th>
                    <th>Customer</th>
                    <th>Supplier</th>
                    <th>Load in</th>
                    <th>Load out</th>
                    <th>Info</th>
                </tr>
            </thead>
            <tbody>
                 <tr>
                      <td>data<td>
                      <td>data<td>
                      <td>data<td>
                      <td>data<td>
                      <td>data<td>
                      <td>data<td>
                      <td>data<td>
                 </tr>
            </tbody>
        </table>
    </div>
</div>
```

it still looks like overflowing

![image](https://user-images.githubusercontent.com/29059382/27732733-fe82a366-5d92-11e7-8af5-0d9244d54485.png)

anyone has a suggestion?

**Comment by makkoman** [comment] 2017-08-30 20:28
Just solved a similar issue with the suggestion of @motoservo 
You'll want to check the options being passed to wkhtmltopdf. Mine worked after I passed the flag `--print-media-type`

**Comment by tristanmarsh** [comment] 2017-09-01 01:19
I was only able to prevent the thead duplication over the tbody for one table in a particularly complicated invoice template by removing the thead element. I imagine this is more of a problem with the Chrome rendering engine. The issue was coming through in test prints and PDF exports from Chrome, although it will be used with Athena PDF.

**Comment by montao** [comment] 2017-10-23 01:15
I could resolve this issue by removing all CSS and incrementally adding only the CSS needed. Now our table renders nicely over several pages both with proper pagebreak and table headers which don't overlap. Thanks!

**Comment by dpjain** [comment] 2017-11-23 14:08
Thanks!! It worked for me...

**Comment by unlessbamboo** [comment] 2018-04-11 03:48
@Mathlight  if the table construct is:
<table>
<thead>...</thead>
<tbody>
  <tr>
     <td>
         <div>
           <table>Actual content is here, many lines and may be split into different pages</table>
           <table></table>
           ...
         </div>
      </td>
    </tr>
</tbody>
</table>

At this situation, CSS style may be :

`       
        thead { display: table-row-group;}
        tfoot { display: table-row-group }
        tr { page-break-inside: avoid }
`

this work for me.

**Comment by adihat** [comment] 2018-05-12 04:01
@Mathlight Thanks for the solution. worked for me too

**Comment by josecanchila** [comment] 2018-06-12 16:27
@Mathlight comment solve my issue, thanks you!

**Comment by iainheng** [comment] 2018-07-06 06:07
@Mathlight solution is fine most of the time but it will render a big space if the row has a long content inside as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/3263759/42362401-a9fceac4-8125-11e8-88ea-29febe51cd96.png)

**Comment by Mancini-Rafael** [comment] 2018-07-19 16:54
This may not work for everyone, but when i added the page-break: avoid on both the td and tr elements, everything went smooth (also used important). Like this:

```
tr { 
  page-break-inside: avoid !important;
}

td { 
  page-break-inside: avoid !important;
}
```

**Comment by daj1234** [comment] 2018-08-10 08:29
Hi,

Can you please help me. I've tried all solutions above and header and 2nd page are still overlapping.

[print pdf.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2277140/print.pdf.zip)

**Comment by Tomsgu** [comment] 2018-08-10 08:36
@daj1234 Have you read some workarounds from the #1524 issue?

**Comment by daj1234** [comment] 2018-08-10 08:39
Hi @Tomsgu 

Yes I did, I also posted in that thread as well. I have tried every solution recommended in that thread and in this thread but I have failed to fix the problem.

Because I am really new to html, so I am not sure if I am applying the fix correctly on my code.

**Comment by Tomsgu** [comment] 2018-08-10 08:59
@daj1234 I saw attached files and the html is broken even in a browser.
- According to http://www.htmlhelp.com/tools/validator/doctype.html I don't see `<!DOCTYPE pdf` 
- What `<pdf>` tags suppose to do?
- `<#if ...` is not a valid html tag neither. If you use some kind of templating system, you should attach at least a final html. 

Please ask in stackoverflow if you have more questions since this seems to not be a problem of wkhtmltopdf.

**Comment by daj1234** [comment] 2018-08-10 09:52
@Tomsgu 

Thank you for your response! I just manually adjusted the header-height so it won't overlap on the next page.

**Comment by mutasam** [comment] 2018-09-22 09:55
i tried all the above suggestions but nothing worked for me .
after a cup of tea and hours staring to code i figured out the problem was the stupid 
`position: relative; bottom: 2cm;`
so if u have a relative position any where in your code removed it now. 
and absolutely add
`thead { display: table-header-group }
tfoot { display: table-row-group }
tr { page-break-inside: avoid }`

**Comment by vishalksuthar** [comment] 2018-10-05 11:34
> After some scrolling through the Issue tracker here, I found the solution.
> 
> Adding the following in the CSS fixes the table headers:
> 
> ```
> thead { display: table-header-group }
> tfoot { display: table-row-group }
> tr { page-break-inside: avoid }
> ```
> Solution mention by @jwynia: [#1770 (comment)](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1770#issuecomment-73530576)

Thanks you so mutch.

**Comment by anls** [comment] 2018-10-15 08:30
After some scrolling through the Issue tracker here, I found the solution.

Adding the following in the CSS fixes the table headers:

thead { display: table-header-group }
tfoot { display: table-row-group }
tr { page-break-inside: avoid }
Solution mention by @jwynia: #1770 (comment)

**Comment by roshimon** [comment] 2018-12-12 06:05
> After some scrolling through the Issue tracker here, I found the solution.
> 
> Adding the following in the CSS fixes the table headers:
> 
> ```
> thead { display: table-header-group }
> tfoot { display: table-row-group }
> tr { page-break-inside: avoid }
> ```
> Solution mention by @jwynia: [#1770 (comment)](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1770#issuecomment-73530576)

Thank you so much :+1:

**Comment by ArDotWeb** [comment] 2019-04-01 14:09
`          table { page-break-inside:auto } 
            tr { page-break-inside:avoid; page-break-after:auto } 
            thead { display:table-header-group } 
            tfoot { display:table-footer-group } `

**Comment by a8568730** [comment] 2019-07-30 02:34
```
tr { page-break-inside: avoid }
```
It works for me ~~ Mint 18.3 Cinnamon 64-bit 3.6.7.

**Comment by brave-orange** [comment] 2019-08-19 05:21
` tr { 
  page-break-inside: avoid !important;
}
`
@Mathlight thank you,it worked for me

**Comment by fredtma** [comment] 2019-08-26 10:26
If you are using passing the header option in the template, make sure use 

`<body  style='margin-bottom: 2pt;'>`

Whilst still using the CSS solution above.

**Comment by birendrapradhan72** [comment] 2019-09-19 13:55
> This may not work for everyone, but when i added the page-break: avoid on both the td and tr elements, everything went smooth (also used important). Like this:
> 
> ```
> tr { 
>   page-break-inside: avoid !important;
> }
> 
> td { 
>   page-break-inside: avoid !important;
> }
> ```

it works perfect.

**Comment by seetpalsingh** [comment] 2019-09-25 11:56
Hi there, I am using debian8 inside Docker over iMac.

I'm getting table header regenerated on my iMac with wkhtmltopdf@0.12.4 

but, in docker debian8 with wkhtmltopdf@0.12.4, it's not repeating table header
[pdf.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3652254/pdf.pdf)

**Comment by pradipyenpure7** [comment] 2019-12-10 12:16
I am using wkhtmltopdf @0.12.5 , its repeating table header but overlapping text description on second page , please help me

**Comment by pradipyenpure7** [comment] 2019-12-10 12:19
I am using wkhtmltopdf @0.12.5 , if text-description is long then its directly move to second page and skipped the 1st page printing start from second page ,how to overcome this issue ?
Please help me?

**Comment by HaiLe81** [comment] 2020-11-23 07:46
> <img alt="" width="50%" src="https://camo.githubusercontent.com/172b7d354056fe5290daa6f4568933ec91eb10934d63452a8cb8bea1f14f11cd/68747470733a2f2f692e696d67666c69702e636f6d2f316b316a796d2e6a7067">
> 
> Added question here:
> http://stackoverflow.com/questions/42341604/wicked-pdf-avoid-page-break-inside-not-working

Hi @dinhnhat0401. Have you fixed that problem? 
If you have done it. Can give me a solution to fix it?

**Comment by SandipKordiya** [comment] 2021-03-28 22:00
> thead { display: table-header-group }
> tfoot { display: table-row-group }
> tr { page-break-inside: avoid }

Thank you so much. its working
