### ISSUE TITLE
--header-html not displayed in version 0.12

### ISSUE THREAD

**Issue by japeldoorn** [wkhtmltopdf/wkhtmltopdf#2042] opened 2014-11-10 16:43 UTC
We upgraded to version 0.12 of wkhtmltopdf, from version 0.10, today, but when using the following command line options to generate a PDF:

wkhtmltopdf.exe --margin-top 20 --margin-bottom 20 --margin-left 20 --margin-right 20 --print-media-type --header-html [URL] --footer-html [URL] [URL] -

the header does not get displayed in the PDF.
If we use the same HTML page as the footer, it does get displayed, so we asume the problem lies within wkhtmltopdf somewhere.

In the old version, the header does get displayed (using the same command line syntax)

We need version 0.12 as version 0.10 does not support non-SSLv3 https connections.

Is there any quick fix available?

**Comment by giniedp** [comment] 2015-02-20 11:54
It seems like the top/bottom margins must be as large as the header/footer elements. I was wondering why my header and footer are not rendering but i had the margins set to 0. This causes the elements to be pushed out of the page.

**Comment by NessterGit** [comment] 2015-04-17 15:00
Anybody found a fix for this, I also got the DOCTYPE, even tried my functionnal footer in the header and it doesn't show up.

**Comment by ashkulz** [comment] 2015-04-18 04:16
Nobody has posted a reproducible, minimal testcase which demonstrates this issue.

**Comment by kfulkerson** [comment] 2015-05-11 18:17
I am experiencing the same problem I am using wkhtmltopdf .12.2.1 on an Apache server.  I am using mikehaertl / phpwkhtmltopdf to convert html pages into pdfs in my Yii project. The --footer-html option works fine but --header-html doesn't work at all. My bottom and top margins are both set to 10 so to give space for the header and footer.  What I did find interesting was when creating a pdf from the Apache terminal command line using wkhtmltopdf --header-html.............  it did work and my header was inserted on the pdf. Has anybody experienced this? Thanks

**Comment by ashkulz** [comment] 2015-06-23 09:21
@kfulkerson: looks like you could be bitten by #2183, which should be fixed in a few hours.

**Closed by ashkulz** 2015-06-23 09:21 UTC
Labels: NeedInfo

**Comment by ashkulz** [comment] 2015-07-14 01:14
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Please note that the above downloads will be removed after the `0.12.3` release*.

**Comment by TimBozeman** [comment] 2015-07-15 19:57
I tried 0.12.3-dev-79ff51e on trusty. I am using 
    <!DOCTYPE html>
    <html>
      <head>
        <title>MAIN</title>
      </head>
      <body style="background:Green;">
        <h1>MAIN</h1>
      </body> 
    </html>
as a header and footer with mikehaertl / phpwkhtmltopdf and I only get the footer to show. If I add a margin-top => 200 some 
![selection_418](https://cloud.githubusercontent.com/assets/2164987/8708482/1af0f22c-2af1-11e5-8f87-a8fb74e1bafa.png)
green does show, but no text.

**Comment by prcongithub** [comment] 2017-03-24 07:51
Any update on this? I am facing this problem with (wkhtmltopdf 0.12.4 (with patched qt) and wicked_pdf (1.1.0)
My render hash looks like this.
```
hash = {
      pdf: "report_#{params[:id]}.pdf",
      header: {
        :html => {
          template: "shared/reports/pdf/_report_header.pdf.haml",
          layout: "layouts/#{layout}"
        }
      },
      footer: {
        :html => {
          template: "shared/reports/pdf/_report_footer.pdf.haml",
          layout: "layouts/#{layout}"
        }
      },
      zoom: 1.5,
      disable_smart_shrinking: false,
      template: "assessment_reports/#{template}",
      layout: "layouts/#{layout}",
      handlers: [ :haml ],
      margin: { :left => "0mm",:right => "0mm", :top => "13mm", :bottom => "12mm" },
      formats: [:pdf],
     }
```
The html contains this doctype 
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
```

**Comment by JFossey** [comment] 2018-01-31 11:02
I have been able able to create a reproducible test case for this.

## wkhtmltopdf 0.12.4 (with patched qt)

### Header Shows
`wkhtmltopdf-amd64 --header-html 'http://test.dev/pdf-header' 'http://test.dev/pdf-body' 'test.pdf'`

### Header Does not show at all
`wkhtmltopdf-amd64 --margin-top '10mm' --header-html 'http://test.dev/pdf-header' 'http://test.dev/pdf-body' 'test.pdf'`

### Bottom half of Header shows
`wkhtmltopdf-amd64 --margin-top '20mm' --header-html 'http://test.dev/pdf-header' 'http://test.dev/pdf-body' 'test.pdf'`

### Full Header Shows correctly
`wkhtmltopdf-amd64 --margin-top '40mm' --header-html 'http://test.dev/pdf-header' 'http://test.dev/pdf-body' 'test.pdf'`

### Assessment

There seems to be some sort of calculations taking place between `header-html` and `margin-top` and when no margin-top is specified the header displays but using some sort of default spacing.

When a `margin-top` is set the placement of the header seems to use the margin-top but subtracts the header height or something similar first when positioning the header.

This was confirmed by adding content to the header to see if its placement changes but keeping the margin-top constant.

### Workaround

1. Dont use margin-top and use the the default placement and spacing
1. Increase your margin-top until the placement is correct, a rough guide is add the approximate height of your header to your margin-top

**Comment by DaveWishesHe** [comment] 2018-06-22 13:50
In addition to @JFossey's detail here, I'd like to add that it _appears_ that the number of new lines within the header being rendered directly affects the amount of white space above the header. Note the gradually increasing white space in the attached 3 screengrabs.

![a](https://user-images.githubusercontent.com/4179596/41780039-7edd5568-762b-11e8-8d06-6846d5959ea9.png)
![b](https://user-images.githubusercontent.com/4179596/41780038-7ec290d4-762b-11e8-964c-2066d3322a60.png)
![c](https://user-images.githubusercontent.com/4179596/41780037-7ea6b5d0-762b-11e8-8276-6a859b7e9ebe.png)
