### ISSUE TITLE
Large quantity of images error

### ISSUE THREAD

**Issue by kornushkin** [wkhtmltopdf/wkhtmltopdf#2757] opened 2016-01-14 13:27 UTC
Hi! Please help me to solve the problem with large quantity of images in generated PDF.
After some quantity of added images to PDF file I've got an error and images replaced with blue squares with "?" sign.

Images exist in filesystem.

http://i.imgur.com/EkggfO3.png

wkhtmltopdf version: "wkhtmltopdf 0.12.0 final"
OS version: "Ubuntu 14.04.3 LTS" 

Error message:
The exit status code '1' says something went wrong: stderr: "" stdout: "Loading page (1/2) [> ] 0% [======> ] 10% [=======> ] 12% [=======> ] 12% [=======> ] 12% [=======> ] 12% [=======> ] 12% [=======> ] 12% [=======> ] 12% [=======> ] 12% [=======> ] 12% [=======> ] 13% [=======> ] 13% [========> ] 14% [========> ] 14% [========> ] 14% [========> ] 14% [========> ] 14% [=========> ] 15% [=========> ] 15% [=========> ] 15% [=========> ] 15% [=========> ] 15% [=========> ] 16% [=========> ] 16% [=========> ] 16% [=========> ] 16% [=========> ] 16% [=========> ] 16% [=========> ] 16% [=========> ] 16% [==========> ] 17% [==========> ] 17% [==========> ] 17% [==========> ] 17% [==========> ] 17% [==========> ] 17% [==========> ] 17% [==========> ] 17% [==========> ] 18% [==========> ] 18% [==========> ] 18% [==========> ] 18% [===========> ] 19% [===========> ] 19% [===========> ] 19% [===========> ] 19% [===========> ] 19% [============> ] 20% [============> ] 20% [============> ] 20% [============> ] 20% [============> ] 20% [============> ] 20% [============> ] 21% [============> ] 21% [============> ] 21% [=============> ] 23% [===============> ] 25% [================> ] 27% [=================> ] 29% Warning: Failed to load file:///var/www/web/catalog/thumbs/1231231452704687.jpg (ignore) Warning: Failed to load file:///var/www/web/catalog/thumbs/treadway_toomey_auctions_UNITED_STATES2016_02_06_159_1_1452704678.jpg (ignore) Warning: Failed to load file:///var/www/web/catalog/thumbs/treadway_toomey_auctions_UNITED_STATES2016_02_06_159_2_1452704680.jpg (ignore) Warning: Failed to load file:///var/www/web/catalog/thumbs/sofe_design_auctions_UNITED_STATES2016_01_23_77_1_1452704624.jpg (ignore) Warning: Failed to load file:///var/www/web/catalog/thumbs/sofe_design_auctions_UNITED_STATES2016_01_23_77_2_1452704627.jpg (ignore) Warning: Failed to load file:///var/www/web/catalog/thumbs/sofe_design_auctions_UNITED_STATES2016_01_23_77_3_1452704630.jpg (ignore) Warning: Failed to load file:///var/www/web/catalog/thumbs/greenwich_auction_UNITED_STATES2016_01_17_420_1_1452704602.jpg (ignore) Warning: Failed to load file:///var/www/web/catalog/thumbs/greenwich_auction_UNITED_STATES2016_01_17_420_2_1452704605.jpg (ignore) Warning: Failed to load file:///var/www/web/catalog/thumbs/greenwich_auction_UNITED_STATES2016_01_17_420_3_1452704607.jpg (ignore) Warning: Failed to load 
....

**Comment by lkraider** [comment] 2017-08-16 21:04
I was having the same issue, running `strace` I found the cause was limit of open files (default 1024):

```
fcntl(1022, F_SETFD, FD_CLOEXEC)        = 0
fstat(1022, {st_mode=S_IFREG|0664, st_size=94178, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=127, ...}) = 0
stat("/home/ubuntu/tmp/5938CFA5-C3D7-4EB8-9236-578B4898B25E/Photos/E1D899F3-C498-490B-9311-73E28E979D4C.jpg", {st_mode=S_IFREG|0664, st_size=101373, ...}) = 0
open("/home/ubuntu/tmp/5938CFA5-C3D7-4EB8-9236-578B4898B25E/Photos/E1D899F3-C498-490B-9311-73E28E979D4C.jpg", O_RDONLY|O_CLOEXEC) = 1023
fcntl(1023, F_SETFD, FD_CLOEXEC)        = 0
fstat(1023, {st_mode=S_IFREG|0664, st_size=101373, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=127, ...}) = 0
brk(0x37a7000)                          = 0x37a7000
stat("/home/ubuntu/tmp/5938CFA5-C3D7-4EB8-9236-578B4898B25E/Photos/A0B5AFA2-ED68-40AF-A90D-BB69C1FA0C8E.jpg", {st_mode=S_IFREG|0664, st_size=60283, ...}) = 0
open("/home/ubuntu/tmp/5938CFA5-C3D7-4EB8-9236-578B4898B25E/Photos/A0B5AFA2-ED68-40AF-A90D-BB69C1FA0C8E.jpg", O_RDONLY|O_CLOEXEC) = -1 EMFILE (Too many open files)
lstat("/home/ubuntu/tmp/5938CFA5-C3D7-4EB8-9236-578B4898B25E/Photos/A0B5AFA2-ED68-40AF-A90D-BB69C1FA0C8E.jpg", {st_mode=S_IFREG|0664, st_size=60283, ...}) = 0
stat("/home/ubuntu/tmp/5938CFA5-C3D7-4EB8-9236-578B4898B25E/Photos/D1EF9355-395F-4BB0-BD92-37594CF8E0A5.jpg", {st_mode=S_IFREG|0664, st_size=115174, ...}) = 0
open("/home/ubuntu/tmp/5938CFA5-C3D7-4EB8-9236-578B4898B25E/Photos/D1EF9355-395F-4BB0-BD92-37594CF8E0A5.jpg", O_RDONLY|O_CLOEXEC) = -1 EMFILE (Too many open files)
lstat("/home/ubuntu/tmp/5938CFA5-C3D7-4EB8-9236-578B4898B25E/Photos/D1EF9355-395F-4BB0-BD92-37594CF8E0A5.jpg", {st_mode=S_IFREG|0664, st_size=115174, ...}) = 0
stat("/home/ubuntu/tmp/5938CFA5-C3D7-4EB8-9236-578B4898B25E/Photos/76EF0344-2907-4DCA-9126-324247E64B67.jpg", {st_mode=S_IFREG|0664, st_size=128819, ...}) = 0
open("/home/ubuntu/tmp/5938CFA5-C3D7-4EB8-9236-578B4898B25E/Photos/76EF0344-2907-4DCA-9126-324247E64B67.jpg", O_RDONLY|O_CLOEXEC) = -1 EMFILE (Too many open files)
lstat("/home/ubuntu/tmp/5938CFA5-C3D7-4EB8-9236-578B4898B25E/Photos/76EF0344-2907-4DCA-9126-324247E64B67.jpg", {st_mode=S_IFREG|0664, st_size=128819, ...}) = 0
stat("/home/ubuntu/tmp/5938CFA5-C3D7-4EB8-9236-578B4898B25E/Photos/C11875D4-F767-48BD-AA95-D711EB7FF46C.jpg", {st_mode=S_IFREG|0664, st_size=105590, ...}) = 0
open("/home/ubuntu/tmp/5938CFA5-C3D7-4EB8-9236-578B4898B25E/Photos/C11875D4-F767-48BD-AA95-D711EB7FF46C.jpg", O_RDONLY|O_CLOEXEC) = -1 EMFILE (Too many open files)
(...)
```

Setting a higher limit before running the command fixed the issue:
` ulimit -n 4096 `

**Comment by Tomsgu** [comment] 2018-09-05 09:03
Closing as an answer was provided.

**Closed by Tomsgu** 2018-09-05 09:03 UTC
Labels: Question
