### ISSUE TITLE
No header, footer, nor CSS on Odoo reports.

### ISSUE THREAD

**Issue by Segebre** [wkhtmltopdf/wkhtmltopdf#3030] opened 2016-07-08 06:23 UTC
Hi,

I have been trying about a week now to solve this issue. I have tried different versions and many other solutions I have found over these last 6 days, none of them have worked.

I have tried following these steps: http://askubuntu.com/questions/556667/how-to-install-wkhtmltopdf-0-12-1-on-ubuntu-server

Also i have tried these: http://www.odoo.yenthevg.com/install-wkhtmltopdf-on-ubuntu/

I have tried following these steps: https://www.odoo.com/forum/help-1/question/how-to-install-wkhtmltopdf-0-12-0-version-in-server-56107
, but the address is broken so I used these instead: http://download.gna.org/wkhtmltopdf/0.12/0.12.0/wkhtmltox-linux-amd64_0.12.0-03c001d.tar.xz
                                                                            http://download.gna.org/wkhtmltopdf/0.12/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz

I have even tried the 32bit versions of each of them. Desperately I have no idea what else to do. And finally i ask you, how can i solve this issue?

This is the HTML version and how it is supposed to look as PDF: ![howitshouldlook](https://cloud.githubusercontent.com/assets/10774915/16679045/fee852de-44a1-11e6-982b-cc84137b2544.png)

This is the PDF version after being converted from HTML, this is how it looks: ![howitlooks](https://cloud.githubusercontent.com/assets/10774915/16678968/7099fcda-44a1-11e6-80c6-1ab60fd02d1e.png)

**Comment by m3asmi** [comment] 2016-09-21 17:19
same problem here 
I use ubuntu 16.04 amd64

**Comment by Tomsgu** [comment] 2018-09-25 18:30
Closing as the issue is quite old and has no information that can help to reproduce a bug, so it's difficult to fix/help something. In any case it seems like a css file is ignored.

**Closed by Tomsgu** 2018-09-25 18:30 UTC
Labels: NeedInfo
