### ISSUE TITLE
Footer center does not show when using header-html

### ISSUE THREAD

**Issue by jbrumwell** [wkhtmltopdf/wkhtmltopdf#3064] opened 2016-08-06 02:35 UTC
If I include the `header-html` option and `footer-center` the footer does not show. If I omit the `header-html` option the footer shows up.

**Comment by jbrumwell** [comment] 2016-08-08 20:00
Looks to be any footer commands;

`wkhtmltopdf --quiet --print-media-type --footer-center "[page]" --header-spacing 5 --footer-spacing 5 --page-size "letter" --orientation "Portrait" --viewport-size "1280x1024" --header-html "/tmp/tmp-9543Jiil4ZT2DGZI.html"`

Results in no footer, if you remove the header-html option the footer generates as expected

**Comment by LuizFeReis** [comment] 2016-09-06 19:14
Same problem here, can't use Header and Footer together, only the header shows up.

Windows 7 64 (wkhtmltopdf 0.12.2.2 (with patched qt))

**Comment by Schtorsk** [comment] 2016-12-08 14:36
I thought I had the same problem too. But I really needed to combine` header-html` with `footer-center` so I persevered. Turns out it was just a margin problem.

This does not work:
`--footer-center "[page]/[toPage]" --header-html "someUrlToHtmlFile"`

This does:
`--footer-center "[page]/[toPage]" --header-html "someUrlToHtmlFile" --margin-top 35mm --margin-bottom 15mm"`

Maybe you're facing the same problem?

**Comment by sunding0308** [comment] 2018-01-09 06:46
@Schtorsk thank you very much!

**Comment by Tomsgu** [comment] 2018-09-05 09:53
Closing as duplicate of #2796.

**Closed by Tomsgu** 2018-09-05 09:53 UTC
Labels: NeedInfo
