### ISSUE TITLE
Rotated elements not rendered on thead on second page and beyond

### ISSUE THREAD

**Issue by Viburnum** [wkhtmltopdf/wkhtmltopdf#1914] opened 2014-08-18 11:48 UTC
## What steps will reproduce the problem?

Create a table with THEAD header and TBODY long enough to require more pages
Create inside the TH of the the header a DIV with some content and add the css property:
`-webkit-transform: rotate(270deg);`
## What is the expected output?

To have each page repeat the THEAD with the rotated element.
## What do you see instead?

Rotated elements are removed from page 2 and beyond. 
## What version are you using?

Using: 
- Linux: Precompiled 64bit 0.12.1 from https://github.com/h4cc/wkhtmltopdf-amd64 
- Windows: 64bit 0.12.1 (MSVC 2013)
## On what operating system?
- Debian Wheezy 64bit
- Windows 7 64bit

**Comment by rruchte** [comment] 2016-01-31 23:16
Here is a patch that correctly renders rotated headers inside the repeated table heads. This covers the basic scenario where you have block level elements with a transform applied directly inside the cells. It's kind of ugly but it works consistently for my needs. I'm not a WebKit guru, so there may be a cleaner way to do this.
rruchte/qt@1390363bda159c4e6e835dfe97ec9b9f497b1f63

**Comment by j0n4s** [comment] 2016-07-06 18:16
excuse me, What does it mean "PatchNeed"?, I have install **wkhtmltopdf 0.12.3 (with patched qt)** and I have the rotate in second page problem..

**Comment by Wjat777** [comment] 2016-11-23 14:09
This issue occurs with [0.12.4](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.4) version too. The [rccuchte patch's](https://github.com/wkhtmltopdf/qt/compare/wk_4.8.7...rruchte:fix_transformed_table_header_repeat) is not merged.

**Comment by ashkulz** [comment] 2016-11-23 17:06
Sorry, didn't see his patch. Will review and see if it can be merged.

**Comment by emielmolenaar** [comment] 2017-01-02 13:41
It would be very nice if this issue gets fixed. Hoping that the submitted patch is OK.

**Comment by chourie2** [comment] 2017-02-03 14:06
Same for me here, I'm struggling with this issue too.

It would really help me, just to have an update on the situation. Have you found the time to do the review? Or is it planed to work on it, or not anymore?

Thank you in advance for your time!

**Comment by ashkulz** [comment] 2017-03-22 04:50
I've applied the patch by @rruchte as-is. Thanks for the contribution!

**Closed** 2017-03-22 04:50 UTC
Labels: HasPatch

**Comment by DarshanKsheerasagar** [comment] 2017-04-06 06:15
Hello @ashkulz ,

Generate PDF using HTMl string with page break is not proper working ... Below is my Code and Output

Default.aspx

<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="wkhtmltopdfTest._Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="PrintStyle.css" rel="stylesheet" type="text/css" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
    <form id="form1" runat="server">
     <asp:Button ID="Button1" runat="server" Text="Download" OnClick="btnExport_Click" />
    <div >
        <asp:Panel ID="pnlPerson" runat="server">
            <div>
                <table style="width: 785px;">
                    <tr>
                        <td>
                            First Page
                        </td>
                    </tr>
                    <tr class="page-break">
                        <td >
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Second Page
                        </td>
                    </tr>
                    <tr class="page-break">
                        <td >
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Third Page
                        </td>
                    </tr>
                    <tr class="page-break">
                        <td >
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Fourth Page
                        </td>
                    </tr>
                    <tr class="page-break">
                        <td >
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Five Page
                        </td>
                    </tr>
                </table>
            </div>
        </asp:Panel>
    </div>
   
    </form>
</body>
</html>


Default.cs.aspx

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Diagnostics;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

namespace wkhtmltopdfTest
{
    public partial class _Default : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
        }
        protected void btnExport_Click(object sender, EventArgs e)
        {
            try
            {
                string PrintStyle = System.IO.File.ReadAllText(Server.MapPath("/PrintStyle.css"));

                StringWriter sw = new StringWriter();
                HtmlTextWriter hw = new HtmlTextWriter(sw);

                pnlPerson.RenderControl(hw);
                StringReader sr = new StringReader(sw.ToString());



                string outXml = "<html> <head> " +
                                "<style type=\"text/css\">  " + PrintStyle + " </style> " +
                                "</head> <body> <div>" + sw.ToString() + " " +
                                " </div></body> </html>";
                //table, tr, td, th, tbody, thead, tfoot { page-break-inside: avoid !important;}  
                //tr{display:block;}

                byte[] result = ConvertHtmlToPdf(outXml);


                HttpContext.Current.Response.Clear();
                Response.ContentType = "application/pdf";
                string outputFilename = "Report" + "_" + DateTime.Now.ToString("yyyy-MM-dd-hh-mm-ss-fff") + ".pdf";
                Response.AddHeader("content-disposition", "attachment;filename=" + outputFilename);
                Response.CacheControl = "No-cache";
                MemoryStream ms = new MemoryStream(result);
                ms.WriteTo(Response.OutputStream);
                Response.Flush();
                Response.SuppressContent = true;
                HttpContext.Current.ApplicationInstance.CompleteRequest();

            }
            catch(Exception ex)
            {
            }
        }
        protected byte[] ConvertHtmlToPdf(string html)
        {
            System.Reflection.Assembly ass = System.Reflection.Assembly.GetExecutingAssembly();
            string conPath = System.IO.Path.GetDirectoryName(ass.CodeBase);
            Uri uri = new Uri(conPath);
            conPath = uri.AbsolutePath.Replace("%20", " ").Replace("25", "");
            conPath = Path.GetFullPath(Path.Combine(conPath, @"..\"));
            conPath = conPath + "bin\\wkhtmltopdf.exe";
            var p = new Process
            {
                StartInfo =
                {
                    CreateNoWindow = true,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    RedirectStandardInput = true,
                    UseShellExecute = false,
                    FileName = conPath
                }
            };
            string s = "-q ";
            s += "--margin-bottom 0 ";
            s += "--margin-right 0 ";
            s += "--margin-left 0 ";
            s += "--margin-top 0 ";
            s += "--page-size A4 ";
            s += "--print-media-type ";
            s += "--disable-smart-shrinking ";
            s += "- -";
            p.StartInfo.Arguments = s;
            p.Start();
            StreamWriter myStreamWriter = new StreamWriter(p.StandardInput.BaseStream, Encoding.UTF8);
            myStreamWriter.Write(html);
            myStreamWriter.Close();
            var buffer = new byte[32768];
            byte[] file;
            using (var ms = new MemoryStream())
            {
                while (true)
                {
                    var read = p.StandardOutput.BaseStream.Read(buffer, 0, buffer.Length);
                    if (read <= 0)
                    {
                        break;
                    }
                    ms.Write(buffer, 0, read);
                }
                file = ms.ToArray();
            }
            p.WaitForExit(60000);
            var returnCode = p.ExitCode;
            p.Close();
            return returnCode == 0 ? file : null;
        }
    }
}


PrintStyle.css

 @media print 
 { 
     tr.page-break  {display: block;page-break-after: always; }
 }


Output :

![pagebreakissue](https://cloud.githubusercontent.com/assets/24871149/24740381/7a48f3e6-1abe-11e7-91c9-ed947c8ae5d6.JPG)

**Comment by ashkulz** [comment] 2018-05-30 03:55
A release candidate [is available](https://wkhtmltopdf.org/downloads.html#release-candidate) which includes the fixes made in wkhtmltopdf/qt@c745cfd57fbba4f2fe6e17dc95d7a8a3a4c57829 -- please test and report your findings before the final release.

**Comment by craue** [comment] 2018-06-07 08:39
Unfortunately, I can't see any difference in the results rendered with 0.12.4 and 0.12.5-rc (`wkhtmltox-0.12.5-0.20180604.140.rc~6f77c46~msvc2015-win64.exe`). Rotated text in thead is still missing on following pages.

**Comment by ashkulz** [comment] 2018-06-07 09:32
@craue: the patch by @rruchte was not a full fledged solution, maybe you can share the exact scenario in which it is failing?

**Comment by rruchte** [comment] 2018-06-07 13:29
@craue The patch covers cases like the following, where there is a rotated block inside the table head cell.

```html
<table>
    <thead>
        <tr>
            <th style="font-size: 12px; height: 75px; vertical-align: bottom; width: 24px; white-space: nowrap; padding: 4px;overflow: hidden;">
                <div style="transform: rotate(270deg);width: 24px;padding-left: 6px;">Rotated Text</div>
            </th>
        </tr>
    </thead>
</table>
```

**Comment by craue** [comment] 2018-06-07 13:54
I tried narrowing down the cause and found out that the header text is placed differently on following pages which in conjunction with other CSS (especially `overflow: hidden`) made it disappear completely.

code:
```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8" />
		<style type="text/css">
			table {
				border: 1px solid #aaa;
				border-collapse: collapse;
			}
			th {
				height: 100px;
				background: #0ccccc;
			}
			th div {
				-webkit-transform: rotate(270deg);
			}
			tbody tr {
				text-align: center;
				vertical-align: top;
				height: 1000px;
				background: #cccc0c;
			}
		</style>
	</head>
	<body>
		<table>
			<thead>
				<tr><th><div>head cell</div></th></tr>
			</thead>
			<tbody>
				<tr><td>body cell</td></tr>
				<tr><td>body cell</td></tr>
			</tbody>
		</table>
	</body>
</html>
```

result page 1:
![test-page1](https://user-images.githubusercontent.com/800119/41104003-c078d76c-6a6a-11e8-9111-0923d34a2dc7.png)

result page 2:
![test-page2](https://user-images.githubusercontent.com/800119/41104019-c59f2a98-6a6a-11e8-8d6c-f1b63b6c863a.png)

**Comment by rruchte** [comment] 2018-06-07 14:05
You may need to experiment with your CSS. I created the patch for a case where tables are repeating across many pages and it works as expected for us.

**Comment by craue** [comment] 2018-06-07 14:16
@rruchte, shouldn't it be in the same place? Seems like the position calculation is flawed.

**Comment by rruchte** [comment] 2018-06-07 14:21
@craue It is in the same place for my case. There is certainly room for improvement - I just hacked it up to get rotated headers working in a client project.

**Comment by sasha-x** [comment] 2019-12-24 19:17
Still actual.
