### ISSUE TITLE
PDF Table Headers on Page Breaks

### ISSUE THREAD

**Issue by carr2424** [wkhtmltopdf/wkhtmltopdf#2182] opened 2015-01-29 18:12 UTC
Table headers on page breaks are writing on top of the content row in the table.  This displays correctly in v0.12.1.

![wkhtmltopdf-table-header-issue-v0_12_2_1](https://cloud.githubusercontent.com/assets/1128193/5963395/d708132a-a7b9-11e4-9829-ee1a7acda341.png)

**Comment by amitbarkai** [comment] 2015-02-04 13:05
i'm using the latest version 0.12.2 if i'm not mistaken  
experiencing the same problem , in addition table break can look as the follow image 
![image](https://cloud.githubusercontent.com/assets/9720398/6040813/b303e58e-ac7e-11e4-8358-7eb9fd9394fd.png)

there are cases that the page brake can skip a full page .
it seems these happen when the constant exceed the a single page

**Comment by ashkulz** [comment] 2015-02-05 16:11
Duplicate of #1524 (and possibly #1770)

**Closed by ashkulz** 2015-02-05 16:11 UTC

**Comment by amitbarkai** [comment] 2015-02-09 11:51
is there any workaround or DEV build you can provide that solve this issue ?

**Comment by Oxyless** [comment] 2015-02-23 16:21
I removed my thead tag and used a big tbody with a special css on first row.
It is not beautiful but at least it works : )

**Comment by twetzel** [comment] 2016-10-07 00:03
can be solved with css: 

    table {
        thead {
            display: table-row-group;
        }
    }

.. is also a problem in chrome, there are double thead`s on following pages

**Comment by stevebauman** [comment] 2019-01-31 21:50
Thanks a ton @twetzel! Helped me resolve my issue.

**Comment by jmalStorm** [comment] 2019-05-31 07:59
But then header is not repeated in another page if table with lots of rows...
Any one knows workaround if I want to keep repeating headers but avoid page break inside header?
