### ISSUE TITLE
0.12.5 regression: TOC is not added to PDF

### ISSUE THREAD

**Issue by victorovich2004** [wkhtmltopdf/wkhtmltopdf#4128] opened 2018-10-11 14:57 UTC
in 0.12.4 version TOC generation was OK, but 0.12.5 introduced regression: neither 'tocXsl' nor 'toc' command line option not working!
Example from help do not generate TOC:
wkhtmltopdf toc http://qt-project.org/doc/qt-4.8/qstring.html qstring.pdf
the same example generate TOC on 0.12.4

**Comment by Tomsgu** [comment] 2018-10-12 14:59
Duplicate of #3953. It was fixed, but there is no stable release yet. You can use a dev build.

**Closed by Tomsgu** 2018-10-12 14:59 UTC

**Comment by ashkulz** [comment] 2020-06-07 08:30
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
