### ISSUE TITLE
Segmentation fault with 12.5 on using quotes in CSS

### ISSUE THREAD

**Issue by arjunsuresh** [wkhtmltopdf/wkhtmltopdf#3961] opened 2018-06-17 06:15 UTC
Hi, when I use 
quotes: "\201C""\201D""\2018""\2019";
in my CSS the latest release is giving segmentation fault. 12.4 works fine here.

**Comment by ashkulz** [comment] 2018-06-17 06:43
which OS/distro?

**Comment by arjunsuresh** [comment] 2018-06-17 07:10
It is Ubuntu 18.04

**Comment by ashkulz** [comment] 2018-06-17 07:11
Duplicate of #3945

**Closed** 2018-06-17 07:12 UTC
