### ISSUE TITLE
Graph gets compressed

### ISSUE THREAD

**Issue by cmainemer** [wkhtmltopdf/wkhtmltopdf#3171] opened 2016-10-17 18:19 UTC
Using wkhtmltopdf.exe version 0.12.3.2. 
[ais_4083386599242298613.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/534328/ais_4083386599242298613.zip)

The distraction index graph in the attached html5 file is all compressed.  Are there any command line settings that can be used to avoid the compression ?

**Comment by PhilterPaper** [comment] 2016-10-18 15:08
If you could provide the resulting PDF, we could see what you mean by "compression" in the graph. Do you mean that it's squeezed in one direction or both?

**Comment by cmainemer** [comment] 2016-10-26 20:15
Sorry for the delay. Here is a copy of the pdf file that is generated

[ais_4083386599242298613.html.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/554338/ais_4083386599242298613.html.pdf)

**Comment by PhilterPaper** [comment] 2016-10-26 22:39
Did you comment out the `<div id="distractionIndexChart">`, or was it always that way? wkHTMLtoPDF _seems_ to be seeing and processing _something_, but I'm wondering if it's missing the 100% width and height because of its being commented out? This chart sections are the result of a lot of Javascript processing, and wkHTMLtoPDF has a lot of reports with various problems with JS. Maybe there's just some JS (used for the chart) being processed incorrectly. Maybe it's as simple as restoring the width and height? Worth a try.

**Comment by cmainemer** [comment] 2016-10-27 13:51
The <div ...> statement was always commented out. Uncommenting it generated the chart but in the wrong location. Including the new pdf generated:

[ais_4083386599242298613MOD.html.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/556017/ais_4083386599242298613MOD.html.pdf)

**Comment by PhilterPaper** [comment] 2016-10-27 14:53
That leads me to suspect that wkHTMLtoPDF (the WebKit engine) is just not doing a good job of running all that Javascript. Each of the report sections is entirely built by Javascript on the fly, not original HTML. Maybe you can look around the issues filed on wkHTMLtoPDF and see what they say about JS problems, but at this point I don't think I can offer any further help. You will need to start investigating other HTML to PDF converters. I assume that you have no control over the original HTML report generator, and are just trying to use it? You might also look into what various browsers can do in the way of printing (if that's your final destination), and some are able to print a page directly to PDF.

**Comment by cmainemer** [comment] 2016-10-27 15:38
Thanks for all your help

**Comment by Tomsgu** [comment] 2018-07-26 05:38
Does this work on `0.12.5`?

**Comment by Tomsgu** [comment] 2018-09-26 16:56
I am closing this since there is no feedback and the issue is quite old.

**Closed by Tomsgu** 2018-09-26 16:56 UTC
Labels: NeedInfo
