### ISSUE TITLE
Deforming number "0" and other rounded letters in PDF

### ISSUE THREAD

**Issue by malekjaroslav** [wkhtmltopdf/wkhtmltopdf#2454] opened 2015-07-09 20:57 UTC
I have an issue with certain fonts that are deformed in PDF viz. image. I can't find a way how to fix it.
![screen shot 2015-07-09 at 22 54 20](https://cloud.githubusercontent.com/assets/7753942/8606692/add05ae6-268d-11e5-9d51-58f6a3121726.png)

**Comment by JayBizzle** [comment] 2015-08-14 14:20
Same as #2022

**Comment by Tomsgu** [comment] 2018-08-22 17:57
Duplicate of #2022.

**Closed by Tomsgu** 2018-08-22 17:57 UTC
Labels: NeedInfo
