### ISSUE TITLE
Sometimes disappears footers

### ISSUE THREAD

**Issue by LordConrad** [wkhtmltopdf/wkhtmltopdf#2307] opened 2015-04-16 10:50 UTC
wkhtmltopdf 0.12.2.1
used with params:
--no-stop-slow-scripts
--javascript-delay 1000
--header-html <path-to-header.html>
--footer-html <path-to-footer.html>
page <path-to-cover.html>
toc 
--toc-header-text Contents 

html footer markup:

<!DOCTYPE html>
<*html xmlns="http://www.w3.org/1999/xhtml">
<*head>
    <*link rel="stylesheet" type="text/css" href="../Content/css/pdf-report.css" />
    <*script>
    function subst() {
        var vars = {};
        var x = document.location.search.substring(1).split('&');
        for (var i in x) { var z = x[i].split('=', 2); vars[z[0]] = unescape(z[1]); }
        var y = document.getElementsByClassName('page');
        for (var j = 0; j < y.length; ++j) y[j].textContent = vars['page'];
    }
    <*/script>
</head>
<*body onload="subst()">
    <*div id="footer">
        <*div class="footer-container">
            <*div class="margin-right-30">
                <*div class="inline">Page| <*/div><*div class="inline"><*span class="page bold"><*/span><*/div>
            <*/div>
        <*/div>
    <*/div>
<*/body>
<*/html>

CSS: .footer-container {
    border-top: solid 3px rgb(66, 147, 171);
    padding-top: 25px;
    margin-top: 10px;
    text-align: left;
    font-size: 15pt;
    text-align: right;
}

So, sometimes (about 40% cases) footers disappears in generated pdf. I tried to use different params and different delays for JS, but issue not resolved

**Comment by ashkulz** [comment] 2015-04-16 12:54
Please post complete information, as what you have provided seems to be incomplete.

**Comment by ashkulz** [comment] 2015-06-23 10:40
Looks like a duplicate of #2183, which will be fixed in a few hours.

**Closed by ashkulz** 2015-06-23 10:40 UTC

**Comment by ashkulz** [comment] 2015-07-14 01:14
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Please note that the above downloads will be removed after the `0.12.3` release*.
