### ISSUE TITLE
DPI Argument not reflecting in PDF

### ISSUE THREAD

**Issue by agtruworth** [wkhtmltopdf/wkhtmltopdf#3007] opened 2016-06-16 13:30 UTC
When I pass DPI argument to generate PDF then PDF quality and size not reflecting. Always produce same output. I am using Window-7 32 bit system.
Below is cmd command 

c:>wkhtmltopdf --dpi 600 test.html test.pdf

**Comment by SkYneT54** [comment] 2016-06-30 17:38
Have you solved this issue ?

**Comment by toleabivol** [comment] 2016-11-29 16:52
Same for me (ubuntu 16.04 tested with latest 0.12.4 and 0.13.0-alpha-7b36694)

**Comment by Tomsgu** [comment] 2018-09-25 17:53
Closing as a duplicate of #2579.

**Closed by Tomsgu** 2018-09-25 17:53 UTC
Labels: NeedInfo
