### ISSUE TITLE
Header not showing in 0.12.2_2

### ISSUE THREAD

**Issue by michal-sapsa** [wkhtmltopdf/wkhtmltopdf#2377] opened 2015-05-24 08:49 UTC
wkhtmltopdf.exe --margin-bottom 50 --margin-top 50 --footer-html a.html --header-html a.html a.html a.pdf

a.html

    <html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=Windows-1250"/>
    </head>
    <body style="margin: 0; padding: 0">
    <center><img src="a.png" width=1700></center>
    </body>
    </html>

and the a.png is https://assets-cdn.github.com/images/modules/microsoft_callout/azure_bg.png

This work flawless in 0.11.0 rc2
non 0.12.2_2 version want to give me same results as 0.11.0 rc2

OS Windows 8.1 x64 Enterprise

Edit: before someone tell that I can't use a.html as header, footer, body - this is the minimal setup needed to hit this bug, and using different html make it look the same (no header). Header show up only if its not html.

**Comment by neoPix** [comment] 2015-06-04 13:39
I get the same issue with --header-html.

OS Windows 7 x64 Professional

**Comment by ashkulz** [comment] 2015-06-23 09:18
Looks like a duplicate of #2083 and/or #2183, downgrading to 0.12.1 should fix it in most cases (a fix will be committed in a few hours).

**Closed by ashkulz** 2015-06-23 09:18 UTC

**Comment by ashkulz** [comment] 2015-07-14 01:14
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Please note that the above downloads will be removed after the `0.12.3` release*.
