### ISSUE TITLE
Rowspan and page-break

### ISSUE THREAD

**Issue by MrFr1day** [wkhtmltopdf/wkhtmltopdf#3252] opened 2016-12-15 13:54 UTC
Hi,

In the attached example (html & pdf), you'll find that that wkhtmltopdf is ignoring the "page-break-inside:avoid" for rowspan cells.

Is there a workaround for this?

Thanks.

v 0.12.3.2
Windows 7 x64

[Rowspan.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/654794/Rowspan.zip)

**Comment by bree29** [comment] 2016-12-17 16:35
Hey !
I was looking for a solution to your issue, and I can't make it work.
The .NextRow class should be with div ; but div are not allowed in tables...

An alternate way I treated that kind of problem with my JPG Blend was to, after we know how height my jpg has to be (minimum and maximum) ; making div with page-break-inside:avoid class around ?

Exemple : 
```
<style> .nextpage { page-break-inside:avoid; }
<div class = .nextpage><table>
[[WHAT YOU WANT BUT AT LEAST MORE THAN PAGE / 2, and AT MAX THE ENTIRE PAGE]]
</table></div>
<style> .nextpage { page-break-inside:avoid; }
<div class = .nextpage><table>
[[HERE IT GOES AGAIN]]
</table></div>
```

Gimme some news ?

Bree

**Comment by MrFr1day** [comment] 2016-12-18 11:50
Hello bree29,

I was hoping I can avoid splitting the table because I don't know how to calculate the size of each group-of-rows (3 rows) + a table header in each page.

Counting the letters in each cell (the only solution I know) is not a fail-proof solution since some letters take more space than others.

And putting each group in their own table is not an option either.

Thanks.

**Comment by Tomsgu** [comment] 2018-08-08 11:03
Duplicate of #1524. Please try one of the workaround from this issue.

**Closed by Tomsgu** 2018-08-08 11:03 UTC
Labels: NeedInfo

**Comment by sergiujardan** [comment] 2019-05-24 13:30
Hi.
I have the same issue and could not identify how can I fix it.

This is my html code:
`<style>
 table { page-break-inside: auto }
        tr { page-break-inside: avoid; page-break-after: auto }
        thead { display: table-header-group }
        tfoot { display: table-footer-group }
</style>

<table class="w100">
	<thead>
		<tr>
			<th class="w20"></th>
			<th class="w5" style="text-align: center">Time</th>
			@for (int i = 0; i < 31; i++)
			{
				<th class="w1" style="text-align: center">@(i+1)</th>
			}
		</tr>
	</thead>
	<tbody>
		@for (int i = 0; i < 5; i++)
		{
			<tr>
			<td rowspan="4"></td>
			<td></td>
			@for (int j = 0; j < 31; j++)
			{
				<td>
					<div style="min-height: 10px"></div>
				</td>
			}
		}
	</tr>
	<tbody>

</table>
`
When you look at the PDF it doesn't break properly the table. I have a screenshot: 
https://documentcloud.adobe.com/link/track?uri=urn%3Aaaid%3Ascds%3AUS%3A62b7fc46-8df5-4a25-8595-71c1b7689bc9

It would be great if anyone can help me with my problem.

Many thanks in advance,
Serj

**Comment by sergiujardan** [comment] 2019-05-24 13:38
Hi.
I have the same issue and could not identify how can I fix it.

This is my html code:
`<style>
 table { page-break-inside: auto }
        tr { page-break-inside: avoid; page-break-after: auto }
        thead { display: table-header-group }
        tfoot { display: table-footer-group }
</style>
'

https://jsfiddle.net/nj260hzt/1/

When you look at the PDF it doesn't break properly the table. I have a screenshot: 
https://documentcloud.adobe.com/link/track?uri=urn%3Aaaid%3Ascds%3AUS%3A62b7fc46-8df5-4a25-8595-71c1b7689bc9

It would be great if anyone can help me with my problem.

Many thanks in advance,
Serj
