### ISSUE TITLE
SHA1 sum missing for buster amd64 deb package

### ISSUE THREAD

**Issue by warp10** [wkhtmltopdf/wkhtmltopdf#4650] opened 2020-03-27 21:46 UTC
The SHA1 sum for wkhtmltox_0.12.5-1.buster_amd64.deb is missing from https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/SHA1SUMS

BTW, it is missing also for MD5SUMS and SHA256SUMS
 

PS: Not sure if this issue should be opened on https://github.com/wkhtmltopdf/packaging. In case it should, sorry for that.

**Comment by ashkulz** [comment] 2020-03-28 03:47
Duplicate of wkhtmltopdf/packaging#47 -- I've not been able to find time to finish the `0.12.6` release automation, which will make the signed releases moot as they'll all come from an automated CI job from Azure Pipelines.

**Closed by ashkulz** 2020-03-28 03:47 UTC
