### ISSUE TITLE
table rows  overlapping the header in the second page

### ISSUE THREAD

**Issue by dre-logics** [wkhtmltopdf/wkhtmltopdf#2973] opened 2016-05-31 18:38 UTC
I have a second table who will not fit on the page.
so the  table rows  overlapping the header in the second page.

I use this code to aviod it:

table { page-break-inside:auto }
        tr    { page-break-inside:avoid; page-break-after:auto }
        td    { page-break-inside:avoid; page-break-after:auto }
        thead { display:table-header-group }
        tfoot { display:table-footer-group }

this solution does not work!
Who can help me
[offerte805.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/291878/offerte805.pdf)

**Comment by ashkulz** [comment] 2016-06-01 05:30
Duplicate of #1524.

**Closed by ashkulz** 2016-06-01 05:30 UTC

**Comment by dre-logics** [comment] 2016-06-01 17:43
Oke, thanks 
I have new challenge. On my Local PC with  Windows 10 and Laravel 5.2 If  I create a PDF with wkhtmltopdf then a get nice PDF with page-size default A4.
On the webserver ,  I create a PDF with wkhtmltopdf then a PDF strange layout    , see Appendix
[offerte857.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/293998/offerte857.pdf)

Its same source as on the webserver as on th local PC. 

  $pdf = PDF::loadView('emails.offertePDF', $data)

What am I doing wrong or forgot
