### ISSUE TITLE
wkhtmltopdf doesn't support odoo on Ubuntu 18.04

### ISSUE THREAD

**Issue by thite** [wkhtmltopdf/wkhtmltopdf#3921] opened 2018-05-17 06:45 UTC
Hi @ashkulz ,

This is a well-known issue regarding the Trinity: WKHTMLTOPDF-ODOO-UBUNTU 18.
When I try to print pdf in odoo, it generates a blank pdf (the size is 306 bytes).
I need to run Odoo 11 on Ubuntu 18 LTS.

**Comment by ashkulz** [comment] 2018-05-17 07:18
Duplicate of #3898 and #3914

**Closed** 2018-05-17 07:18 UTC
