### ISSUE TITLE
[0.12.5 regression] TOC no longer present in pdf output

### ISSUE THREAD

**Issue by Jc-L** [wkhtmltopdf/wkhtmltopdf#4122] opened 2018-10-09 14:07 UTC
On Windows 10 64bits, when moving from
`wkhtmltox-0.12.4_msvc2015-win64.exe`
to
`wkhtmltox-0.12.5-1.msvc2015-win64.exe`

the Table Of Content no longer appears in the generated pdf file. Issue also appears on CentOS,

Step to reproduce (with both versions):
```
$ cat > source.html  <<EOF
<html>
<head></head>
<body>
<h1>H1 Title</h1>
<h2>H2 Title</h2>
<h3>H3 Title</h3>
</body>
</html>
EOF

wkhtmltopdf toc source.html out.pdf
```

**Comment by Tomsgu** [comment] 2018-10-09 14:16
This is a duplicate of #3953. It was fixed already, but there is no 0.12.6 version released yet :worried:.

**Closed by Tomsgu** 2018-10-09 14:16 UTC
Labels: Duplicate

**Comment by ashkulz** [comment] 2020-06-07 08:29
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.

**Comment by Jc-L** [comment] 2020-06-07 16:13
0.12.6rc1 fixes the issue (tested windows 64bits builds 0.12.4, 0.12.5, 0.12.6rc1). TOC is now present.
