### ISSUE TITLE
Temp PDF files are not removed after execution

### ISSUE THREAD

**Issue by dangusev** [wkhtmltopdf/wkhtmltopdf#3498] opened 2017-05-30 16:34 UTC
Possibly the same as https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1981

Try to use wkhtmltoimage (ver 0.12.4 with patched qt) on Ubuntu 16.04.2 in the following way:
```
echo 1 | wkhtmltoimage --height 320 --format png --width 540 --javascript-delay 300 - -
```
Everything works without errors, but after each execution I see new files "wktemp-****.html" in /tmp/ directory. Tried to use 0.12.2.4 with the same result.

**Comment by omederos** [comment] 2017-11-09 17:40
I'm having the very same issue :(

**Comment by ritika-innani** [comment] 2019-01-11 07:12
Do we have any updates on this issue?
I am facing the same issue and want to disable the generation of temp files

**Comment by AlexKulbako** [comment] 2020-01-23 17:23
Facing the same problem. When it will be fixed?

**Comment by ashkulz** [comment] 2020-01-24 05:37
Is this only specific to `wkhtmltoimage`?

**Comment by ashkulz** [comment] 2020-01-24 06:01
I think this patch should fix the issue, will try it out this weekend:
```diff
$ git diff
diff --git a/src/lib/imageconverter.cc b/src/lib/imageconverter.cc
index 09e3b23..6cfe340 100644
--- a/src/lib/imageconverter.cc
+++ b/src/lib/imageconverter.cc
@@ -225,6 +225,7 @@ void ImageConverterPrivate::pagesLoaded(bool ok) {
        loadProgress(100);
 
        currentPhase = 2;
+       clearResources()
        emit out.phaseChanged();
        conversionDone = true;
        emit out.finished(true);
```

**Comment by AlexKulbako** [comment] 2020-01-24 09:07
> Is this only specific to `wkhtmltoimage`?

wkhtmltopdf as well

**Comment by ashkulz** [comment] 2020-01-24 09:09
@AlexKulbako: can you add some reproduction instructions for wkhtmltopdf 0.12.5 -- like done in the original post?

**Comment by AlexKulbako** [comment] 2020-01-24 09:57
> @AlexKulbako: can you add some reproduction instructions for wkhtmltopdf 0.12.5 -- like done in the original post?

It's really hard to reproduce. We are using HL7 MDM for our customer and sending pdfs via this protocol. We are generating more 1k pdf files per day. Once a week I get a message from the customer that pdf files are not longer being sending. After clearing Windows/Temp it's working :(

**Comment by ashkulz** [comment] 2020-01-24 11:54
Please create a separate ticket and reference this one if you're able to reproduce :+1:

**Comment by recvfrom** [comment] 2020-12-30 05:14
Any chance this fix can be included with the next release? I verified that the patch above fixes the issue for my use case (using wkhtmltoimage via imgkit)... If there's anything I can help with to get this fix in, just let me know!

**Comment by ashkulz** [comment] 2020-12-30 06:01
@recvfrom having a reproducible testcase would really help in confirming that the above fix works.

**Comment by recvfrom** [comment] 2020-12-30 21:55
Using the test case from the first comment above reproduces the issue for me, for wkhtmltoimage.

Without the fix:
```
~$ echo 1 | strace -f wkhtmltoimage --height 320 --format png --width 540 --javascript-delay 300 - - 2>&1 | grep --text wktemp
openat(AT_FDCWD, "/tmp/wktemp-05ed9850-3f36-4f41-9c98-a114b7a87fe8.html", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 8
stat("/tmp/wktemp-05ed9850-3f36-4f41-9c98-a114b7a87fe8.html", {st_mode=S_IFREG|0664, st_size=2, ...}) = 0
[pid 91537] lstat("/tmp/wktemp-05ed9850-3f36-4f41-9c98-a114b7a87fe8.html", {st_mode=S_IFREG|0664, st_size=2, ...}) = 0
[pid 91537] stat("/tmp/wktemp-05ed9850-3f36-4f41-9c98-a114b7a87fe8.html", {st_mode=S_IFREG|0664, st_size=2, ...}) = 0
[pid 91537] openat(AT_FDCWD, "/tmp/wktemp-05ed9850-3f36-4f41-9c98-a114b7a87fe8.html", O_RDONLY|O_CLOEXEC) = 10
```
With the fix from the patch posted above (notice the call to unlink):
```
~/workspace/wkhtmltopdf/bin$ echo 1 | LD_LIBRARY_PATH=. strace -f ./wkhtmltoimage --height 320 --format png --width 540 --javascript-delay 300 - - 2>&1 | grep --text wktemp
[pid 91525] openat(AT_FDCWD, "/tmp/wktemp-239716fc-8d15-4402-b3ad-ccde27330e7b.html", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 7
[pid 91525] access("/tmp/wktemp-239716fc-8d15-4402-b3ad-ccde27330e7b.html", F_OK) = 0
[pid 91525] lstat("/tmp/wktemp-239716fc-8d15-4402-b3ad-ccde27330e7b.html", {st_mode=S_IFREG|0664, st_size=2, ...}) = 0
[pid 91525] lstat("/tmp/wktemp-239716fc-8d15-4402-b3ad-ccde27330e7b.html", {st_mode=S_IFREG|0664, st_size=2, ...}) = 0
[pid 91525] statx(AT_FDCWD, "/tmp/wktemp-239716fc-8d15-4402-b3ad-ccde27330e7b.html", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=2, ...}) = 0
[pid 91525] openat(AT_FDCWD, "/tmp/wktemp-239716fc-8d15-4402-b3ad-ccde27330e7b.html", O_RDONLY|O_CLOEXEC) = 9
[pid 91525] unlink("/tmp/wktemp-239716fc-8d15-4402-b3ad-ccde27330e7b.html") = 0
```

I tried a couple different basic invocations of wkhtmltopdf and couldn't reproduce the issue with that...

**Closed** 2020-12-31 06:17 UTC
Labels: Verified

**Comment by FubinSama** [comment] 2022-01-29 06:57
@ashkulz Hello, guys. I found also generate the *.html temp file in my server.
My wkhtmltoimage version is 0.12.6
My server is CentOS Linux release 7.6.1810 (Core)
BTW. It doesn't happend in my mac.

**Comment by ashkulz** [comment] 2022-01-29 06:58
@FubinSama this hasn't been released yet.

**Comment by FubinSama** [comment] 2022-01-29 07:01
> @FubinSama this hasn't been released yet.

OK. Thanks. But when can I get the new version which fix it?
