### ISSUE TITLE
Overlapping text in table

### ISSUE THREAD

**Issue by simplias** [wkhtmltopdf/wkhtmltopdf#2775] opened 2016-02-02 21:00 UTC
Sometimes the text is overlapping pictures. We are currently on a very old version 0.9.9 and want to update to 0.12.1 since 2 years, but the following issues is hindering us:

Checkout the following example: wkhtmltopdf.exe atest.html --header-html header.html --footer-html footer.html  test4.pdf.

It is working on the old version 0.9.9. 

Unfortunately it is the only way to reproduce the error.In the zip file you will find the required files to reproduce the error. It is on the very last page of the document test4.pdf 
![bug](https://cloud.githubusercontent.com/assets/1998154/12764128/4ba59fe8-c9f8-11e5-8e76-2a77821e974c.png)
We are willing to pay you the effort (e.g. 100$).

[files.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/114669/files.zip)
[test4.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/114670/test4.pdf)

:

**Comment by Tomsgu** [comment] 2018-06-19 13:56
Possible duplicate of #1524

**Closed** 2018-06-29 13:49 UTC
Labels: Duplicate
