### ISSUE TITLE
PDF text getting clipped and split into two page on page-break

### ISSUE THREAD

**Issue by manishshanker** [wkhtmltopdf/wkhtmltopdf#3350] opened 2017-02-22 15:36 UTC
Hi, This issue has been reported all over the web it looks like but I haven't come across any full proof solution yet. 

Please advise what is the best way to handle this as it works most of the time but when content changes it sometimes clip the text in a weird way splitting them onto two pages, even though we specify property like page-break:avoid etc.

**Comment by PhilterPaper** [comment] 2017-02-22 16:04
This is an open problem with many threads here discussing it. It would be better to comment in an existing thread than to start yet another one.

**Comment by Jmuccigr** [comment] 2017-03-05 18:53
And it would therefore be good to close this one with a "same as" indication, no? :-)

**Comment by amiraljack** [comment] 2017-05-09 12:29
Hi, I had the same issue, I fixed it by replacing `display: inline-block` by `display: block` on my div element. I don't really know how it worked to be honest, element's height is maybe miscalculated with inline-block.

**Comment by dcworldwide** [comment] 2017-06-30 01:23
Relates to https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3485

**Comment by Tomsgu** [comment] 2018-06-20 07:18
Duplicate of #1524, #2029.
Please read the these issues. You can find some workarounds that can improve a situation, since there is no real fix yet.

**Closed** 2018-06-21 07:05 UTC
Labels: Duplicate
