### ISSUE TITLE
table header overwrites first table row on subsequent pages

### ISSUE THREAD

**Issue by DavidLRowe** [wkhtmltopdf/wkhtmltopdf#2530] opened 2015-08-18 21:51 UTC
When a table in Github Flavoured Markdown spans a page, the repeated header overwrites the first line of the table on subsequent pages. Editing the .html file to remove the <thead> and <tbody> tags makes the problem disappear. (testtable.md, testtable.html, testtable.pdf available for testing, but I don't see any way to attach them.)

![wkhtmltopdf table header overwrites row](https://cloud.githubusercontent.com/assets/8562172/9343481/1ab6c486-45b7-11e5-973a-132fdb9d28d9.jpg)

**Comment by DavidLRowe** [comment] 2015-08-18 22:01
Sorry! The HTML tags dissappeared. That second sentence should read "...to remove the [thead] and [tbody] tags..." (with [ and ] substituted for angle brackets).

**Comment by lpagani91** [comment] 2015-08-18 22:12
just submitted the same issue a few minutes after you! Tried your fix. It works except that the headers become right justified instead of being centered inside each column but it is better than the original overwriting!

**Comment by PhilterPaper** [comment] 2015-08-20 14:24
Enclose code in backticks and you should be able to write HTML in-line:  `<thead>`. 

The only thing I've found to prevent the thead being overwritten by the next row is to use CSS to forbid breaking a **row** across a page.

**Comment by DavidLRowe** [comment] 2015-08-20 14:53
@PhilterPaper Thanks for the tips. Would you be able to post an example of your CSS workaround here?

**Comment by PhilterPaper** [comment] 2015-08-21 20:01
`tr { page-break-inside: avoid; }`

**Comment by Tomsgu** [comment] 2018-06-20 07:38
Duplicate of #1524.

**Closed** 2018-06-22 06:59 UTC
Labels: Duplicate

**Comment by NimeshJadav** [comment] 2019-03-06 12:43
> `tr { page-break-inside: avoid; }`

Sorry But It's Not Working

**Comment by arielrs35** [comment] 2020-09-01 20:15
@PhilterPaper it worked for me tr { page-break-inside: avoid; } 
Thanks
