### ISSUE TITLE
Not rendering d3 charts.

### ISSUE THREAD

**Issue by mkok1019** [wkhtmltopdf/wkhtmltopdf#3637] opened 2017-09-07 09:54 UTC
I am going to render d3 charts into PDF but it doesn't work.

Actually, I've tested that javascript is running for PDF export, but it doesn't support async callback.

I've described here how it doesn't work on my side.

```
d3.queue()
    .defer(d3.json, "https://s3.amazonaws.com/xxx.json")
    .defer(d3.json, dataUrl)
    .defer(d3.tsv, "https://s3.amazonaws.com/xxx.tsv")
    .await(ready);
```
Before this code block, I've confirmed that JS is running correctly. After this code block, I put some JS testing code, but it didn't work and its not coming into PDF.

Can anyone help for this, please?

**Comment by Tomsgu** [comment] 2018-08-09 08:08
Duplicate of #1964. There you can find some workarounds for d3 charts (https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1964#issuecomment-104936269)

**Closed by Tomsgu** 2018-08-09 08:08 UTC
Labels: NeedInfo
