### ISSUE TITLE
Fonts always appear bolded when printing HTML page.

### ISSUE THREAD

**Issue by joeysr20det** [wkhtmltopdf/wkhtmltopdf#2988] opened 2016-06-09 17:15 UTC
We use wkhtmltopdf to print HTML pages to PDF. These are very simple pages mind... a hand full of <input> boxes, a few <labels>, a couple images, etc. We've noticed that there doesn't seem to be any control over the way our fonts are rendered. For example, one of our forms that we print uses the font Arial throughout the entire page. I've set the CSS font-family to just Arial (I've read there are issues if you use a list of font names) and I've set the font-weight from 100 to 900 but I cannot get a standard looking font weight. I always end up with a bold to very bolded font.

From what I've read, it sounds as though you are at the mercy of how QT decides to render the text, is this true?

I've also read that QT does individual character placement instead of just printing full strings of text, does that apply here as well? (It seems to from the output).

We really like wkhtmltopdf, it's nice, simple and works great for us however these font issues are really holding us back. Is there any aim to try and fix some of this in the future?

**Comment by NicoBarbaros** [comment] 2016-06-17 10:28
There is a issue with the font that has the same family. So whether convert your font to base_64 or change the family name of each font in a font editor. 

[http://apleroy.com/posts/custom-pdf-fonts-with-wicked_pdf-and-heroku](url)

This should be helpful

**Comment by concepta-thiago** [comment] 2016-07-19 19:29
i have the same problem, tried this link but its is broken, i also tried base64 and woks fine on html but the pdf does not render it ,

Any help?

**Comment by NicoBarbaros** [comment] 2016-07-20 10:46
Try changing the font family! That worked for me.

**Comment by zampa89** [comment] 2016-12-14 16:25
I have the same issue... I tried this simple code in an empty HTML page:

`<div style="width:250px"><input type="text" style="font-family: Microsoft Sans Serif; width:150px;" value="...content...">...text...</div>`

The results were these
![image](https://cloud.githubusercontent.com/assets/1488992/21190280/8f468812-c221-11e6-9a9d-d4524ac370c5.png)

The text looks the same in QTWeb browser, but the font in the PDF is bolder than in every other browser, especially the text inside of the input box

**Comment by Jmuccigr** [comment] 2017-02-23 19:34
I'm seeing this with Gill Sans where the light version is not being used by wkhtmltopdf and in one case the words are getting extended across an entire line. (Can provide URL, if that's helpful.)

**Comment by PhilterPaper** [comment] 2017-02-23 23:30
If @font-face is used to specify fonts, there are known problems. Sometimes the fix is as simple as specifying the font weight in each entry. Be sure to read the various bug reports and suggested solutions.

**Comment by Jmuccigr** [comment] 2017-02-24 00:07
There are a lot of them!

A bunch should be closed, I suspect, but the ones I read didn't seem to have a definite solution. 

I do specify "lighter" as the weight but it's apparently ignored.

**Comment by PhilterPaper** [comment] 2017-02-24 13:43
That's the font weight in the @font-face entry, not other CSS. I think you have to give a definite weight, not relative amounts (lighter, heavier, etc.).

**Comment by Jmuccigr** [comment] 2017-02-24 15:21
I declare the font weight as `lighter` in the individual css entries, e.g., h1. I don't use **@font-face** at all.

**Comment by Jmuccigr** [comment] 2017-05-15 16:57
Any more thoughts on this? If I change my css so that it has (for h1): `font-weight: 100;` where `100` replaces the `lighter` I normally use, I still get heavier fonts with greater spacing. The screen cap shows a PDF generated by using the print function in OS X on the left, and the PDF generated by wkhtmltopdf on the right. The one on the left is what the html looks like.

![wkhtmltopdf](https://cloud.githubusercontent.com/assets/615115/26068953/5fb5abaa-396d-11e7-8ce9-a5c8aa5e017c.png)
(I also had to bump up the dpi to 300 to get the print size right, but that's a different issue, I assume. The problem described here remains when I don't specify dpi.)

**Comment by theo4u** [comment] 2017-10-29 06:13
check this #1542

**Comment by Tomsgu** [comment] 2018-08-23 11:27
Thanks for the workaround @royarun6. I am closing this issue as it is duplicate of #1542.

**Closed by Tomsgu** 2018-08-23 11:27 UTC
Labels: NeedInfo

**Comment by imsinu9** [comment] 2020-12-03 10:20
In my case, it was expecting `NimbusSanL-Regu` font which I installed it via 

`apt install gsfonts`
