### ISSUE TITLE
Nodejs10.x support

### ISSUE THREAD

**Issue by nyel-dev** [wkhtmltopdf/wkhtmltopdf#4589] opened 2020-01-17 02:54 UTC
AWS is now forcing users to use nodejs10.x. Apparently, wkhtmltopdf is not working on nodejs10.x. Any ways to fix this?

Previously working state:
nodejs8.10
AWS Lambda function

Ways to replicate:
Create lambda function that runs on nodejs10.x

**Comment by ashkulz** [comment] 2020-01-17 10:20
Duplicate of #4523

**Closed by ashkulz** 2020-01-17 10:20 UTC
