### ISSUE TITLE
external links all point to pdf.js/web

### ISSUE THREAD

**Issue by kenirwin** [wkhtmltopdf/wkhtmltopdf#2581] opened 2015-09-14 21:24 UTC
Hi folks,

I've just started using wkhtmltopdf. It seems to be working well, but I find that all of the links from a source html page are converted to links that go to *resource://pdf.js/web* instead of the origin html src value. Do you know what causes this or how I can fix it?

Thanks
ken

**Comment by kenirwin** [comment] 2015-09-14 21:24
PS - I'm using PHP:
exec('/usr/local/bin/wkhtmltopdf --enable-external-links --page-size Letter '.$url. ' '.$file);

**Comment by ashkulz** [comment] 2015-09-15 04:59
Duplicate of #1843, use the `0.12.3-dev` build which include those changes.

**Closed by ashkulz** 2015-09-15 04:59 UTC
