### ISSUE TITLE
Non-ascii characters in filepath and header

### ISSUE THREAD

**Issue by kristinlyt** [wkhtmltopdf/wkhtmltopdf#2445] opened 2015-07-06 11:10 UTC
I am trying to convert a HTML page with Thai characters using C# language. HTML content has no issues, but my header shows some characters as '?' instead. And the export fails whenever the filename contains vietnamese characters. Is there any way which I can bypass and allow the filename setting?

*Argument contains '--encoding utf-8' 

Any advice will be greatly appreciated!

**Comment by ashkulz** [comment] 2015-07-06 11:16
I assume this is on Windows, so looks like a duplicate of #2395.

**Closed by ashkulz** 2015-07-06 11:16 UTC
