### ISSUE TITLE
Problems with Ionic Beaver

### ISSUE THREAD

**Issue by Jonnathangte68** [wkhtmltopdf/wkhtmltopdf#3922] opened 2018-05-18 21:33 UTC
admin@srvr58:~/jonnathanaha$ sudo dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb 
Selecting previously unselected package wkhtmltox.
(Reading database ... 79244 files and directories currently installed.)
Preparing to unpack wkhtmltox-0.12.1_linux-trusty-amd64.deb ...
Unpacking wkhtmltox (0.12.1) ...
dpkg: dependency problems prevent configuration of wkhtmltox:
 wkhtmltox depends on fontconfig; however:
  Package fontconfig is not installed.
 wkhtmltox depends on libfontconfig1; however:
  Package libfontconfig1 is not installed.
 wkhtmltox depends on libpng12-0; however:
  Package libpng12-0 is not installed.
 wkhtmltox depends on libjpeg-turbo8; however:
  Package libjpeg-turbo8 is not installed.
 wkhtmltox depends on libxrender1; however:
  Package libxrender1 is not installed.

dpkg: error processing package wkhtmltox (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.8.3-2) ...
Errors were encountered while processing:
 wkhtmltox

**Comment by ashkulz** [comment] 2018-05-19 02:37
Duplicate of #3898

**Closed by ashkulz** 2018-05-19 02:37 UTC
