### ISSUE TITLE
-s issues for page size and page width

### ISSUE THREAD

**Issue by Pagise** [wkhtmltopdf/wkhtmltopdf#2741] opened 2016-01-04 17:03 UTC
I'm trying to make sure that the page prints to a letter format. I tried this a few times and got output, but now I get: "Invalid argument(s) parsed to -s" and I have no idea why. I used "-s --page-size letter".

Second issue: When I print a responsive page, I ALWAYS get the mobile size of the page printed to the pdf instead of the regular size. I used "-s --page-width 260" to print a width of 1000px wide (260mm) (which would be enough I would think), but it doesn't work. Even if I get to a width of 4000mm.. It doesn't matter, it always gives the mobile view. Any idea why? Am I missing something here?
Funny thing is.. I am now getting the  "Invalid argument(s) parsed to -s" issue also when I ONLY use the "-s --page-width" part...

**Comment by Pagise** [comment] 2018-06-15 17:01
Ok, this was an issue in 2016. Two and a half years later people are asking about this?.. alloylab adds the "needinfo" label to it (I don't get a notification about this) and then simply closes it 3 hours later (I did get a notification about THAT though!). Why ask for "needinfo" after 2.5 years? Why not within 2.5 hours or something? Well.. at least it's a way to get rid of open issues I guess.... I hope it got fixed though!

**Comment by alloylab** [comment] 2018-06-15 17:04
@Pagise That was a mistake what version are you running?

**Comment by ashkulz** [comment] 2018-06-15 17:06
@Pagise: we're trying to do a spring cleaning of all open issues. This is a volunteer effort, so @alloylab is [gardening all issues](http://words.steveklabnik.com/how-to-be-an-open-source-gardener) but closed it prematurely.

**Comment by Tomsgu** [comment] 2018-06-15 17:12
Well @Pagise when you have more than 1000 issues and most of them are more than 2 years old, you can't just go one by one and ask everyone the same question. Especially if the issue misses important facts like In what version is it happening, what os are you using, can you provide a minimal html case when it happens. There is also stackoverflow for the questions.

Just reminding that this is open source project. Nobody is obligate to do something.

**Comment by Pagise** [comment] 2018-06-15 17:36
No problem.. I'm glad it actually finally got some "feedback"! lol.
Version: Most likely v0.12.2.1 since it was jan 6 1016 and I most likely was trying the latest version.
OS: Linux (centos 6 to be more precise)


Unfortunately I haven't looked at it ever since since it was so buggy and didn't do what I wanted to do. I see that there have been a lot of fixes ever since, so I might want to give it a try again (if the documentation has been updated and if it 'easily' prints a regular portrait version of a web site)...
If it does the above, then you might as well close this case!

**Comment by Tomsgu** [comment] 2018-08-25 10:27
The first issue is due to wrong set of arguments. You should use either `-s` or `--page-size`. They should be equivalent. 

The second issue is hard to reproduce because there is no html example and a lot has changed in newer versions.

Please re-open the issue if you will experience this issue in a newest version (at the moment 0.12.5) and have more information to be able to reproduce the issue

**Closed by Tomsgu** 2018-08-25 10:27 UTC
Labels: NeedInfo
