### ISSUE TITLE
umlaut in command line footer text

### ISSUE THREAD

**Issue by Mathlight** [wkhtmltopdf/wkhtmltopdf#2489] opened 2015-07-28 08:05 UTC
I'm trying to create an footer text with an umlaut? [ ü ] but it's not working.

The (php) command that generates the PDF:

```
$footerText = $exportName . ' ' . $cron->Name . ' ' . str_replace('|', ':', date("Y-m-d H|i"));
exec("wkhtmltopdf --footer-left '" . $footerText . "' --footer-right '[page] / [topage]' --orientation Landscape " . $fileName . ".html " . $fileName . ".pdf");
```

Where `$footerText` = `AutoExport Partijen düits 2015-07-28 09:49`

But the output (in the PDF) is without the [ ü ]: `AutoExport Partijen dits 2015-07-28 09:49`

The PDF is created on an Ubuntu 14.04 server with these locales:

```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

What can I do to make the umlaut [ ü ] work on the footer?

**Comment by PhilterPaper** [comment] 2015-08-16 23:52
I just tried using & uuml;, and that didn't work, so it's possible that the character set in headers and footers is limited to ASCII? I presume that you have confirmed that the encoding you used to create the footer matches what the page is (UTF-8?). If you accidentally created a Latin-1/Windows-1252 u-umlaut for the command line, that would likely fail.

**Comment by Mathlight** [comment] 2015-08-17 06:10
@PhilterPaper Thank you for your responce. It do seems like it is indeed limit to ASCII characters, which would be a shame...

In PHP, which calls the script, I set the output like this (although it doesn't matter):
`header('Content-Type: text/html; charset=utf-8');`

In the export HTML files, I've set the meta charset to utf-8 also:

`<meta http-equiv="content-type" content="text/html; charset=utf-8">`

But still no luck.

So right now, I've build in an filter which will pick up the wrong characters and call the problem to the end-user. But it would be much better if this could be fixed (although I have no clue how...)

**Comment by PhilterPaper** [comment] 2015-08-17 13:23
I don't think that headers and footers go "through" the HTML page, so setting the encoding there may not have any effect on your header or footer text. It's possible that a UTF-8 page could somehow "drag" headers and footers into UTF-8, but only the author can tell us for sure.

**Comment by jmau2002** [comment] 2016-03-29 09:59
Working for me with  0.12.3.2 on Windows 7 PC. See output.pdf. 

[output.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/193222/output.pdf)

**Comment by Tomsgu** [comment] 2018-08-22 18:09
Closing as it seems to be resolved.

**Closed by Tomsgu** 2018-08-22 18:09 UTC
Labels: NeedInfo
