### ISSUE TITLE
PNG images render unwanted transparency

### ISSUE THREAD

**Issue by pbarnum** [wkhtmltopdf/wkhtmltopdf#2221] opened 2015-02-25 20:29 UTC
wkhtmltopdf x64 Debian 6.0 

This only happens with certain page layouts, it doesn't happen all the time.

When ever I compile a PDF with PNG images, some of the images come out with some transparency. When I add "opacity: 1.0;" and "filter: alpha(opacity=100);" to my CSS, it still renders with transparency.

Keep in mind that these are not the same image but the effect is the same.
Original:
![Original](http://i.imgur.com/TkgrMjK.png)

PDF:
![PDF](http://i.imgur.com/Cek26At.png)

I was able to solve this with one image by moving it to the top of the page. I can't rely on this method for all images because it would destroy the flow of content.

**Comment by rsteinwand** [comment] 2015-02-26 13:26
Does the transparency look proper if the images are viewed outside the page?

**Comment by pbarnum** [comment] 2015-02-26 22:32
Yes it does. The PNGs are created using the canvas JavaScript method toDataURL() and then saved using PHP.

**Comment by massltov** [comment] 2015-03-24 10:38
Maybe related:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2135

We had a similar issue for JPGs and fixed it by giving the image a z-index and setting position: relative;

**Comment by constantm** [comment] 2017-05-12 13:12
This is still an issue. @massltov's solution fixed it for me.

**Comment by Tomsgu** [comment] 2018-08-07 10:15
Duplicate of #2135.

**Closed by Tomsgu** 2018-08-07 10:15 UTC
Labels: NeedInfo

**Comment by nysso** [comment] 2019-01-14 20:03
I faced this issue on enlarged images above their original ratio
so I had to remove that enlarging method.

**Comment by jisazaTappsi** [comment] 2019-02-07 23:52
It was a border surrounding the png... had to remove it

**Comment by henryavila** [comment] 2019-12-19 20:15
I had the same issue, and the only thing that resolved for me was this trick:

```
<div class="logo">
     <!-- Hack to WkHtmlToPdf render correctly the image (without adding transparency) -->
     <span style="color: #FFFFFF">.</span>

     <img src="{{ url('/img/logo.png')  }}" style="width:292px; height:150px;">
</div>
```

If I write some content just before the img tag, then th img is rendered correctly. 
ps: I set the dot as white color so it will not be visible

**Comment by cemilatalay** [comment] 2021-06-17 09:20
This problem solved. İnto div in style write:

` z-index: 1000;position: relative;`

My problem is to solve this code directory.
