### ISSUE TITLE
Multi Columns CSS for rendering PDF

### ISSUE THREAD

**Issue by dj1encore** [wkhtmltopdf/wkhtmltopdf#3748] opened 2017-12-06 17:03 UTC
This issue is listed in a number of Posts, However, no solution is provided.

Using CSS,

  .newsection { -webkit-column-count: 2; /* Chrome, Safari, Opera */
    -moz-column-count: 2; /* Firefox */
    column-count: 2;}

does not render PDF with Newspaper style columns.

Desired output shown below;

![capture](https://user-images.githubusercontent.com/34314341/33674379-4f47ef24-da7d-11e7-8c56-5a79310715c2.PNG)

**Comment by Tomsgu** [comment] 2018-07-16 05:48
Duplicate of #3172. You're not helping by opening duplicated issues.

**Closed by Tomsgu** 2018-07-16 05:48 UTC
Labels: NeedInfo

**Comment by richmahn** [comment] 2018-11-06 18:10
@Tomsgu It is helpful when nothing is being done about this much needed feature

**Comment by yannoliv** [comment] 2021-05-28 12:41
Any news?

**Comment by l2m2** [comment] 2022-07-22 11:42
Any news again?

**Comment by l2m2** [comment] 2022-09-07 07:43
Finally I implemented it with javascript. A bit complicated but works.

**Comment by jeannyjohanis** [comment] 2022-09-08 02:29
Hi @l2m2, interested to know how you implemented this with javascript

**Comment by richmahn** [comment] 2022-09-12 13:32
@l2m2 yeah, interested too.
