### ISSUE TITLE
wkhtmltoimage doesn't obey page breaks or have --print-media-type options

### ISSUE THREAD

**Issue by brandonros** [wkhtmltopdf/wkhtmltopdf#2740] opened 2016-01-04 16:41 UTC
I'm not sure if these are intentional or not.

Please let me know what other information I can provide. I feel the title explains quite a bit.

**Comment by stania1** [comment] 2016-01-14 08:12
Take a look at https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2371. We had a similar issue and used the workaround described there (basically removing float on the element that needs page-break-before / page-break-after).

**Comment by Tomsgu** [comment] 2018-08-25 09:30
Closing as this is a duplicate of #2371.

**Closed by Tomsgu** 2018-08-25 09:30 UTC
Labels: NeedInfo
