### ISSUE TITLE
Space under a image in a <table>

### ISSUE THREAD

**Issue by BenBezac** [wkhtmltopdf/wkhtmltopdf#2781] opened 2016-02-04 13:51 UTC
Hi,

First of all, thx for your work.

I have an issue while generating my pdf with some images.

I'm on the version 0.12.3.1 in windows and i also tried on my debian server with the same result.

My command with the options : 

`C:\"Program Files (x86)"\wkhtmltopdf\bin\wkhtmltopdf.exe --margin-bottom "15" --orientation "Portrait" --debug-javascript --encoding "UTF-8" --images --enable-internal-links --enable-javascript --javascript-delay "1000" --enable-plugins --no-stop-slow-scripts --footer-html "footer.html"  toc --xsl-style-sheet "tocRapportPDF.xsl" "body.html" "rapport.pdf"`

My HTML : 

```html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title></title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />

        <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="css/printReport.css" rel="stylesheet" type="text/css"/>

    </head>
    <body>
        <div class="report">
            <form>
                <div class="row form-horizontal form" id="printableArea">
                    <div class="block page-breaker">
                        <div class="row" id="block1">
                            <div class="do-not-break">
                                <h4 style="font-size : 1.5em" class="form-section">  
                                    <span>1.</span>
                                    <b>Posts : </b>
                                </h4>
                                <div class="row">
                                    <div style="margin-left:5em ; margin-right:5em" class="do-not-break-agent">
                                        <h5 style="font-size : 1.25em" class="form-section"> 
                                            <span>1.1</span>&nbsp;&nbsp;
                                            <b>example of title h5</b>
                                        </h5> 
                                        <span class="rapport-agent-full-url">Just a sub text</span>   

                                        <table style="table-layout: fixed" class="table table-bordered table-condensed table-striped">
                                            <tbody>


                                                <tr>

                                                    <td class="limited-cell-81">30/04/2015</td>
                                                    <td>
                                                        <div><strong>Title 1</strong></div><br>
                                                        <div>
                                                            <img class="img-sized" src="img.jpg"/>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="limited-cell-81">01/05/2015</td>
                                                    <td>
                                                        <div><strong>Title 2</strong></div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="limited-cell-81">01/05/2015</td>
                                                    <td>
                                                        <div><strong>Title 3</strong></div>                                                        
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="limited-cell-81">01/05/2015</td>
                                                    <td>
                                                        <div><strong>Title 4</strong></div><br>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="limited-cell-81">01/05/2015</td>
                                                    <td>
                                                        <div><strong>Title 5</strong></div><br>
                                                        <div>
                                                            <img class="img-sized" src="img.jpg"/><br>
                                                            <img class="img-sized" src="img.jpg"/><br>
                                                            <img class="img-sized" src="img.jpg"/><br>
                                                            <img class="img-sized" src="img.jpg"/><br>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="limited-cell-81">01/05/2015</td>
                                                    <td>
                                                        <div><strong>Title 6</strong></div><br>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="limited-cell-81">01/05/2015</td>
                                                    <td>
                                                        <div><strong>Title 7</strong></div>
                                                        <div>
                                                            <img class="img-sized" src="img.jpg"/>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="limited-cell-81">01/05/2015</td>
                                                    <td>
                                                        <div><strong>Title 8</strong></div><br>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="limited-cell-81">01/05/2015</td>
                                                    <td>
                                                        <div><strong>Title 9</strong></div><br>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="limited-cell-81">01/05/2015</td>
                                                    <td>
                                                        <div><strong>Title 10</strong></div><br>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="limited-cell-81">01/05/2015</td>
                                                    <td>
                                                        <div><strong>Title 11</strong></div>
                                                        <div>
                                                            <img class="img-sized" src="img.jpg"/>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </form>
        </div>
    </body>

</html>
```

My custom css ( plus bootstrap) : 

```css
body {    
    background: #ffffff !important;
}

* { 
    -webkit-print-color-adjust: exact; 
}

a[href]:after {
    content: " (" attr(href) ")";
}

abbr[title]:after {
    content: " (" attr(title) ")";
}

.ir a:after,
a[href^="javascript:"]:after,
a[href^="#"]:after {
    content: "";
}

thead {
    display: table-header-group;
}

tr,
img {
    page-break-inside: avoid;
}

img {
    max-width: 100% !important;
}

@page  {
    margin: 0.5cm;
}

h2,
h3 {
    page-break-after: avoid;
}

.hidden-print {
    display: none !important;
}

.do-not-break, .do-not-break-agent{
    page-break-inside: avoid;
}
.page-breaker {
    page-break-after: always;
}

table{
    width:810px !important;
    word-wrap: break-word;
}

td.limited-cell{
    max-width: 200px;
}
tr,
td{
    height: 0px !important;
    overflow: hidden !important
}
td.limited-cell-81{
    width: 90px;
    min-width: 90px;
    max-width: 90px;
}
img.img-sized{
    height: 10cm !important;
}
```

Here is a example : 

[rapport.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/117458/rapport.pdf)

I've tried lots of things, but no success, like changing the page-break-inside /  page-break-before /  page-break-after
Tried to change div to span or p, no effets, even tried to remove table tr td to some div with css.

The gap between the images seems not to be the same from a page to another.

Any idea please ?

**Comment by BenBezac** [comment] 2016-02-22 12:57
Up please, still need help for this. Thx

**Comment by BenBezac** [comment] 2016-03-03 09:21
Still need help please,

We are willing to pay you the effort

**Comment by NicoBarbaros** [comment] 2016-06-17 12:27
I got the same problem with text, nothing seems to work? 

Maybe you fixed it somehow @BenBezac ?

**Comment by BenBezac** [comment] 2016-09-26 07:30
Hi, sry for the delay.

We didn't find any fix and we put aside this library : /

**Comment by BDhara** [comment] 2017-05-17 09:43
which library did u use for conversion because I'm facing same problem @BenBezac 
did you find any solution @nicubarbaros ?

**Comment by BenBezac** [comment] 2017-05-24 11:46
Problem is still pending @BDhara so we are gonna move to a solution in java like jasperreport, cause clearly it's a ghost town over here

**Comment by BDhara** [comment] 2017-05-24 12:41
Actually I solved it by using div instead of table @BenBezac :)

**Comment by BenBezac** [comment] 2017-05-26 14:02
@BDhara good move :)
Couldn't use div instead of table without a shitload of css x)

**Comment by Tomsgu** [comment] 2018-09-05 09:35
Closing as duplicate of #2029.

**Closed by Tomsgu** 2018-09-05 09:35 UTC
Labels: NeedInfo
