### ISSUE TITLE
Changing --dpi option makes no difference in v0.12.4

### ISSUE THREAD

**Issue by alphestdev** [wkhtmltopdf/wkhtmltopdf#3287] opened 2017-01-13 12:32 UTC
These commands produce exactly the same PDF:

`"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" --dpi 300 "D:\invoice.html" "D:\test_invoice_300dpi.pdf"`

`"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" --dpi 600 "D:\invoice.html" "D:\test_invoice_600dpi.pdf"`

It's also exactly the same as not setting `--dpi` parameter at all.

I'm new to this tool, am I missing something? Or is this a bug?

Tested on Windows 7 x64

**Comment by markevans** [comment] 2017-02-15 11:37
I see the same problem on Mac OSX.
I got around it (which I _think_ works) by using CSS to make the page 2480px wide and 3508px high (A4), then only using the `--page-width`, `--page-height` and `--viewport-size` switches (and leaving out `--zoom` and `--dpi`)

**Comment by ReganRyanNZ** [comment] 2018-03-27 00:19
`--dpi` and `--zoom` make a difference on my local OSX machine, but don't affect my AWS linux servers (wkhtmltopdf 0.12.4 qt). Any help/fix would be g r e a t

**Comment by ReganRyanNZ** [comment] 2018-03-27 02:04
A temp workaround is to set the page width and height to px, instead of cm. It means the page dimensions might end up weird, but at least the content will line up with the page nicely.

**Comment by hassenc** [comment] 2018-05-31 15:05
Same problem here. `--dpi` is not affecting my server.

**Comment by Tomsgu** [comment] 2018-08-08 09:33
Does the problem still exists in `0.12.5`?

**Comment by vinhluan** [comment] 2018-08-23 11:50
Yes it does on Linux systems. I haven't tested it on other systems though.

**Comment by Tomsgu** [comment] 2018-08-24 08:18
Duplicate of #2579.

**Closed by Tomsgu** 2018-08-24 08:18 UTC
Labels: NeedInfo
