### ISSUE TITLE
long tables across pages get column headers superposed to first row on the next page.

### ISSUE THREAD

**Issue by lpagani91** [wkhtmltopdf/wkhtmltopdf#2531] opened 2015-08-18 21:59 UTC
Hello,

When a table is too long to fit in the page, wkhtmltopdf nicely breaks it in two parts and repeats the column headers on the new page. It is very convenient except that these column headers do not have their own room to appear and are superposed to the first row to be printed on the next page (here on the 6th row). A shame...
![capture d ecran 2015-08-18 a 14 10 32](https://cloud.githubusercontent.com/assets/13851060/9343861/e192992a-4604-11e5-8fba-8faf09b77eae.png)

Can we avoid this in the command line (did not find anything looking useful in the -H option) or is it a bug ?

Thanks,
Laurent

**Comment by lpagani91** [comment] 2015-08-19 08:55
This problem appears on a Mac under OS 10.7.5. This morning I installed wkhtmltopdf on Ubuntu and the problem did not appear.

**Comment by lpagani91** [comment] 2015-08-19 09:05
On Ubuntu, I have an older version (0.9.9) which works nicely. The version above is 0.12.2.1 (with patched qt, it says).

**Comment by PhilterPaper** [comment] 2015-08-20 14:21
I encountered this with 0.12.2.4 (patched QT). I ended up changing the CSS to tell it never to break within a **tr**. This leaves quite a bit of wasted space at the bottom of the page, if the next row doesn't quite fit, and wkhtmltopdf also has a bug I've reported that the table left and right borders are continued to the bottom of the page.

**Comment by mrbokx** [comment] 2015-08-20 14:24
@PhilterPaper 
What CSS did you use to overcome this issue?

**Comment by PhilterPaper** [comment] 2015-08-21 20:01
`tr { page-break-inside: avoid; }`

**Comment by mrbokx** [comment] 2015-08-25 08:04
@PhilterPaper thanks, it seems to be a good workaround!

**Comment by Tomsgu** [comment] 2018-06-20 07:13
Duplicate of #1524.
Please read the this issue. You can find some workarounds that can improve a situation, since there is no real fix yet.

**Closed** 2018-06-22 07:02 UTC
Labels: Duplicate

**Comment by susajsnair** [comment] 2018-07-19 10:41
@PhilterPaper 
`tr { page-break-inside: avoid; }`
Its ain't working for me

**Comment by Tomsgu** [comment] 2018-07-19 12:22
@susajsnair have you read #2141 or #1524?

**Comment by susajsnair** [comment] 2018-07-19 15:11
@Tomsgu thanks for your reply.
actually i made 0.12.2.4 to 0.12.4 update added `<thead style="display: table-row-group;">` and it is working fine now.

**Comment by Tomsgu** [comment] 2018-07-19 15:41
@susajsnair nice to hear that. :thumbsup:
