### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ingedgarmorales** [wkhtmltopdf/wkhtmltopdf#2641] opened 2015-10-25 02:56 UTC
its wkhtmltopdf properly installed?
`wkhtmltopdf -H`

![image](https://cloud.githubusercontent.com/assets/5240279/10713809/3679634c-7a99-11e5-8a51-303612c3af04.png)

Because when i do: `wkhtmltopdf http://google.com google.pdf` i get:  
![image](https://cloud.githubusercontent.com/assets/5240279/10713787/26d28564-7a98-11e5-9964-3e2b9efd12b7.png)
1. I'll try completely uninstall wkhtmltopdf  and then reinstall it using next:
   `wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm`
   `rpm -Uvh wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm`
   IT IS OK? 
2. How can I  uninstall wkhtmltopdf from webserver in CentOs 6 64 bits ?
   I did `rpm -e wkhtmltopdf` but doesnt work for me:
   ![image](https://cloud.githubusercontent.com/assets/5240279/10713802/dee946b0-7a98-11e5-8eb0-49223f345b28.png)
3. What am i doing wrong?

Thank you !

**Comment by ingedgarmorales** [comment] 2015-10-25 03:23
Fixed!

Install Dependencies:

`yum install -y xorg-x11-fonts-75dpi`
`yum install -y xorg-x11-fonts-Type1`

And its works! :+1: 

![image](https://cloud.githubusercontent.com/assets/5240279/10713887/caceb624-7a9d-11e5-9017-f05cda753db7.png)

![image](https://cloud.githubusercontent.com/assets/5240279/10713890/df407c32-7a9d-11e5-818c-9d5ffbad8e7c.png)

**Comment by bernstein7** [comment] 2016-10-20 13:26
What was the solution?

**Comment by Tomsgu** [comment] 2018-08-13 09:36
Closing as I cannot reproduce the crash in `0.12.5`. Please feel free to re-open if the issue still exists.

**Closed by Tomsgu** 2018-08-13 09:36 UTC
Labels: NeedInfo

**Comment by levpr** [comment] 2018-09-05 08:00
Try to _wkhtmltopdf --log-level error https://www.chartjs.org/ chartjs.pdf_. The same error: _Segmentation fault_. wkhtmltopdf 0.12.5.

**Comment by Tomsgu** [comment] 2018-09-05 08:06
Maybe the same error, but a different issue. Please use search functionality to find issues with chartjs.
