### ISSUE TITLE
Fail to load images with NFD (decomposed Unicode normalization form) file names

### ISSUE THREAD

**Issue by DavidCasillasRivero** [wkhtmltopdf/wkhtmltopdf#3888] opened 2018-04-23 06:19 UTC
I'm running `wkhtmltopdf 0.12.2.4` on Ubuntu16, installed using `apt-get`. When trying to convert a page which contains images with file names in NFD normalization form (they where named in OSX) the images fail to load and are displayed as missing images in the PDF.  All of this pages work fine when viewed in a browser. To reproduce the error the file names should include non ASCII characters like accented vocals (á, é, í, ó, ú).
Renaming the files with NFC normalization form fixes the issue.
Since I have not seen this problem reported I may be missing something. I have checked that:
- The requested file name in disk is in NFD form
- The file name in the database is in NFD form
- The file name in the request when viewing the page in the browser is in NFD form

I attach a simple example to reproduce the problem with an simple HTML file that loads the same image two times, with the file name in NFD and NFC forms. The images are displayed in the browser but the NFD one fails in PDF after running:
`wkhtmltopdf index.html out.pdf`

[wkhtmltppdf-NFD.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1936884/wkhtmltppdf-NFD.zip)

**Comment by Tomsgu** [comment] 2018-07-04 07:21
For me everything works well with wkhtmltopdf 0.12.5 on linux (trying your example). Does the issue still exist in this version?

**Comment by Tomsgu** [comment] 2018-08-21 15:51
Closing as I can't reproduce the issue in a newest version and there is no feedback from the author.

**Closed by Tomsgu** 2018-08-21 15:51 UTC
Labels: NeedInfo
