### ISSUE TITLE
Hyperlink goes to the wrong page

### ISSUE THREAD

**Issue by icnocop** [wkhtmltopdf/wkhtmltopdf#4322] opened 2019-04-09 08:10 UTC
**wkhtmltopdf version(s) affected**: 
0.12.4_msvc2015-win64
0.12.5-1.msvc2015-win64
0.12.6-0.20180618.3.dev.e6d6f54.msvc2015-win64
0.12.6-0.20180618.3.dev.e6d6f54.msvc2015-win32

**OS information**
Windows 10 Enterprise 64-bit Version 1809 (OS Build 17763.292)

**Description**
I generated a PDF from 4 HTML files:
1. toc.html
2. Page 1.html
3. Page 2.html
4. Page 3.html

toc.html has a hyperlink to all the other pages.
The hyperlink to Page 3 goes to the wrong page in the generated PDF.

**How to reproduce**
1. Download and unzip [wkhtmltopdf_bug.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3057799/wkhtmltopdf_bug.zip) to a folder of your choice.
2. wkhtmltopdf should be in your `%PATH%`.
3. Run `build.cmd` which basically runs the following command:
 `wkhtmltopdf.exe articles\toc.html "articles\Page 1.html" "articles\Page 2.html" "articles\Page 3.html" test.pdf`
4. Open the generated `test.pdf` in Adobe Acrobat Reader DC 2019.010.20098
5. Click on the `Page 3` hyperlink on the first page and notice that it goes to page 5

**Expected behavior**
I expected the `Page 3` hyperlink on the first page to go to page 4.

Notice the bookmark/outlines work without issues.

**Comment by PhilterPaper** [comment] 2019-04-10 00:19
Your link to page 3 is only to "Page%203.html". If you add a specific anchor point "Page%203.html#page-3" (the first id), it will go to the expected place. If you only give a file name, I'm not sure there's any specific point in the file that it's supposed to go to.

**Comment by icnocop** [comment] 2019-04-10 00:28
The thing is that the "Page 1" and "Page 2" links work without issue.

**Comment by ashkulz** [comment] 2019-04-10 05:43
Duplicate of #1947

**Closed by ashkulz** 2019-04-10 05:43 UTC

**Comment by ashkulz** [comment] 2019-04-10 05:49
@icnocop: can you check whether the patch posted in the linked issue works for you?
