### ISSUE TITLE
TOS is not working on 0.12.5, but works on 0.12.3

### ISSUE THREAD

**Issue by cerw** [wkhtmltopdf/wkhtmltopdf#4540] opened 2019-11-27 04:12 UTC
**wkhtmltopdf version(s) affected**: 0.12.5

**OS information**
Linux/Mac

**Description**
I had to downgrade to 0.12.3 to get TOS working on larger (10 pages pdf) . BUt 0.12.3 has ContentNotFound crash bug which makes it hard to test and there must be no 404! So I hope we can somehow make the newest/bested version to do the right TOS.

**How to reproduce**
Same html generated with same options 
[0.12.3](https://www.dropbox.com/s/j8bpmv3uepsxbr8/Manual_199_P_22_C_1-20191127.04_good.pdf?dl=0) 
[0.12.5](https://www.dropbox.com/s/vltd13eh1jmqibj/Manual_199_P_22_C_1-20191127.04_bad.pdf?dl=0)

**Expected behavior**
Create Cover + TOS + Content.

**Possible Solution**  
No idea. 

Thanks

**Comment by ashkulz** [comment] 2020-06-05 20:09
Duplicate of #3953, please try using the 0.12.6 release candidate (should be updated in a day's time).

**Closed by ashkulz** 2020-06-05 20:09 UTC

**Comment by ashkulz** [comment] 2020-06-07 08:31
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
