### ISSUE TITLE
TOC page is not created

### ISSUE THREAD

**Issue by guillaumefortin** [wkhtmltopdf/wkhtmltopdf#4056] opened 2018-08-22 13:31 UTC
I installed 0.12.5 using centos6 and centos7 rpm with different arguments combinations and I naver have the TOC page in my PDF. Tried many examples supposed to work.

**Comment by Tomsgu** [comment] 2018-08-22 13:50
Duplicate of #3953. It was fixed, but there is no stable release yet.

**Closed by Tomsgu** 2018-08-22 13:50 UTC
Labels: Duplicate

**Comment by ashkulz** [comment] 2020-06-07 08:29
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
