### ISSUE TITLE
wkhtmltoimage.exe not working on windows server 2012

### ISSUE THREAD

**Issue by wiredmonkey** [wkhtmltopdf/wkhtmltopdf#2651] opened 2015-10-28 22:37 UTC
Hi 

I've recently migrated a website which make an image of the webpage using wkhtmltoimage.exe. It worked perfectly on Windows Server 2008 R2 Datacenter but the functionality has stopped working on Windows Server 2012. The process just times out, any ideas?

Cheers

Shaun

**Comment by seixasfelipe** [comment] 2015-12-11 21:10
Same problem here, on Windows Server 2012.

**Comment by cclarke6264** [comment] 2015-12-13 06:45
I've got it running on Windows Server 2012 R2

**Comment by Tomsgu** [comment] 2018-08-23 08:30
Is this still an issue in 0.12.5?

**Comment by cclarke6264** [comment] 2018-08-23 10:03
Hi,

 

I wouldn’t know, we stopped using the software a while ago.

 

Regards

 

Chris C.

**Comment by Tomsgu** [comment] 2018-08-23 11:03
Thanks for the feedback. I am closing it since there is no way to reproduce the issue.

**Closed by Tomsgu** 2018-08-23 11:03 UTC
Labels: NeedInfo
