### ISSUE TITLE
rowspan cell exceed row height at before page break

### ISSUE THREAD

**Issue by lertoo** [wkhtmltopdf/wkhtmltopdf#2803] opened 2016-02-18 00:01 UTC
When a table cell has rowspan set, and the next row is moved to the next page, the cell height exceed the height of the row. I believe this problem is with the upstream QT WebKit.
```html
<xmp>
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Overflow testing</title>
</head>
<body style="font-family: Arial; font-size: 11px;">
    <div style="height: 1100px; border: solid 1px gray;">
        Space holder
    </div>
    <br />
    <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
        <tr style="page-break-inside: avoid;">
            <td style="vertical-align: middle; width: 150px; color: red; background-color: #eee;" rowspan="2">
                This cell exceeds the row height
            </td>
            <td>
                sth.
            </td>
        </tr>
        <tr style="page-break-inside: avoid;">
            <td>
                sth.
            </td>
        </tr>
        <tr style="page-break-inside: avoid;">
            <td>
                sth.
            </td>
            <td>
                <div style="height: 200px;">
                    This cell will be moved to the next page.
                </div>
            </td>
        </tr>
    </table>
</body>
</html>
</xmp>
```
![rowspan-cell-height-page-break](https://cloud.githubusercontent.com/assets/4444524/13129130/e32811f6-d62e-11e5-9673-7a383a9ac057.JPG)

**Comment by PhilterPaper** [comment] 2016-02-18 14:08
Your code is unreadable. Please use proper code markup (blank line before and after, indent 4 spaces) and proper HTML (< and >, not & lt; and & gt;).

    <!DOCTYPE html>
    <head> etc.

**Comment by lertoo** [comment] 2016-02-19 00:27
Don't know how to format it. Put it into a HTML file, generate PDF, you will see the result. When copy to an HTML file, development tool like Visual Studio Code will automatically format it for you.

**Comment by PhilterPaper** [comment] 2016-02-20 15:39
This is what people expect to see:

    <!DOCTYPE html>
    <html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta charset="utf-8" />
      <title>Overflow testing</title>
    </head>
    <body style="font-family: Arial; font-size: 11px;">
      <div style="height: 1100px; border: solid 1px gray;">
        Space holder
      </div>
    
      <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
        <tr style="page-break-inside: avoid;">
          <td style="vertical-align: middle; width: 150px; color: red; background-color: #eee;" rowspan="2">
            This cell exceeds the row height
          </td>
          <td>
            sth.
          </td>
        </tr>
        <tr style="page-break-inside: avoid;">
          <td>
            sth.
          </td>
        </tr>
        <tr style="page-break-inside: avoid;">
          <td>
            sth.
          </td>
          <td>
            <div style="height: 200px;">
              This cell will be moved to the next page.
            </div>
          </td>
        </tr>
      </table>
    </body>
  </html> 

No extra `<br>`s, no extra `<p>`s, multiple lines, no `<` and `>` replaced by entities. Please learn to use a real text editor instead of a WYSIWYG page editor.

**Comment by JoseAlmela** [comment] 2018-01-10 12:32
Hello,

I have the same issue.
This occurs when the rowbefore the page break has an rowspan > 1.

**Comment by Tomsgu** [comment] 2018-09-05 10:04
Closing as i can't reproduce it in 0.12.5. Please feel free to re-open this issue if you still experience the problem.

**Closed by Tomsgu** 2018-09-05 10:04 UTC
Labels: NeedInfo
