### ISSUE TITLE
Repeating table headers being overlaid on new content

### ISSUE THREAD

**Issue by BruceEckel** [wkhtmltopdf/wkhtmltopdf#2679] opened 2015-11-19 19:33 UTC
![badtablegeneration](https://cloud.githubusercontent.com/assets/1001900/11281859/683a5374-8eb1-11e5-9d35-2b5277dca2ff.PNG)

**Comment by evandroprogram** [comment] 2015-11-25 18:14
I fix it using the css `page-break-inside` property on my report CSS. Add this snipet to your report CSS and tell us if it works:
`/* Page break issue fix */
table, tr, td, th, tbody, thead, tfoot {
    page-break-inside: avoid !important;
}`

**Comment by BruceEckel** [comment] 2015-11-27 18:27
I had fixed it with:

tr { page-break-inside: avoid; }




-- Bruce Eckel
www.MindviewInc.com <http://www.mindviewinc.com/>
Blog: BruceEckel.github.io
www.WinterTechForum.com
www.AtomicScala.com
www.Reinventing-Business.com
http://www.TrustOrganizations.com <http://www.ScalaSummit.com>

**Comment by barryvdh** [comment] 2015-12-04 09:04
Can confirm that `tr { page-break-inside: avoid; }` fixes this issue, in `0.21.2.1`

**Comment by rainabba** [comment] 2016-01-28 18:34
@BruceEckel If you've confirmed a solution, you may want to close this issue.

**Comment by Tomsgu** [comment] 2018-06-19 13:42
Duplicate of #1524

**Closed** 2018-06-21 07:10 UTC
Labels: Duplicate
