### ISSUE TITLE
Converting web to SVG causes error in QSvgGenerator

### ISSUE THREAD

**Issue by ginzor** [wkhtmltopdf/wkhtmltopdf#2035] opened 2014-11-06 08:56 UTC
This might be that I am missing something but I couldn't google my way to an answer so I try my luck here. The issue I am experiencing is this "unhandled metric". I tried sending both width and height with no luck. It works well with png rendering. Sometimes this evens causes Segmentation Fault (might be another issue). The page described below is static in its content over time and the ouput I get is a decent line out (however lacking all text content).

> wkhtmltoimage -f svg --no-images "http://demo.playscan.com/" output.svgLoading page (1/2)
> Rendering (2/2)  
> QSvgGenerator::metric(), unhandled metric 11                 ] 25%
> 
> QPainter::begin: Paint device returned engine == 0, type: 2
> QPainter::setRenderHint: Painter must be active to set rendering hints
> QPainter::translate: Painter not active
> QPainter::setPen: Painter not active
> QPainter::setBrush: Painter not active
> QPainter::setWorldTransform: Painter not active
> QPainter::setFont: Painter not active
> QPainter::setOpacity: Painter not active
> QPainter::setBrush: Painter not active
> QPainter::brush: Painter not active
> QPainter::fillPath: Painter not active
> QPainter::end: Painter not active, aborted
> Done      

== Versions ==
wkhtmltoimage --version
wkhtmltoimage 0.12.1

Debian Testing
Linux  3.16-2-amd64 #1 SMP Debian 3.16.3-2 (2014-09-20) x86_64 GNU/Linux

**Comment by alloylab** [comment] 2018-06-15 13:52
have you tried this on 0.12.5?

**Comment by Tomsgu** [comment] 2018-08-22 14:45
Closing as there is no feedback from the author and I can't reproduce the issue in `0.12.5`.

**Closed by Tomsgu** 2018-08-22 14:45 UTC
Labels: NeedInfo
