### ISSUE TITLE
Flex is not supported yet =(

### ISSUE THREAD

**Issue by KES777** [wkhtmltopdf/wkhtmltopdf#4072] opened 2018-09-05 12:22 UTC
```
$ wkhtmltopdf --version
wkhtmltopdf 0.12.5 (with patched qt)
```

rendered by `wkhtmltopdf`:
[test.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2352691/test.pdf)

How this is rendered by FFv61
![delete1](https://user-images.githubusercontent.com/799021/45092822-4389b180-b11f-11e8-883a-40cf57d836d9.jpg)  View port resolution: 1016x399

source html and css:

[t.tar.gz](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2352698/t.tar.gz)

**Comment by Tomsgu** [comment] 2018-09-05 12:27
Closing as duplicate of #3207

**Closed by Tomsgu** 2018-09-05 12:27 UTC
