### ISSUE TITLE
Unused anchors dropped in PDF produced by wkhtmltopdf

### ISSUE THREAD

**Issue by daytonb** [wkhtmltopdf/wkhtmltopdf#2348] opened 2015-05-05 15:08 UTC
I create a named anchor for each of my section heading in an HTML document. Only those referenced by an `href` actually get put into the PDF (based on my exploring the PDF in a text editor).

I have a project in which I need to include the PDF of an HTML document as a chapter of in a larger PDF document. I really want to be able to link to sections in the chapter produced by wkhtmltopdf, but
almost none of my anchors make it into the PDF file.

**Comment by daytonb** [comment] 2015-05-05 15:15
I was going to upload an example HTML and resulting PDF, but I don't see a way to do that with github, so the HTML is shown below:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta content="text/html; charset=ISO-8859-1" http-equiv="content-type">
<title>Link Example</title>
</head>
<body>
    <h1><a name=unused_anchor></a>Section Heading with Unused Anchor</h1>

    <p>
    The section heading to this section has an anchor in the HTML, but
    <i>wkhtmltopdf</i> does not include this anchor in the PDF because no
    <i>href</i>s link to it.
    </p>

    <h1><a name=used_anchor></a>Section Heading with Referenced Anchor</h1>

    <p>
    On the other hand, because <a href=#used_anchor>this link</a> references
    the anchor in the heading to this section, the anchor in this section
    heading is included in the PDF produced by <i>wkhtmltopdf</i>.
    </p>
</body>
</html>
```

**Comment by ashkulz** [comment] 2015-05-07 04:56
Duplicate of #1554.

**Closed by ashkulz** 2015-05-07 04:56 UTC
