### ISSUE TITLE
Blank PDF in local

### ISSUE THREAD

**Issue by iNaraku** [wkhtmltopdf/wkhtmltopdf#3851] opened 2018-03-16 18:33 UTC
I have a problem with the press, my project is developed in ASP.NET MVC 5, everything worked fine until I changed my laptop, downloaded my TFS project and now the generated PDFs are shown blank in my local, but if the information is displayed correct on the server, I have the dll in the rotary folder as msvcp120.dll, msvcr120.dll, vccorlib120.dll, wkhtmltoimage.exe, wkhtmltopdf.exe, but I can not make it work locally

**Comment by alloylab** [comment] 2018-06-15 12:57
what version?

**Comment by Tomsgu** [comment] 2018-08-06 14:35
Closing because the issue is missing important information and there is no feedback from the author.

**Closed by Tomsgu** 2018-08-06 14:35 UTC
Labels: NeedInfo, NeedMinimalTestcase
