### ISSUE TITLE
Double encoding of quotation mark in URL

### ISSUE THREAD

**Issue by surferboy2** [wkhtmltopdf/wkhtmltopdf#4545] opened 2019-12-02 19:39 UTC
**wkhtmltopdf version(s) affected**: 
wkhtmltopdf 0.12.5 (with patched qt)

**OS information**
MAC OS Catalina - root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64

**Description**
Double encoding of quotation marks in URL's

**How to reproduce**
r stat encodes " mark in URL so snippet of original URL in html file ..... <+!type:%22Access+Point+Interface%22>
will be encoded as <!type:%2522Access+Point+Interface%2522> after export via wkthmltopdf

**Expected behavior**
Is there anything I can do to prevent this double encoding?

**Comment by lestal** [comment] 2020-03-12 15:48
I encountered with same issue. Are there any updates?

**Comment by ashkulz** [comment] 2020-06-09 02:03
Duplicate of #4406

**Closed** 2020-06-09 02:05 UTC
