### ISSUE TITLE
PDF and HTML look different with Letter Spacing

### ISSUE THREAD

**Issue by kamalsamra** [wkhtmltopdf/wkhtmltopdf#3043] opened 2016-07-21 11:21 UTC
using version 0.12.3

Specifically the problem I'm having is with letter-spacing declarations which also have a float not being rendered correctly. So for instance on a right float element which has the letter-spacing, the PDF will space the characters too much.

**Comment by c0dechick** [comment] 2016-08-09 17:00
Try setting the dpi to 96 and then set letter-spacing.
Reference: [https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2899]

**Comment by Tomsgu** [comment] 2018-07-26 05:43
Duplicate of #2899

**Closed by Tomsgu** 2018-07-26 05:43 UTC
Labels: NeedInfo
