### ISSUE TITLE
Exit with code 1 due to network error: HostNotFoundError

### ISSUE THREAD

**Issue by damienh** [wkhtmltopdf/wkhtmltopdf#2532] opened 2015-08-19 12:08 UTC
I am using `wkhtmltopdf 0.12.2.1 (with patched qt)` 64 bit version and I am using Pdfkit to execute the generation.

I am randomly getting the error below. I have around 30 html pages and sometimes it completes, but the majority of the time it fails on a random html document and gives the below error:

`Exit with code 1 due to network error: HostNotFoundError
/Users/damien/.rvm/gems/ruby-2.1.1@project-site/gems/pdfkit-0.8.0/lib/pdfkit/pdfkit.rb:71:in `to_pdf': command failed (exitstatus=1): /usr/local/bin/wkhtmltopdf --page-size A3 --load-error-handling skip --load-media-error-handling ignore --javascript-delay 600 --print-media-type --footer-html ./config/pdf-generation/_sample_footer.html --header-spacing 2 http://localhost:4000/en-GB/archived/frantic-felix/index.html - (RuntimeError)`

Here is an example of the output:

```
Loading pages (1/6)
Warning: SSL error ignored                                         
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)                                               
Done                                                                      
Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)                                               
Done                   
```

In the html doc there are links to assets like followed:

```
<script src="https://use.typekit.net/xxxx.js"></script>
<link rel="stylesheet" href="/assets/main-2a7e0e242618c238cd73c2ad7280dec6.css">
<script src="/assets/bootstrap.min-8b9f8d66b5b56652f31b666757632c52.js"></script> 
<script src="/assets/smooth-scroll-9b5d196c4dac2586d95e2b4d3f9eca25.js"></script>
```

The it still generates the pdf and it looks fine. All styles loaded ect. 

Some of the projects do have iframes, though these are hidden in the actual print css. 

example of a iframe call: `<p><iframe allowtransparency="true" width="485" height="402" src="http://scratch.mit.edu/projects/embed/60787262/?autostart=false" frameborder="0"></iframe> <img src="images/ghost-final.png" /></p>
` 
In my server logs I can see no 404 messages on resources not loading.

I have tried 32bit and 64bit versions but I am having no luck. 

Can anyone point me in the right direction?

**Comment by damienh** [comment] 2015-08-19 12:10
Here is a link to sample of the full html https://gist.github.com/damienh/d954d985593d5ab2f25b

**Comment by Shurlow** [comment] 2015-08-27 18:45
Im getting a similar issue, though my html file is extremely basic. I only get this error when adding the --user-style-sheet option...

**Comment by damienh** [comment] 2015-09-01 10:11
I have also noticed I get this when the html page does not contain iframes as well. Its really random.

**Comment by damienh** [comment] 2015-09-03 14:14
Having looked at activity monitor on OSX I think it may actually be running out of memory!

**Comment by dconradda** [comment] 2016-06-01 15:01
I'm getting this same error when running this command:
C:\Windows\wkhtmltopdf.exe *.html *.pdf
Using 0.12.3.2 64-bit Windows 7

However, I can get the converter to work when running individual files, such as 
C:\Windows\wkhtmltopdf.exe 2.html 2.pdf

**Comment by ashkulz** [comment] 2016-06-02 07:51
@damienh: is it reproducible when you run it from the command line?

**Comment by woohoou** [comment] 2016-08-24 23:49
+1

**Comment by koflerdavid** [comment] 2016-09-03 15:14
I just experienced the same problem. The reason was that I referenced jQuery from a CDN, but my machine was disconnected from the internet, so wkhtmltopdf could not access it.
I'd recommend to not include any assets from the web if you use wkhtmltopdf for heavy-duty PDF rendering.

**Comment by koflerdavid** [comment] 2016-09-03 15:15
Actually, there is an option `--load-media-error-handling`, defaulting to `ignore`, which should prevent this problem, shouldn't it?

**Comment by Sicos1977** [comment] 2016-09-16 09:13
--load-media-error-handling ignore
--load-error-handling ignore

**Comment by daveztong** [comment] 2016-12-05 08:49
--load-media-error-handling ignore
--load-error-handling ignore

tried both, did not work!

**Comment by tristan-k** [comment] 2017-02-02 15:46
Same here.

**Comment by qayyumabro** [comment] 2017-02-10 15:02
Same issue with centos7, same command was working fine on centos5.
I'm using setup from here http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/

**Comment by omrqs** [comment] 2017-03-02 22:52
This error occurs when url are defined as //url... in place of https://url....
Keep the protocol. 
wkhtmltopdf try find double slash as local path...

Solved for me.

**Comment by sharfaz** [comment] 2017-03-24 10:43
After spending number of days to fix the issue I found the resolution.  The problem is VM trying to load the host from VM itself and cannot find. Update your VM host file to refer your Virtual Host

So edit your VM (homestead or any other OS) host file.

/etc/hosts
127.0.0.1 #add your virtual host

This resolved my problem.
I have Bootstrap and local css assets in my pdf header and after changing host file everything worked!!!

**Comment by dev-hitech** [comment] 2017-11-26 13:41
Thanks @omrqs, you inspired my solution. My problem was that I used host alias on my local machine for the public IP. This deceived wkhtmltopdf from the real source of static files loaded in the template file, and it couldn't load static files.

**Comment by Tomsgu** [comment] 2018-08-22 18:26
Closing as it seems to be resolved by replacing relative urls to absolute ones. Please feel free to re-open if the issue still persists.

**Closed by Tomsgu** 2018-08-22 18:26 UTC
Labels: NeedInfo

**Comment by junior-lupainformatica** [comment] 2020-07-02 22:40
I am having this issue with version 0.12.6

On localhost (WAMP) it works perfectly, but on Homolog (Debian Buster) it fails

```
The exit status code '1' says something went wrong: stderr: "Loading pages (1/6) [> ] 0% [======> ] 10% [=======> ] 12% Error: Failed to load https://clubepatrulheiro.lupahosting.com.br/theme/SmartAdmin/css/bootstrap.min.css, with network status code 3 and http status code 0 - 
Host not found Error: Failed to load https://clubepatrulheiro.lupahosting.com.br/theme/SmartAdmin/css/font-awesome.min.css, with network status code 3 and http status code 0 - Host not found Error: Failed to load https://clubepatrulheiro.lupahosting.com.br/theme/SmartAdmin/css/smartadmin-production.min.css, with network status code 3 and http status code 0 - 
Host not found Warning: Failed to load https://clubepatrulheiro.lupahosting.com.br/theme/SmartAdmin/css/intranet.css (ignore) Warning: Failed to load https://clubepatrulheiro.lupahosting.com.br/img/certificado_associacao.png (ignore) [=========> ] 15% Error: Failed to load https://clubepatrulheiro.lupahosting.com.br/webroot/fonts/LiberationSerif-Regular.ttf, with network status code 3 and http status code 0 - 
Host not found Error: Failed to load https://clubepatrulheiro.lupahosting.com.br/webroot/fonts/LiberationSerif-BoldItalic.ttf, with network status code 3 and http status code 0 - 
Host not found Error: Failed to load https://clubepatrulheiro.lupahosting.com.br/webroot/fonts/LiberationSerif-Bold.ttf, with network status code 3 and http status code 0 - Host not found [============================================================] 100% Counting pages (2/6) [============================================================] 
Object 1 of 1 Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load. 
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load. Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load. Resolving links (4/6) [============================================================] 
Object 1 of 1 Loading headers and footers (5/6) Printing pages (6/6) [> ] Preparing [============================================================] 
Page 1 of 1 Done Exit with code 1 due to network error: HostNotFoundError " 
stdout: "" command: /usr/local/bin/wkhtmltopdf --orientation Landscape --margin-top 0 --margin-bottom 0 --margin-left 0 --margin-right 0 --lowquality '/tmp/knp_snappy5efe61233734f9.28252574.html' '/var/www/clubedopatrulheiro/Files/Titulos/201807/pdf/titulo-123.pdf'.
```

**Comment by neerajmathur** [comment] 2020-12-03 09:20
**Request to reopen this issue**

I am getting this error too despite of passing --load-error-handling  ignore flag. In our case we cannot control URL's, since user is pasting content from external source (say internet). I am wondering why it is still throwing **HostNotFoundError** even after including the required ignore flag

C:\Users\neeraj.x.mathur>D:\temp\HtmlToPdf\wkhtmltopdf.exe **--load-error-handling
 ignore**  --disable-javascript --disable-external-links --disable-internal-links
"http://XXX/Message/PdfSnapshot/MessageCopy/23423?IsEmailRendering=True&userid=65374&usertypeid=63" D:\Temp\abc.pdf
Loading pages (1/6)
Error: Failed to load https:/images?q=tbn:ANd9GcQfaSPCKLwxcSVAooxEWcM77EoUp35icCgdXjcsQdPj8mQEZsz-Eg, with network status code 3 and http status code 0 - Host
not found
Error: Failed to load https:/images?q=tbn:ANd9GcTia8nYc0xmdwpK94pulGCw-PnLhsd55fP_RIZZ1gmKEL7eIjjd, with network status code 3 and http status code 0 - Host  no
t found
Error: Failed to load https:/images?q=tbn:ANd9GcQDpw0hVBXwCVPGuUVV3QQwGavSyR-yTynlQUx6k-1kNiFoCKWV, with network status code 3 and http status code 0 - Host  no
t found
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
**Exit with code 1 due to network error: HostNotFoundError**

**Comment by mikebernal** [comment] 2021-03-08 02:07
@neerajmathur Have you found a solution to this problem?

**Comment by gildonei** [comment] 2021-03-08 11:06
> @neerajmathur Have you found a solution to this problem?

Only way i got to solve this, was putting all css and external ref inline

**Comment by vonsogt** [comment] 2021-03-23 04:21
I'm using windows:
I just got the same problems, the way I serve using "php artisan serve", but when I put the project_folder to `xampp/htdocs` and try to access the route again, it's work fine like it should.

**Comment by kmagzhan** [comment] 2022-08-31 19:11
Changing the page parameter from letter to a4 helped me. I do not know why

**Comment by cheeseytoastie** [comment] 2022-09-06 07:14
My problem with this error was the urls were behind a login - so the login screen and all the scripts were being returned rather than the simple html I was expecting.
