### ISSUE TITLE
Unable to figure out why chart is not rendering in the image.

### ISSUE THREAD

**Issue by mahesh-panchal** [wkhtmltopdf/wkhtmltopdf#3815] opened 2018-02-09 15:53 UTC
Hi,

I'm trying to automate exporting Krona charts to png using this tool. However I cannot understand why the chart does not render in the image.

This is the command I'm using.
```
wkhtmltox/bin/wkhtmltoimage --javascript-delay 900 http://krona.sourceforge.net/examples/text.krona.html test.png
```

Can someone provide any input on what I need to do to get the chart to render in the image?

Thank you in advance.

**Comment by Tomsgu** [comment] 2018-08-09 08:04
Most likely duplicate of #1964. There are some workarounds in this issue that you can try.

**Closed by Tomsgu** 2018-08-09 08:04 UTC
Labels: Duplicate
