### ISSUE TITLE
 Use 0.12.4 to convert the HTML to PDF, the page very very small. But use 0.12.3, it's OK.

### ISSUE THREAD

**Issue by diguage** [wkhtmltopdf/wkhtmltopdf#3795] opened 2018-01-26 07:19 UTC
Use 0.12.4 to convert the HTML file to PDF, the page very small. But use 0.12.3, it's OK.

macOS 10.13.2

**Comment by grahampaulcook** [comment] 2018-01-26 11:33
Does anything jump out if you compare the commits between 0.12.3 and 0.12.4

https://github.com/wkhtmltopdf/wkhtmltopdf/compare/0.12.3...0.12.4

**Comment by hakimio** [comment] 2018-01-29 18:04
Have you tried "disable-smart-shrinking" setting?

**Comment by hakimio** [comment] 2018-01-29 18:07
Also, there where some DPI fixes for Mac OS in unreleased 0.12.5:
https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/CHANGELOG.md
Might be worth building from source.

**Comment by diguage** [comment] 2018-02-26 10:56
@hakimio I do not try the setting. I try later. Thanks.

**Comment by alloylab** [comment] 2018-06-15 12:33
is this resolved?

**Comment by hakimio** [comment] 2018-06-15 12:36
@alloylab In the latest version (0.12.5) it is.

**Comment by ashkulz** [comment] 2018-06-15 12:37
duplicate of #3241

**Closed by ashkulz** 2018-06-15 12:37 UTC
