### ISSUE TITLE
thead overlapping tbody content on subsequent pages

### ISSUE THREAD

**Issue by allanlange** [wkhtmltopdf/wkhtmltopdf#3987] opened 2018-07-02 13:48 UTC
I'm experiencing some difficulties getting my tbody content to position correctly when I make use of a thead element in my table.

I have been using the method in this article (http://www.jessicaschillinger.us/2017/blog/print-repeating-header-browser/).

On the first page, where the thead element originally appears, it doesn't mess up anything.

![capture1](https://user-images.githubusercontent.com/15052294/42167862-9cb46dd8-7e0f-11e8-98e8-c69cc62acdfb.PNG)

Any ideas on how to fix this?

![capture](https://user-images.githubusercontent.com/15052294/42166794-6d7a4996-7e0c-11e8-871f-31ef09dea37c.PNG)

**Comment by Tomsgu** [comment] 2018-07-02 17:09
Duplicate of #1524.

**Closed by Tomsgu** 2018-07-02 17:09 UTC
