### ISSUE TITLE
Text being split horizontally across pages

### ISSUE THREAD

**Issue by BruceEckel** [wkhtmltopdf/wkhtmltopdf#2678] opened 2015-11-19 19:33 UTC
![badpagetransition](https://cloud.githubusercontent.com/assets/1001900/11281838/4ef6eb8e-8eb1-11e5-9e24-ddd221ccc6f4.PNG)

**Comment by PhilterPaper** [comment] 2015-11-21 19:46
See #2491 (which in turn points to older bugs).

**Comment by BruceEckel** [comment] 2015-11-21 22:43
`tr { page-break-inside: avoid }` Did not help. Is it because the problem
I'm having is within code listings?


-- Bruce Eckel
www.MindviewInc.com <http://www.mindviewinc.com/>
Blog: BruceEckel.github.io
www.WinterTechForum.com
www.AtomicScala.com
www.Reinventing-Business.com
http://www.TrustOrganizations.com <http://www.ScalaSummit.com>

**Comment by PhilterPaper** [comment] 2015-11-23 14:16
Obviously, if you don't have a `<tr>`, specifying CSS for a tr isn't going to help... I think there was some discussion for non-tables, such as putting material in a `<div>` or something, and using the **page-break-inside: avoid** on that. You don't want to have to wrap a div around every line of code -- hopefully there's a better solution than that! Be sure to read all the related discussions; you might find your solution in one of them.

**Comment by BruceEckel** [comment] 2015-11-25 17:44
For what it's worth, this didn't work either. The impression I get is that
this is a pretty fundamental problem; it's looking like I'll have to go
back to Pandoc.

.sourceCode {
    font-family:"Ubuntu Mono", monospace;
    margin-top: 0;
    margin-bottom: 0;
    font-weight: normal;
    font-size: 1.0em;
    page-break-inside: avoid;
}


-- Bruce Eckel
www.MindviewInc.com <http://www.mindviewinc.com/>
Blog: BruceEckel.github.io
www.WinterTechForum.com
www.AtomicScala.com
www.Reinventing-Business.com
http://www.TrustOrganizations.com <http://www.ScalaSummit.com>

**Comment by PhilterPaper** [comment] 2015-11-27 15:28
What kind of element is `.sourceCode` applied to? Is it a `<div>` with the entire listing, or is it one line at a time (perhaps inside its own `<div>`)? If it's the entire listing, if it exceeds a full page I think it will be forced to ignore "no break" instructions.

**Comment by BruceEckel** [comment] 2015-11-27 18:25
The entire listing. It's coming from markdown, so Pandoc is automatically
taking:

```java
(some lines of Java code)
```
and  surrounding it with the *sourceCode* class (which is Pandoc's class)


-- Bruce Eckel
www.MindviewInc.com <http://www.mindviewinc.com/>
Blog: BruceEckel.github.io
www.WinterTechForum.com
www.AtomicScala.com
www.Reinventing-Business.com
http://www.TrustOrganizations.com <http://www.ScalaSummit.com>

**Comment by PhilterPaper** [comment] 2015-11-27 18:55
So Pandoc is producing something like

    <div class="sourceCode">
    many lines
    of Java code,
    more than will
    fit on a page
    </div>

for its HTML output, which you are in turn changing into PDF? The original line splitting was happening *without* the `page-break-inside property`? And with it, it still splits in the middle of a line? Does anything good happen if you change to a different font? As you can probably guess, I'm running out of ideas here.

**Comment by BruceEckel** [comment] 2015-11-27 18:57
Yes, I do think this is probably unsolvable, because of the technology used
by wkhtmltopdf. Really too bad, because it's a great idea otherwise.


-- Bruce Eckel
www.MindviewInc.com <http://www.mindviewinc.com/>
Blog: BruceEckel.github.io
www.WinterTechForum.com
www.AtomicScala.com
www.Reinventing-Business.com
http://www.TrustOrganizations.com <http://www.ScalaSummit.com>

**Comment by Dunge** [comment] 2015-12-08 21:07
I have the same problem trying to print a webpage with tables. The row get split in two. I tried page-break-inside: avoid; for the tr and td styles, not working. On the other hand, if I print directly from Firefox the browser is intelligent enough to break the pages at the cells delimitation, something that wkhtmltopdf don't.

**Comment by BruceEckel** [comment] 2015-12-09 03:55
It's Payware, but this looks like the solution that will solve my problems:
http://www.princexml.com/


-- Bruce Eckel
www.MindviewInc.com <http://www.mindviewinc.com/>
Blog: BruceEckel.github.io
www.WinterTechForum.com
www.AtomicScala.com
www.Reinventing-Business.com
http://www.TrustOrganizations.com <http://www.ScalaSummit.com>

**Comment by Tomsgu** [comment] 2018-06-19 13:41
Duplicate of #2029.

**Closed** 2018-06-22 07:04 UTC
Labels: Duplicate

**Comment by Norris1z** [comment] 2022-08-23 18:30
Adding 
`    html,
    body {
        margin: 0;
        padding: 0;
        border: 0;
        font-size: 100%;
        font: inherit;
        vertical-align: baseline;
    }`

Fixed it for me.
