### ISSUE TITLE
wkhtmltopdf hangs with --window-status and --header-html = 404 not found

### ISSUE THREAD

**Issue by johnedo1234** [wkhtmltopdf/wkhtmltopdf#2229] opened 2015-03-03 18:43 UTC
To reproduce the hang, try this:

`wkhtmltopdf --load-error-handling abort --load-media-error-handling abort  --window-status ready --header-html www.example.com/404  page.html page.pdf`

with page.html:

``` html
<!DOCTYPE html>
<html lang="en">
    <body>
        <script type="text/javascript">window.status = 'ready';</script>
    </body>
    <h>page</h>
</html>
```

Note that no error message is emitted at all.

**Comment by Tomsgu** [comment] 2018-08-20 19:34
Closing as it's a duplicate of #2228.

**Closed by Tomsgu** 2018-08-20 19:34 UTC
Labels: Duplicate
