### ISSUE TITLE
With page-break-inside: avoid enabled, fails to not create inside row page breaks on my file.

### ISSUE THREAD

**Issue by joshjacobson** [wkhtmltopdf/wkhtmltopdf#3059] opened 2016-08-02 18:55 UTC
Example of the problem:

Using PDFKit w/ Python:

```
import pdfkit
options = {
    'user-style-sheet': 'htmltopdf.css'
}

file_p = myfile.html
pdfkit.from_file(file_p, file_p[:-5] + '.pdf', options=options)
```

CSS, htmltopdf.css:

```
<style type="text/css">
tr { 
    page-break-inside: avoid !important;
}

thead, tfoot { 
    display: table-row-group 
}
</style>
```

I've attached the file I'm attempting to work with in which problems occur at page breaks (replace extension w/ .html). page-break-before: always; fails as well, and assigning these to td instead of tr does not solve it either.

[D - Yadgir_July.txt](https://github.com/pdfkit/pdfkit/files/397514/D.-.Yadgir_July.txt)

**Comment by sneakernets** [comment] 2016-08-22 21:20
I was about to report this when I noticed it was already an issue. I wonder when this popped up because it was working swimmingly before a certain date, and I got reports that tables were being chewed up.

**Comment by concepta-thiago** [comment] 2016-09-16 19:56
It was working on version 0.12.2.3 but now its doesnt seems to work in version 0.13.0-alpha
does anyone knows any workaround to fix this?

**Comment by Tomsgu** [comment] 2018-06-20 07:41
Duplicate of #2141. https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2141#issuecomment-95874671

**Closed** 2018-06-21 07:09 UTC
Labels: Duplicate
