### ISSUE TITLE
Google Noto Fonts Not Rendering Properly

### ISSUE THREAD

**Issue by stania1** [wkhtmltopdf/wkhtmltopdf#2693] opened 2015-12-01 03:48 UTC
Hi,

I need to generate PDFs in multiple languages, but for some reason, some fonts render correctly in HTML (viewed on e.g. Chrome), but not on the PDF. One such font is Google Noto Sinhala. 

We're using wkhtmltopdf via WickedPDF (I've posted the same issue there). The font is base64-encoded in the CSS.

Here's our setup:

```
@font-face {
    font-family: "Noto Sans Sinhala";
    src: url(<%= asset_data_uri 'NotoSansSinhala-Regular.ttf' %>) format("truetype");
    font-weight: normal;
}

body.si & {
    font-family: 'Noto Sans Sinhala';
}
```

Here's how it looks in Chrome:

![image](https://cloud.githubusercontent.com/assets/1446811/11491877/ed917336-9820-11e5-81c5-392af866a41c.png)

In the PDF, it doesn't look like it's using the right font at all:

![image](https://cloud.githubusercontent.com/assets/1446811/11491885/fbfd9864-9820-11e5-8988-a9696f698944.png)

I'm using wkhtmltopdf version 0.9.9.

Has anyone seen this issue? Any pointers?

Thanks!

**Comment by natonischuk** [comment] 2016-06-13 06:18
hi, did U found solution?

**Comment by Manoj51** [comment] 2016-11-29 11:09
@stania1 @natonischuk I am also facing a similar issue. Did you figure out the issue?

**Comment by PhilterPaper** [comment] 2016-11-29 14:10
I don't know Sinhalese (or its alphabet), but looking at the two examples, the only difference (other than minor stylistic differences in the typefaces) is that two characters in the second have failed to combine properly. They are on either side of the second black block. I recall seeing a number of reports of such problems (characters not properly combining in various Indic scripts) -- you might want to do some searching for those reports.

**Comment by ashkulz** [comment] 2016-11-30 14:47
Looks like a duplicate of #2764. Can someone report back if it works with `0.13`?

**Closed by ashkulz** 2016-11-30 14:47 UTC

**Comment by Manoj51** [comment] 2016-12-01 08:59
@ashkulz I tried with 0.13, it is still not working. In versions below 0.11 this issue was not there.
If you could point me to where the problem might be it would be great. I would like to take a look at it.

**Comment by ashkulz** [comment] 2016-12-02 06:56
Most likely the font rendering changed in either Qt or WebKit, so can't really help you there.
