### ISSUE TITLE
Everything looks tiny on the PDF

### ISSUE THREAD

**Issue by nicktc** [wkhtmltopdf/wkhtmltopdf#3266] opened 2017-01-02 15:33 UTC
Hi,

I have a mac with wkhtmltopdf 0.12.4 installed. If I run:

`wkhtmltopdf http://www.google.com google.pdf`

It generates a PDF with really small content, as if the PDF page size is huge. I also have this when passing it some simple HTML. I need a font-size of 200 pixels (!) to make the text readeable. Looks like the PDF canvas is huge. When I set the page-size to 'A4' (which is the default?) I still have the same problem. Also disabling shrinking doesn't help. See attachment.

Thanks,

Nick
[google.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/680986/google.pdf)

**Comment by nicktc** [comment] 2017-01-02 19:55
I just installed a slightly older version, this one doesn't have the same problem.

`http://download.gna.org/wkhtmltopdf/0.12/0.12.3/wkhtmltox-0.12.3_osx-cocoa-x86-64.pkg`

See attachment with result.
[google.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/681323/google.pdf)

**Comment by ashkulz** [comment] 2017-01-03 05:17
Hi, it's a known issue (duplicate of #3241).

**Closed by ashkulz** 2017-01-03 05:17 UTC

**Comment by nchodelski** [comment] 2017-10-10 17:26
I have been able to fix this issue using the latest version of the library (in PHP, with the library installed using Composer).

Initially I was not able to get the PDF to render the appropriate size (but copying and opening up the intermediate HTML showed it filling the whole page as expected.). My whole document was rendering much smaller than the page.

When i passed the '--dpi' optio with a value of 300 during PDF creation, the size and layout both rendered correctly in the PDF.

 I only needed to pass the dpi flag to address this issue. i did not try passing '--disable-smart-shrinking', though on other issues in this project, people have successfully used that flag to fix too-small rendering PDFs as well.
—

**Comment by Joebayld** [comment] 2017-10-18 08:07
I tried the above suggestion of setting the DPI, but this still isn't correct. I'm comparing the rendered PDF to me clicking print from the html in a browser. wkhtmltopdf still has sizing off. Is there a magic number that makes this work correct? I'm on a Mac, but will need to build on a Linux server.

**Comment by jeremymoritz** [comment] 2020-09-26 18:53
For me, running wkhtmltopdf 12.6.0 on NodeJS 12.10 Lambda, the only thing i needed to do to make it continue to behave as before was `--disable-smart-shrinking`.  Thank you @nchodelski for mentioning this in your post!

**Comment by betzabeth14** [comment] 2021-01-04 23:02
I´m working in C# and the answer's @jeremymoritz  solved my problem. Thanks a lot. This is my chunk code
 var objectSettings = new ObjectSettings {
                PagesCount = true,
                HtmlContent = htmlContent,
                WebSettings = { DefaultEncoding = "utf-8", EnableIntelligentShrinking = false, }, };

**Comment by vjt** [comment] 2021-06-22 14:55
The `--disable-smart-shrinking` option also helped for my use case, but I had to further tweak the `--dpi` option and I settled to `120` to have a 1:1 correspondence between the font sizes in HTML and the ones yielded in PDF. I'm using version `0.12.6`.

Cheers!
