### ISSUE TITLE
QPaintDevice: Cannot destroy paint device that is being painted when files header-html or missing in --footer-html 

### ISSUE THREAD

**Issue by hamacker** [wkhtmltopdf/wkhtmltopdf#2033] opened 2014-11-05 16:22 UTC
wkhtmltopdf Version: wkhtmltox-0.12.2-dev-200b9a6_msvc2013-win32
Operating System and Version: Microsoft Windows 7 [version 6.1.7601]
When I try:

wkhtmltopdf.exe  --no-collate --title "Fechamento de proposta"  --page-size A4 --margin-bottom 5 --margin-left 5 --margin-right 5 --margin-top 3 --footer-spacing 5 --footer-font-size 8 --header-line --header-html cabecalho.html --footer-line --footer-html rodape.html --footer-line  --footer-left "Fechamento de proposta" --footer-right "fqpve007-rev01 - Página [page] de [topage]" --print-media-type  --background  "c:\temp\proposta-fechamento-49290.htm" "c:\temp\proposta-fechamento-49290.pdf"

But forget to put/create cabecalho.html or rodape.html, appear error message:
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Error: Failed loading page http://rodape.html?page=1&section=Relat¾rio de fecham
ento de proposta&sitepage=1&title=EmissÒo de guia de fechamento de proposta&subs
ection=&frompage=1&subsubsection=&isodate=2014-11-05&topage=1&doctitle=Fechament
o de proposta&sitepages=1&webpage=c:\temp\proposta-fechamento-49290.htm&time=14:
03:52&date=05/11/2014 (sometimes it will work just to ignore this error with --l
oad-error-handling ignore)
QPaintDevice: Cannot destroy paint device that is being painted

And crash my application (Delphi XE5).
Ok, I need to veify files before inside my app, but will be better check files missing inside wkhtmltopdf before processing, if does not exists then exit with os error 2 .

Thanks for great job with wkhtmltopdf.

**Comment by alloylab** [comment] 2018-06-15 13:52
have you tried this on 0.12.5?

**Comment by CaffeineDreams** [comment] 2018-06-20 15:19
We ran into this problem too. I just updated to 12.5 to see if it fixes it but unfortunately not.

The only difference between the versions is that in 12.2, the error reads: `Error: Failed loading page <URL with custom parameters of our PDF header> (sometimes it will work just to ignore this error with --load-error-handling ignore) QPaintDevice: Cannot destroy paint device that is being painted` and in 12.5 it reads simply `QPaintDevice: Cannot destroy paint device that is being painted`.

We construct our custom switches like so:

```
var customSwitches = "--no-stop-slow-scripts --enable-javascript --debug-javascript ";
if (!string.IsNullOrEmpty(FooterUrl))
	customSwitches += $"--footer-html {FooterUrl}&requestedAction={Constants.AllowedLocalActions.PdfLayoutKey} --footer-spacing 0 -B 20mm ";

if (!string.IsNullOrEmpty(HeaderUrl))
	customSwitches += $"--header-html {HeaderUrl}&requestedAction={Constants.AllowedLocalActions.PdfLayoutKey} --header-spacing 5 -T {model.HeaderHeight}mm ";

if (reportPageNumber.HasValue)
	customSwitches += $"--page-offset {reportPageNumber.Value} --viewport-size 1131x800";
```
This was working for us deployed on Azure in a VM but seems to have stopped when we switched to PAAS.

Also this is using the Rotativa wrapper.

We'll continue to look into this and if I find anything I'll update here.

**Comment by alloylab** [comment] 2018-06-20 15:46
@CaffeineDreams does it work without the wrapper?

**Comment by CaffeineDreams** [comment] 2018-06-25 08:52
I replicated the commands that rotativa was generating and ran them on our PaaS environments and got the same error. We were convinced for a time that it was to do with how wkhtmltopdf was constructing query strings but we were way off - the PaaS environments had some extra config that had ip restrictions which blocked the loopback requests to render our header and footer html.

So I'm afraid this probably doesn't help OP, but at least I can confirm that this is how wkhtmltopdf behaves when it encounters a 403 response when getting the header/footer.

**Comment by Tomsgu** [comment] 2018-08-22 14:42
Closing as there is no feedback from the author. Please feel free to re-open this issue if there are more information about this issue.

**Closed by Tomsgu** 2018-08-22 14:42 UTC
Labels: NeedInfo

**Comment by sumitkumar-qai** [comment] 2019-02-05 15:44
I am seeing this error while generating a larger pdf( with lot of pages). below is error:
Error: Failed loading page file:////var/folders/62/glyy8h_d2sz523bynlcqjnsh0000gp/T/wicked_footer_pdf20190205-15895-rv2ilm.html?page=805&section=Systems of Linear and Quadratic Equations&sitepage=805&title=Penn Foster&subsection=Application Problems&frompage=1&subsubsection=&isodate=2019-02-05&topage=820&doctitle=Penn Foster&sitepages=820&webpage=file:////var/folders/62/glyy8h_d2sz523bynlcqjnsh0000gp/T/wicked_pdf20190205-15895-1h6bbot.html&time=9:05 PM&date=05/02/19 (sometimes it will work just to ignore this error with --load-error-handling ignore)

does this related to content?

**Comment by lesliev** [comment] 2019-11-27 21:36
We had this problem on wkhtmltopdf 0.12.3 after upgrading from Ubuntu 14 to Ubuntu 18.04:

```
Error: Failed loading page https://monty.solutionsandservices.co.nz/reports/generic_report_footer?page=1&section=&sitepage=1&title=&subsection=&frompage=1&subsubsection=&isodate=2019-11-27&topage=1&doctitle=&sitepages=1&webpage=-&time=7:48 PM&date=11/27/19 (sometimes it will work just to ignore this error with --load-error-handling ignore)
QPaintDevice: Cannot destroy paint device that is being painted
Segmentation fault (core dumped)
```
The command was:
```/usr/bin/wkhtmltopdf --page-size A4 --print-media-type --orientation PORTRAIT --margin-bottom 10mm --debug-javascript --header-left Papamoa\ College --header-right Period\ ending:\ 31-October-2019 --header-font-size 7 --header-spacing 3 --footer-html https://our-server.co.nz/reports/generic_report_footer - -```

Removing the footer made the PDF generate, but all styles were missing.

Upgrading to wkhtmltopdf 0.12.4 (static builds) had the same problem. 
Upgrading to 0.12.5 (deb) fixed both issues.

**Comment by glautrou** [comment] 2020-01-09 08:04
I had the same issue, the reason was because the footer URL returned 404 when called from local server. Fixing the server DNS problem solved my problem.

**Comment by Markuzy** [comment] 2020-03-26 09:46
We have resolved this issue on our environment.
Will post here to see if it helps.

The application will crash on large number of pages generated.
We use DinkToPDF as wrapper over wkhtmltopdf.

We encountered this issue in docker environment, but not on IIS.
This lead us to investigate linux side limitations.

We found that this was related to a ulimit value for nofile.
Since we deploy via fargate onto AWS, we checked [AWS task definition guide](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_limits) and found that
> The default nofile soft limit is 1024 and hard limit is 4096 for Fargate tasks.

We updated task definition to include this section
```
"ulimits": [
        {
          "name": "nofile",
          "softLimit": 1048576,
          "hardLimit": 1048576
        }
      ],
```

This resolved the issue for us.
How high to set the limit, we found, is dependent on application load.
We found that this limit is not per request, but across the application load at the same time.
If there are many pdf generation requests, we will have to increase the limits, or scale up the containers.

**Comment by lesliev** [comment] 2020-04-13 21:55
THANK YOU! This solved some very long-standing problems for us!

**Comment by lacostenycoder** [comment] 2020-07-27 15:23
@Markuzy does anyone know how to set ulimts in AWS Lambda ?

**Comment by Markuzy** [comment] 2022-10-17 04:25
@lacostenycoder  hope you have found some solution as it has been 2 years hah as it is an interesting prospect. Were you intending to do pdf generation in a Lambda function?

For what I know, it is not very clear whether it is possible according to current Lambda docs:
https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html 

If you search for the term "File descriptors" in the above link,
you will find that there is a 1024 limit that is not changeable.

If someone with AWS Premium/Enterprise support can escalate to clarify, it will be good.

Otherwise, my approach around this is to use AWS Lambda to run an ECS task ad-hoc, and then have the ECS task self-terminate after completion of work. This has some slowness of around 30 seconds for a task to start up, so it may not be what you require.
Another reason for not using Lambda is because in some scenarios, your report may beyond the Lambda 15 min hard cap to generate and will fail as a result.
