### ISSUE TITLE
Gtk-WARNING

### ISSUE THREAD

**Issue by mickaelCOLLET** [wkhtmltopdf/wkhtmltopdf#3113] opened 2016-09-09 08:24 UTC
Hello,
i have this error and i don't know how to solve it.
can u help me ?
thank

```
/usr/local/bin/wkhtmltoimage --format 'jpg' --javascript-delay '1000' --enable-plugins --no-stop-slow-scripts 'google.fr' '/tmp/knp_snappy57d26ec794e020.73081651.jpg'
Loading page (1/2)
QFont::setPixelSize: Pixel size <= 0 (0)                     ] 45%

(wkhtmltoimage:48990): Gtk-WARNING **: cannot open display:
```

**Comment by PhilterPaper** [comment] 2016-09-09 13:23
Not a whole lot to go on here. wkHTMLtoPDF version? Operating system? Versions of various installed systems?

There is an error message that something is trying to set a 0 (or even negative) pixel size. Does this HTML and CSS display correctly in a browser? Can you narrow down the HTML to what's causing the problem? Is something setting a negative or zero font-size, negative or zero image dimension, etc.? That might be the source of the "cannot open display" error.

Some browser engines might accept a 0 size for something, to mean "give me the smallest you can", but other engines (such as WebKit) might literally try to use a zero size.

**Comment by mickaelCOLLET** [comment] 2016-09-09 13:50
I use wkhtmltoimage 0.12.3 with patched qt on debian Jessie.
what is the best issue ? parse and modify html before capture ?

**Comment by PhilterPaper** [comment] 2016-09-09 19:33
Chop away at the HTML and CSS until you get a nice, small document that shows the problem. Remove anything confidential so you could attach the files here and let others experiment with it. In the process, see if the HTML and CSS are doing something fishy, such as specifying invalid dimensions or something. It might not even cause a problem in a browser.

**Comment by mickaelCOLLET** [comment] 2016-09-12 09:49
Thank for ur reply. I have a strange example : 

This work : 

> wkhtmltoimage --format 'jpg' --javascript-delay '3000' --load-media-error-handling 'ignore' --no-stop-slow-scripts 'leboncoin.fr' 'test.jpg'

This failed : 

> wkhtmltoimage --format 'jpg' --javascript-delay '3000' --load-media-error-handling 'ignore' --enable-plugins --no-stop-slow-scripts 'leboncoin.fr' 'test.jpg'

Failed apparear when i use option '--enable-plugins' : 

```
QFont::setPixelSize: Pixel size <= 0 (0)

(wkhtmltoimage:46104): Gtk-WARNING **: cannot open display: 
"
```

Any idea ?

**Comment by PhilterPaper** [comment] 2016-09-12 14:50
I have no experience with plugins -- I don't know if they are part of your _browser_ or of the wkHTML* _program_ itself. That said, do you have any idea what "plugins" you are using? Maybe one of them is returning bad data, if you can figure out which one. The first thing would be to update all your plugins to the current version. If that doesn't fix the problem, try disabling (or deleting) one at a time until you find the offender. At that point, I assume that you'd have to report a bug and get the plugin fixed, because it's probably in use by some part of the HTML document.

**Comment by Tomsgu** [comment] 2018-09-25 20:38
Closing as the issue misses a minimal html example to reproduce it.

**Closed by Tomsgu** 2018-09-25 20:38 UTC
Labels: NeedInfo
