### ISSUE TITLE
v0.12.5 - Windows 10 x64 - Can't create ToC.

### ISSUE THREAD

**Issue by arieradle** [wkhtmltopdf/wkhtmltopdf#3993] opened 2018-07-04 11:07 UTC
v0.12.5 - Windows 10 x64 - EXE installer

Can't create ToC.

Not observed in v0.12.4

**Comment by Tomsgu** [comment] 2018-07-04 12:01
Can you provide a minimal example and command you're running? 
What is the exact issue?

**Comment by arieradle** [comment] 2018-07-04 12:20
The command line is `wkhtmltopdf toc test.html test.pdf`

Take any HTML example with that contains <h?> elements

**Comment by alloylab** [comment] 2018-07-05 17:46
@arieradle can you attached the test.html file?

**Comment by Tomsgu** [comment] 2018-07-09 07:17
Duplicate of #3953, please use the dev build until there is final release of 0.12.6

**Closed by Tomsgu** 2018-07-09 07:17 UTC
Labels: Duplicate

**Comment by ashkulz** [comment] 2020-06-07 08:27
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
