### ISSUE TITLE
Forms not fillable

### ISSUE THREAD

**Issue by ErnstTmp** [wkhtmltopdf/wkhtmltopdf#3280] opened 2017-01-11 13:07 UTC
Hello,
thanks for creating this great tool!!!

I used an old version of wkhtmltopdf (0.10 Rc1, on ubuntu 12.04) to transform HTML forms into PDF forms that can be filled. That works. Now, I want to switch to 0.12.4. Everything else works, but the form fields are read only now. What can I do? I use
` --enable-forms  --encoding UTF-8.`

Fields look like this:
`<td>Date:</td><td><input id="text4" name="text4" size="38" type="text"></td>`

Thanks,
Ernst

**Comment by zavagli** [comment] 2017-07-08 18:07
Hi Ernst,

I have the same problem with Acrobat Reader, but not with Osx Preview, do you have the same?

**Comment by VagelisProkopiou** [comment] 2017-08-31 06:26
Very similar problem here (Windows OS).

The following form elements are not editable in Adobe Reader/Acrobat (editable in Chrome, version 60.0.3112.113).

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form id="form1" name="form1">
        <input type="text" id="t1" name="t1" value="t1">
        <textarea name="t2" id="" cols="30" rows="10"></textarea>
    </form>
</body>
</html>`

wkhtmltopdf version: `0.12.5-dev-b3ca2e3 (with patched qt)`
Adobe Reader version: `11.0.06`

**Comment by richardrails** [comment] 2018-07-26 13:35
any solution here?

**Comment by Tomsgu** [comment] 2018-08-08 09:59
Duplicate of #3025.

**Closed by Tomsgu** 2018-08-08 09:59 UTC
Labels: NeedInfo
