### ISSUE TITLE
Big white space before nested table

### ISSUE THREAD

**Issue by subhimarabeh** [wkhtmltopdf/wkhtmltopdf#2098] opened 2014-12-11 13:36 UTC
Hi All,
i am facing a problem when i am trying to convert html to pdf with nested table, a large white space appeared before the nested table, i read all issues posted here before nad nothing worked for me, 
my html file http://en.file-upload.net/download-9983610/temp.html.html, 
my resulted pdf http://en.file-upload.net/download-9983634/Quote__20141020-002._-LHR-_London__GB_-__-DFW-_Dallas-Fort_Worth__US--21-.pdf.html
ps: i am using the lastest version of the library
please help me, any help would be much appreciated thanks

**Comment by faustow** [comment] 2015-04-02 12:51
hi subhimarabeh, did you ever solve this? I've been having similar issues so your solution might apply to me as well? Thanks in advance!

**Comment by ashkulz** [comment] 2015-04-05 14:58
@faustow: posting the **minimal** HTML/CSS inline would be help in investigating this further.

**Comment by faustow** [comment] 2015-04-06 21:40
The version of wkhtmltopdf I was using when answering to the bug report is v0.12.1 with patched qt. The problem is that it sometimes shows big whitespaces inside tables for apparently no reason. I have tried to detect this whitespace with js to try and remove it, but it doesn't seem to be there as far as javascript knows.

Now I've downloaded each version of wkhtmltopdf and compiled the same report against each of them so you can see the differences.
Short version is: 
* v0.13.0-alpha-4046a03 doesn't have headers on any page (probably because it lacks the patched qt) and the table contents were kind of messed up
* v0.12.2.1 doesn't show the problem with the whitespace in the table but the page header is only shown in the first page
* v0.12.2 doesn't show the problem with the whitespace in the table but the page header is only shown in the first page
* v0.12.1 (the version I always use) is the one with the whitespace problem

The HTML used is the following:
```html
<div id="client-non-compliant-player-list">
    <table>
        <th>THIS IS THE TITLE</th>
    </table>
    <br>
    <table id="clients">
        <tr data-before-template='data-before-template'>
            <th class="client-column">CLIENT</th>
            <th class="team-column-header">TEAM</th>
            <th class="id-column">PLAYER ID</th>
            <th class="description-column">DESCRIPTION</th>
            <th class="inspection-column">INSPECTION</th>
            <th class="schedule-column">SCHEDULE</th>
        </tr>
        <tr data-template='data-template'>
            <td class="client-column">{{name}}</td>
            <td colspan="5">
                <table class="no-border">
                    <tr data-template-for='teams'>
                        <td class="team-column no-border">{{team_name}}</td>
                        <td class="no-border">
                            <table class='player-table no-border' >
                                <tr data-template-for="players" >
                                    <td class="id-column no-border">{{player_name}}</td>
                                    <td class="description-column no-border">{{player_description}}</td>
                                    <td class="inspection-column no-border">{{player_inspection}}</td>
                                    <td class="schedule-column no-border">{{player_schedule}}</td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
```
I have removed the css so this post isn't that long. The {{...}}-labels are for tempojs.

I guess if only I could make v0.12.2.1 have page headers in every page then this problem wouldn't need to be solved/ Do you have any ideas?

**Comment by ashkulz** [comment] 2015-04-07 12:08
What do you mean by a page header? Do you mean "THIS IS A TITLE"? There is no support for repeating arbitrary HTML as a page header in WebKit. Closing this as your original issue seems to be solved with the latest version.

**Closed by ashkulz** 2015-04-07 12:08 UTC
Labels: NeedInfo

**Comment by faustow** [comment] 2015-04-07 12:59
No, I mean header like in --header-html. I've opened #2284 for this.
