### ISSUE TITLE
Font Sizes

### ISSUE THREAD

**Issue by habiem** [wkhtmltopdf/wkhtmltopdf#3367] opened 2017-03-03 16:30 UTC
I saw a report of font sizes being drastically different on OS X, but I'm also seeing this on Linux. There is a huge difference between 0.12.3 and 0.12.4. Fonts appear significantly smaller.

Please let me know if there's anything you need in order to track it down.

Thank you!

**Comment by OpenESignForms** [comment] 2017-03-07 20:20
We have noted this as well.  We used to use a 'print css' to reduce fonts to 80%:

@media print { 
	body.esf { margin: 0; padding: 0; font-size: 80% !important; }
}

But we oddly noticed that 100% was even slightly bigger appearing that if that font-size spec was removed entirely (which seemed odd as you'd think removing it and 100% would be the same).  This makes life hard because the HTML docs are created with styles to make it work nicely with wkhtmltopdf, but then the converter changes how it works so if we change now to remove the CSS, new HTML documents will have it and render ok, but prior HTML will be really small (as they still have the 80% reduction defined inside them).

Does 0.12.4 have a mode/command-line-switch that is more like 0.12.3 in this regard?

**Comment by khkremer** [comment] 2017-03-12 17:24
Take a look here for a discussion #3241

**Comment by Jmuccigr** [comment] 2017-03-19 17:16
Another dupe of #3241 to be closed, no?

**Comment by OpenESignForms** [comment] 2017-03-19 17:27
We found we can use 0.12.4 with --disable-smart-shrinking added.  This is still a bit different from 0.12.3, but is very close and I have no reason to prefer the prior version's layout.  So for us, this is not an issue anymore.  Thanks!

**Closed** 2017-03-20 01:53 UTC
