### ISSUE TITLE
Images are not rendering properly

### ISSUE THREAD

**Issue by chethan-K** [wkhtmltopdf/wkhtmltopdf#2834] opened 2016-03-15 10:19 UTC
Images are not rendering properly in pdf.

After pdf creation : 
In pdf viewer, I don't see the image at all.
In chrome, Image is stretched. 
In firefox, pdf looks cool.
Please suggest . 
[sample.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/173649/sample.pdf)
![sample](https://cloud.githubusercontent.com/assets/2725235/13774495/5dee3816-eac5-11e5-9881-45b5a7c4de6d.jpg)

**Comment by PhilterPaper** [comment] 2016-03-15 13:14
Show us the HTML and CSS used to create the page and PDF. What commands were used to create the PDF? Any messages?

**Comment by chethan-K** [comment] 2016-03-15 14:56
Hi PhilterPaper,
Thanks for the response. 

I am using basic HTML layout for this pdf. 
<html><head></head>
   <body><h1>Test1</h1>
     <img src="path/to/image">
   </body>
</html>


Command on ubuntu :  wkhtmltopdf test.html sample.pdf
I didn't see any error logs.
If you open the above pdf in firefox browser, you can actually see the image. But It won't make it in previewer. This happens only for set of images.

**Comment by PhilterPaper** [comment] 2016-03-16 00:06
What does the image path look like? Is it an http: URL, an absolute path (starts with /) or relative path? There are problems if you use an absolute path... wkHTMLtoPDF will be looking in the wrong place. There have been a number of discussions about this.

**Comment by chethan-K** [comment] 2016-03-16 03:51
Image path is URL. For the same html, If i use different set of images, It works good. 

I suppose, the issue is with image. I don't know what is wrong with this image. 
Is there any limitation or assumption in using image formats.

**Comment by PhilterPaper** [comment] 2016-03-16 15:11
Is this a JPEG, like your example? I haven't heard of any limitations, but then I'm not an expert in the field. I think I've heard of some browsers having trouble with JPEGs which use CMYK color models (rather than RGB) -- you might see if that's the difference between those images which work and those  that don't work. Maybe WebKit falls into the "CMYK doesn't work" category.

**Comment by chethan-K** [comment] 2016-03-16 15:14
Thanks.
Yes!! Seems to be CMYK color model issue. 
I tried hard to pull this image into pdf. Did not worked for me.
https://github.com/KnpLabs/KnpSnappyBundle/issues/47

Now decided to convert CMYK to RGB image.

**Comment by Tomsgu** [comment] 2018-09-05 11:39
Closing as duplicate of https://github.com/wkhtmltopdf/wkhtmltopdf/issues/39.

**Closed by Tomsgu** 2018-09-05 11:39 UTC
Labels: NeedInfo
