### ISSUE TITLE
empty pdf

### ISSUE THREAD

**Issue by qwer1304** [wkhtmltopdf/wkhtmltopdf#2540] opened 2015-08-23 05:52 UTC
wkhtmltopdf 0.12.2.4 (with patched qt)
Win XP SP3 32b
http://www-labs.iro.umontreal.ca/~bengioy/dlbook/manifolds.html

The command: 
wkhtmltopdf http://www-labs.iro.umontreal.ca/~bengioy/dlbook manifolds.pdf
returns an empty pdf

Printing from Chrome Version 46.0.2490.0 canary is fine

**Comment by PhilterPaper** [comment] 2015-08-23 13:33
What is **\wkhtmltopdf"** in the command line supposed to do? That unmatched " looks odd to me.

**Comment by qwer1304** [comment] 2015-08-23 13:35
Sorry - copy paste error. I fixed the command line in the ticket. The problem persists.

**Comment by PhilterPaper** [comment] 2015-08-23 14:00
What exactly is the format this HTML input is in? It is already paginated in some way, and images are inlined (no external image files). It looks like someone took a PDF (or maybe some other publishing format) and converted it to HTML so it would show up as a web page. I wouldn't be terribly surprised if WebKit chokes on this sort of thing.

I tried converting it on the same kind of system as yours, and got "Failed loading page" and "Unknown network error" messages.

**Comment by qwer1304** [comment] 2015-08-23 14:09
Go here http://www-labs.iro.umontreal.ca/~bengioy/dlbook/
There's an explanation to what the files are and why they are doing this.
Then there are links to pages in this format.
I can open the files w/o any issue in Chrome and print them as pdf therefrom.

**Comment by PhilterPaper** [comment] 2015-08-23 15:52
OK, it is a PDF conversion to HTML "as a weak DRM" to discourage high quality reproduction of a draft book-in-progress. A number of browsers (at least, Chrome), can print a web page in PDF, but don't expect it to be as good as the original PDF. 

Possibly the first place to look, to get wkhtmltopdf to accept it, would be to pull out the base64-encoded images and replace them with .png files (in a local copy). If that doesn't work, someone knowledgeable about WebKit will have to go through and look at the HTML and see what WK might not be liking.

By the way, you should make sure you're not violating any license or terms & conditions of this ebook by turning it into a PDF. If all you want to do is print it for personal use, why not print it directly from the web page? If you want to save a copy as an ebook, can you save the HTML version and use a browser to read the file? The only downside would be that an ereader (Nook, Kindle, etc.) might not handle that. Anyway, just some ethical/legal matters to consider.

**Comment by vepashka** [comment] 2015-08-25 05:54
Hello, having the same problem with the following url: http://jobview.monster.com/Senior-Software-Engineer-Job-Seattle-WA-US-154669171.aspx?mescoid=1500127001001&jobPosition=1 anyone has any ideas? Application will generate empty pdf and gets stuck there. Thanks

**Comment by PhilterPaper** [comment] 2015-08-25 13:50
I tried the monster.com conversion, and it *did* produce a file with PDF-looking content, but Adobe Reader shows only a blank page. Possibly, incorrectly formatted PDF was produced. pdftk was able to uncompress the file, but that couldn't display, either. wkhtmltopdf, after "Done", gave "Exit with code 1 due to network error: UnknownContentError". Also, my anti-spyware and firewall hung up the "Loading Pages" phase a few times, but it did get through there.

**Comment by vepashka** [comment] 2015-08-25 14:28
Hello, thank you for your reply and time. So any ideas how I can overcome this? I tried same domain on multiple other services both paid and free and seems like all of them fail to work on this domain. When converting I tried different options, such as disabling js, images etc none of them seem to help. Though disabling js did made the blank file generation faster, maybe that rings a bell. Anyway I am out of ideas, any help is greatly appreciated.

**Comment by PhilterPaper** [comment] 2015-08-27 15:06
The most obvious thing I can think of at the moment is that monster.com is doing something to block what appears (to it) to be site scrapers. That could explain why other converters failed too on this monster.com page. However, when I tried it, it *did* seem to read the page (and produce some output), although it apparently produced invalid PDF and/or couldn't completely read the page. I haven't looked through the innards of the source page yet, except to note that there's a huge amount of JS and CSS, both inline and in files... might there be something there hanging up the read by requiring some response? That, or it took several seconds to complete loading, so maybe something on the wkhtmltopdf end timed out. It might be worthwhile to copy the page source and files to your PC and see if it converts successfully. If it does, it must be a timeout issue. If not, you can remove pieces one by one and see if you can find the offending party.

**Comment by vepashka** [comment] 2015-09-04 12:37
Sorry for late reply. Thank you for your effort, I think I found the
problematic piece. Thanks.

**Comment by PhilterPaper** [comment] 2015-09-04 13:10
For the benefit of future readers, could you tell us what you found? Was it something that might require a fix for wkhtmltopdf, or improvement of its documentation, or was it something you did? That information could save others a lot of time tracking down a similar problem.

**Comment by vepashka** [comment] 2015-09-04 13:17
Yes, of course, it was rude of me. Actually to be honest I wasn't able to
solve the problem, but found that there was a particular class that
wkhtmltopdf had problems parsing. Removing it or disabling js resulted in
faster parsing, and did parsed part of the web page but not all. I think
further investigation into this particular js might lead to a solution but
I am not very strong in js or any web related stuff, mostly do desktop
development, so I ended up using MS word .dll's to parse html, which also
had some problems parsing pages from monster.com but did yield much better
results. Sorry that I didn't give any valid solution, but my suggestion to
anyone who is having same issue is to try out different parsing options,
like disabling js, or disabling external links etc. Also pay attention to
error message wkhtmltopdf is giving to you in most cases it will tell what
part of the page it is having problems parsing. Again thank you for your
time.

**Comment by qwer1304** [comment] 2015-10-16 11:06
Update:
The alpha version  0.12.3-dev-79ff51e manages to generate a pdf of this http://goodfeli.github.io/dlbook/contents/ml.html, but it includes ONLY the graphics.
Text sprinkled over the graphics is lost.
You can see this by generating pdf and then looking at places in text where blanks are interspersed.

**Comment by brendandc** [comment] 2016-08-16 18:05
Another possible cause for anybody coming across the empty pdf (or cut off near the start) files: inline `@font-face` tags within one of the style elements that contained raw .woff files. These are auto-generated by pdf2htmlex and I was able to workaround this issue by removing them.

**Comment by Er3VoS** [comment] 2017-02-20 07:35
Getting empty output pdf when the HTML file is generated by pdf2htmlex even after completely removing the $font-face tags. Anyone that has come across the same issue and can offer any ideas?
Thanks in advance :)

**Comment by freedonaab** [comment] 2017-03-28 11:24
Hi ! pdf2htmlex emits an output HTML with two styles: one with `@media screen` and `@media print`. This allow the produced html to look nice when you load it as a regular page **and** as a pdf (I think that's the reason).
By default wkhtmltopdf (0.12+) does not use  `@media print` but uses `@media screen`. This does not seems to work with html generated with pdf2htmlex. Setting the `--print-media-type` option (it makes it use  `@media print`) for wkhtmltopdf resolved the issue for me.

Hope it can help you too !

**Comment by PhilterPaper** [comment] 2017-03-28 12:51
Um, why are we discussing pdf2htmlex? It's a completely different and unrelated product, going the opposite direction of wkHTMLtoPDF.

**Comment by Tomsgu** [comment] 2018-08-20 19:17
Closing as the author already "fixed" the issue and pdf2htmlex is not wkhtmltopdf.

**Closed by Tomsgu** 2018-08-20 19:17 UTC
Labels: NeedInfo

**Comment by JoenyBui** [comment] 2021-04-02 13:23
> Hi ! pdf2htmlex emits an output HTML with two styles: one with `@media screen` and `@media print`. This allow the produced html to look nice when you load it as a regular page **and** as a pdf (I think that's the reason).
> By default wkhtmltopdf (0.12+) does not use `@media print` but uses `@media screen`. This does not seems to work with html generated with pdf2htmlex. Setting the `--print-media-type` option (it makes it use `@media print`) for wkhtmltopdf resolved the issue for me.
> 
> Hope it can help you too !

This solves my problem trying to run this for javadocs.  Much appreciated.
