### ISSUE TITLE
Css styles not applying in pdf 

### ISSUE THREAD

**Issue by Bhavana23** [wkhtmltopdf/wkhtmltopdf#3676] opened 2017-10-06 13:36 UTC
Iam using wkhtmltopdf for rendering react js component in php and in php template, Iam rendering the stylesheet as follows:

 <script type="text/javascript" src="/node_modules/report/build/static/css/main.67472972.css"></script>

But my styles are not being rendered in the pdf.

my css file looks like this:
[main.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1362842/main.txt)

**Comment by NiR-** [comment] 2017-10-08 17:45
I believe you don't have any `node_modules` directory at the root of your filesystem, thus IMO the path to your css file is invalid. `wkhtmltopdf` needs absolute path to your file so you should either use `<base />` tag to provide the base path for other relative paths, or you should use absolute paths whenever you want to load an external css/js/font/image/... file.

I don't really know react but I guess these URL are generated by it, so you need to find a way to trick it to give you the right html code (maybe a seperate build with some specific webpack config/plugins).

**Comment by semsphy** [comment] 2017-10-09 14:36
@NiR- , I had problem as well. It works well with my ubuntu 16.04 version on linode.com. I'm using your php package. 

But When I set up on my local server ubuntu 16.04 server, it seems not apply the style that used to work and doesn't render my embedded fonts.

I have no clue what is the problem yet, do you have any idea?

### Images
![Uploading Screen Shot 2017-10-09 at 9.35.55 PM.png…]()

**Comment by Bhavana23** [comment] 2017-10-10 09:49
I tried with both the options. Base url and absolute path.But could not get the styles loaded. The same styles are applied for the template in php template but not pdf.

<base href="http://abc.com/{project_name}/node_modules/">
<link  rel="stylesheet" type="text/css"  href="build/static/css/main.65cb5b09.css">

**Comment by semsphy** [comment] 2017-10-10 16:08
Finally, I fixed the problem base on this #3001 

### For Ubuntu 14.04:
```bash
apt-get install openssl=1.0.1f-1ubuntu2.22
apt-get install libssl-dev=1.0.1f-1ubuntu2.22
```
### For Ubuntu 16.04:

``` bash
apt-get install libssl1.0.0=1.0.2g-1ubuntu4.8
apt-get install libssl-dev=1.0.2g-1ubuntu4.8
```

**Comment by Tomsgu** [comment] 2018-07-19 13:21
The #3001 is solved so I am closing this as well. It seems to be the same issue.

**Closed by Tomsgu** 2018-07-19 13:21 UTC
Labels: NeedInfo

**Comment by mfisher29** [comment] 2019-12-05 19:41
Confirmed this was resolved by adding **absolute** path of stylesheet :

```
<head>
        <link rel="stylesheet" type="text/css" href="{your absolute path to}/styles.css" media="screen" />
    </head>
```
