### ISSUE TITLE
default font is missing italic glyphs, but renders ok in chromium

### ISSUE THREAD

**Issue by fommil** [wkhtmltopdf/wkhtmltopdf#2972] opened 2016-05-28 18:44 UTC
When I try to render an HTML page containing italic content with all default css styling, then filter through gs to optimise the size

```
gs -q -dNOPAUSE -dBATCH -dPDFSETTINGS=/ebook -sDEVICE=pdfwrite -sOutputFile=out.pdf in.pdf
```

I get warnings about missing glyphs for text such as `<I>key form</I>`.

```
Missing glyph CID=35, glyph=0023 in the font DejaVuSerif-Italic . The output PDF may fail with some viewers
```

I'm pretty sure DejaVu Serif (`wkhtmltopdf`'s default on my machine... I didn't set it with CSS anyway) has these glyphs, or am I mistaken?

I use debian testing and the distro installed version 0.12.3.

**Comment by fommil** [comment] 2016-05-28 18:46
btw, I have also tried using `@font-face` but the resulting PDFs are **huge**, like 1GB for a book.

**Comment by fommil** [comment] 2016-05-28 18:52
I think this is perhaps a `gs` issue, looking at the PDF output from `wkhtmltopdf` I'm able to render it in a PDF viewer.

**Comment by fommil** [comment] 2016-05-28 21:15
oh, by the sounds of http://bugs.ghostscript.com/show_bug.cgi?id=695869 it sounds like this might be a bug in wkhtmltopdf to do with using bad "placeholder" fonts, does that make sense?

**Comment by PhilterPaper** [comment] 2016-05-29 13:40
What does GS have to do with wkHTMLtoPDF? I don't think it uses it. Are you just reporting that it sounds like a similar problem in GS? I suspect that the two use different font files, but I'm not absolutely sure. It sounds more reasonable that a browser and wkHTMLtoPDF would use the same font files, as wkHTMLtoPDF is using the WebKit browser engine to render the page.

So, you're using entirely default CSS (no `<style>` or linked .css files), and `<i>` tags are reporting *some*, but not *all* missing glyphs? Can you narrow it down to specific characters? If "glyph=0023" is a hex code, that would be the # character. It would be odd to be missing a common ASCII character. Make sure the missing glyphs aren't actually for very exotic UTF-8 characters.

**Comment by fommil** [comment] 2016-05-29 19:36
I'm saying that the PDFs that wkhtmltopdf produces are suffering from a similar defect as reported in the gs report. It is gs that picks up on the defect, e.g. when trying to optimise a PDF that has been produced as a combination of multiple wkhtmltopdf PDFs.

I have a script that you can run which exhibits the problem, but I'm nervous about posting it publicly as the author of the website may be annoyed. Is there a way for me to share a secret gist with you?

**Comment by PhilterPaper** [comment] 2016-05-29 22:11
> It is gs that picks up on the defect, e.g. when trying to optimise a PDF that has been produced as a combination of multiple wkhtmltopdf PDFs.

Well, if I understand what you're doing, you use wkHTMLtoPDF to produce multiple PDFs, and then use GS to merge them into one PDF? Or are you merging with some other tools and then using GS to "optimise" it? Do the individual PDFs (before GS) look OK, with nothing apparently missing? If so, the problem is with GS (or whatever tool you're using to merge the PDFs). There are a number of other tools to merge PDFs into one, if you're using GS, You should be able to directly produce a single PDF from multiple input HTMLs with wkHTMLtoPDF, if GS isn't working right. On the other hand, if the individual PDFs are missing glyphs, that would suggest a problem with either your installed fonts or with wkHTMLtoPDF itself. 

That's about as far as I can help you (suggest you verify at what step italic text started losing glyphs).

**Comment by fommil** [comment] 2016-05-30 09:06
hmm, yeah, I was using `pdfunite`. I'll try without merging the files first, yeah maybe **it** has a bug.

**Comment by fommil** [comment] 2016-05-30 09:15
oh, doh! Sorry for the noise. You're right, it looks like `pdfunite` introduced this problem. I didn't realise how easy it was to merge PDFs with `gs` so I'll just use that and delete `pdfunite` from all my machines, forever.

**Comment by fommil** [comment] 2016-05-30 09:30
oh, no, how interesting, if I optimise the PDFs *before* I merge them then the problem goes away!

I've added you to a private repo (just a script and CSS file, plus cache of the website I'm rendering) if you're interested further. I have my workaround so I'm happy to close this if you don't think this is a bug.

Look at page ~304 of the resulting PDF for the title "Setting up and Tearing Down" and see that the "S" is missing in the version produced by merging the direct output of `wkhtmltopdf`

**Comment by PhilterPaper** [comment] 2016-05-30 12:53
It sounds like you've found the problem area and can work around it, so I don't think there's anything more I can contribute on this. If all evidence is that the problem is outside of wkHTMLtoPDF, I would suggest closing this bug report (it will still be available under the Closed Bugs area, for future reference). Best wishes!

**Closed** 2016-05-30 13:06 UTC
