### ISSUE TITLE
Overlapping Text in Thead

### ISSUE THREAD

**Issue by loicdev** [wkhtmltopdf/wkhtmltopdf#2756] opened 2016-01-14 11:32 UTC
Hello i have a probleme when a generate a PDF with big table row.
Example of top of secondary page
![pasted image at 2016_01_13 06_48 pm](https://cloud.githubusercontent.com/assets/6772726/12323269/5a447c92-baba-11e5-94fb-9d6a0879ae75.png)

I have tried to use this CSS tips that i have found in many discussion : 
 tr {page-break-inside: avoid; }

But it does not work when my row is longer than a page..
Please , any help ?

**Comment by llCorvinSll** [comment] 2016-01-18 08:38
I have same problem, and found a little hacky solution

on table apply this class
```
        .m-multipage thead:before {
            display: block;

            width: 1px;
            height: 2px;

            content: '';

            border: none;
            background-color: white;
        }

        .m-multipage {
            position: relative;

            tr {
                page-break-inside: avoid;
            }
        }
```

**Comment by loicdev** [comment] 2016-01-18 09:16
Thanks @llCorvinSll for your answer but that change nothing ..

**Comment by llCorvinSll** [comment] 2016-01-18 10:05
@loicdev can you provide html and css sample of this example?

**Comment by loicdev** [comment] 2016-01-18 10:29
Okey , in css i have bootstrap and your sample : 

```
        .table-invoice-products thead:before {
           display: block;
           width: 1px;
           height: 2px;
           content: '';
           border: none;
           background-color: white;
       }

        .table-invoice-products {
            position: relative;
        }

        .table-invoice-products tr {
            page-break-inside: avoid;
        }
```
my html is generated by a engine templating : twig , the part after the body is : 
```html
         <table class="table table-bordered table-invoice-products col-xs-12">
            <thead>
            <tr>
                <th class="col-xs-7 text-center">
                   Glossary
                </th>
                <th class="col-xs-1 text-center">
                   Quantity
                </th>
                <th class="col-xs-2 text-center">
                    UnitPrice
                </th>
                <th class="col-xs-2 text-center">
                   Untaxed Amount
                </th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="col-xs-7">
                        Sed maximum est in amicitia parem esse inferiori. Saepe enim excellentiae quaedam sunt, qualis erat Scipionis in nostro, ut ita dicam, grege. Numquam se ille Philo, numquam Rupilio
                    </td>
                    <td class="col-xs-1">
                       
                    </td>
                    <td class="col-xs-2 text-right">
                     
                    </td>
                    <td class="col-xs-2 text-right">
                       
                    </td>
                </tr>
            </tbody>
        </table>
```

But the location where i have add lorem ipsum can exceed a page .

**Comment by jieter** [comment] 2016-01-21 11:14
@loicdev thanks for your css snippet, helped me fix my problem. I only needed one rule:
```css
.table tr {
    page-break-inside: avoid;
}
```

**Comment by Awakening-j** [comment] 2016-03-16 07:57
+1, thanks @loicdev

**Comment by jangor** [comment] 2016-06-02 08:35
Did anybody get the "hacky solution" of @llCorvinSll to work?
I keep having the issue:
![issue2756](https://cloud.githubusercontent.com/assets/4834812/15738709/cdc056f4-28ac-11e6-951a-b4e38b637bac.png)

the html is:

    <!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta charset="UTF-8"/>
        <title>Test Table Exceeding Page Boundary</title>
        <style type="text/css">
            table {
                width: 97mm;
            }
            .gray-thead thead {
                background-color: #efefef;
            }
            
            .fix-page-break-bug thead:before {
                display: block;
                width: 1px;
                height: 2px;
                content: '';
                border: none;
                background-color: white;
            }
            .fix-page-break-bug {
                position: relative;
                tr {
                    page-break-inside: avoid;
                }
            }
            
            .a-block {
                display: block;
                width: 10px;
                height: 290mm;
                context: '';
                border: none;
                background-color: light-gray;
            }
        </style>
    </head>
    <body>
        <h1>Test Table Exceeding Page Boundary</h1>
        <p class="a-block"/>
        <table class="fix-page-break-bug gray-thead">
            <thead>
                <tr><th>Row number</th><th>Heading</th></tr>
            </thead>
            <tbody>
                <tr><td>1</td><td>Value</td></tr>
                <tr><td>2</td><td>Value</td></tr>
                <tr><td>3</td><td>Value</td></tr>
                <tr><td>4</td><td>Value</td></tr>
                <tr><td>5 The quick brown fox jumps over the lazy dog</td><td>The quick brown fox jumps over the lazy dog</td></tr>
                <tr><td>6 The quick brown fox jumps over the lazy dog</td><td>The quick brown fox jumps over the lazy dog</td></tr>
                <tr><td>7</td><td>Value</td></tr>
            </tbody>
        </table>
    </body>
    </html>

*I used the windows version 0.12.3.2 (with patched qt)*

**Comment by symars974** [comment] 2017-02-06 18:49
Hello!
I'm facing the same problem, and the above solutions are not working for me.
I'm using wkhtmltopdf version 0.12.4, and the code is:

<html>
<head>

<style>

	  .m-multipage thead:before {
            display: block;

            width: 1px;
            height: 2px;

            content: '';

            border: none;
            background-color: white;
        }

        .m-multipage {
            position: relative;

            tr {
                page-break-inside: avoid;
            }
        }

</style>

</head>
<body>

	 <table class="m-multipage">
            <thead>
				<tr>
					<th class="text-center">
					   Glossary
					</th>
					<th class="text-center">
					   Quantity
					</th>
					<th class="text-center">
						UnitPrice
					</th>
					<th class="text-center">
					   Untaxed Amount
					</th>
				</tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                      PUT 400 lines here
                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                </tr>
            </tbody>
        </table>
					
</body>
</html>

The result: 

![image](https://cloud.githubusercontent.com/assets/25593045/22661312/60b48a90-ecbe-11e6-8ba6-1c3b7413f9d5.png)


Thanks a lot in advance for any help!

**Comment by montao** [comment] 2017-10-23 01:17
What worked for me was removing all CSS and incrementally adding only the CSS needed. Now our table renders nicely over several pages both with proper pagebreak and table headers which don't overlap. Thanks!

**Comment by Tomsgu** [comment] 2018-06-19 13:54
Duplicate of #1524.

**Closed** 2018-06-22 07:05 UTC
Labels: Duplicate
