### ISSUE TITLE
Getting 2kb blank output when trying to add header-html to command

### ISSUE THREAD

**Issue by ghost** [wkhtmltopdf/wkhtmltopdf#3149] opened 2016-09-30 18:45 UTC
**_# Edit 3: FFS, it was because the header.html file was missing `<!DOCTYPE html>` !!!!!!!!_**

I used a simple example I found on Stackoverflow which provided the following for header.html:
(Edit: I also noticed this example below is in the documentation here: http://wkhtmltopdf.org/usage/wkhtmltopdf.txt)

Edit 2: For some reason if I specify a margin-top size, the PDF will actually have content except the margin at the top will just be a blank white bar, nothing inside. Achieved with: `wkhtmltopdf.exe -T 20mm --header-html C:\Users\Captain\Desktop\header.html C:\Users\Captain\Desktop\ReportTemplate.html test.pdf`

```
<html><head><script>
  function subst() {
    var vars={};
    var x=window.location.search.substring(1).split('&');
    for (var i in x) {var z=x[i].split('=',2);vars[z[0]] = unescape(z[1]);}
    var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
    for (var i in x) {
      var y = document.getElementsByClassName(x[i]);
      for (var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
    }
  }
  </script></head><body onload="subst()">
  <table style="border-bottom: 1px solid black; width: 100%">
    <tr>
      <td class="section"></td>
      <td style="text-align:right">
        Page <span class="page"></span> of <span class="topage"></span>
      </td>
    </tr>
  </table>
  </body></html>
```

I first tried to run the most basic command, so, `wkhtmltopdf.exe --header-html "C:\Users\Captain\Desktop\header.html" "C:\Users\Captain\Desktop\ReportTemplate.html" outy22.pdf`

From this command I get the following output:

> Loading pages (1/6)
> Counting pages (2/6)
> Resolving links (4/6)
> Loading headers and footers (5/6)
> Printing pages (6/6)
> Done

But the pdf itself contains no data and is only 2kb in size. Any ideas what this might be?

Or is there a different output mode that may tell me more about what the problem is?

Edit: I should note that the output is normal if I do not include the header argument

**Comment by PhilterPaper** [comment] 2016-10-01 00:22
The `for (var i in x)` statement looks odd to me. x is normally a list of _properties_, and enclosed in curly braces:

    var x = {fname:"John", lname:"Doe", age:25};

The `for` statement would give **i** as fname, lname, and age; while `x[i]` would be John, Doe, and 25.

So, did you copy the sample code _exactly_? Square brackets [ ] are for numerically indexed (0, 1, 2,...) arrays, while curly braces { } are for objects (associative arrays). Or have things changed recently and for..in is now allowed with ordinary arrays?

**Comment by Yelnik** [comment] 2016-10-03 12:38
Even as a standalone piece of javascript it executes just fine in Chrome. And, as I said, that example is in the documentation for wkhtmltopdf.

**Comment by Yelnik** [comment] 2016-10-04 12:38
And as far as what those refer to, in the documentation it says:

> Footers And Headers:
>   Headers and footers can be added to the document by the --header-* and
>   --footer* arguments respectfully.  In header and footer text string supplied
>   to e.g. --header-left, the following variables will be substituted.
> 
>    * [page]       Replaced by the number of the pages currently being printed
>    * [frompage]   Replaced by the number of the first page to be printed
>    * [topage]     Replaced by the number of the last page to be printed
>    * [webpage]    Replaced by the URL of the page being printed
>    * [section]    Replaced by the name of the current section
>    * [subsection] Replaced by the name of the current subsection
>    * [date]       Replaced by the current date in system local format
>    * [isodate]    Replaced by the current date in ISO 8601 extended format
>    * [time]       Replaced by the current time in system local format
>    * [title]      Replaced by the title of the of the current page object
>    * [doctitle]   Replaced by the title of the output document
>    * [sitepage]   Replaced by the number of the page in the current site being converted
>    * [sitepages]  Replaced by the number of pages in the current site being converted


Someone must know what the issue is, it is quite literally one of the simplest commands wkhtmltopdf has and it outputs nothing...

**Comment by dfsurdyk** [comment] 2016-10-12 20:10
+1 @Yelnik - your Edit 3 above just saved me from spending days debugging this exact same exact issue.  Thank You!

Might I suggest we fail gracefully in the absence of ```<!DOCTYPE html>``` and/or well-formed XML?

**Comment by Tomsgu** [comment] 2018-09-25 21:50
Closing as it was fixed.

**Closed by Tomsgu** 2018-09-25 21:50 UTC
Labels: NeedInfo
