### ISSUE TITLE
Build on Raspberrypi?

### ISSUE THREAD

**Issue by random-robbie** [wkhtmltopdf/wkhtmltopdf#2791] opened 2016-02-10 10:10 UTC
Hi Guys,

The current version on raspbian is 0.9.9.

is there any guides on building for a raspberry pi.

```
Linux  4.1.10-v7+  armv7l
```

**Comment by PhilterPaper** [comment] 2016-02-10 21:11
Have you looked at #1868 yet? There might be useful information there.

**Comment by ashkulz** [comment] 2018-04-30 06:52
Duplicate of #1868

**Closed by ashkulz** 2018-04-30 06:52 UTC
