### ISSUE TITLE
Rectangle rendered after text with sans-serif font

### ISSUE THREAD

**Issue by macosgrove** [wkhtmltopdf/wkhtmltopdf#2136] opened 2015-01-08 01:42 UTC
Looks like an invalid character is being rendered after the word "License certificate" - but not after "License certif". This happens only with sans-serif font.

Here's the simplest doc I could put together that illustrates the issue:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <style>
      body {
        font-family: sans-serif;
      }
      </style>
  </head>
  <body>
    <p>License Certificate</p>
    <p>License Certifi</p>
    <p>License Certif</p>
  </body>
</html>
```
It renders like this:

![screen shot 2015-01-08 at 12 40 42 pm](https://cloud.githubusercontent.com/assets/1095688/5656603/a2c93e9a-9733-11e4-9034-6c69bcc9782d.png)

This happens in wkhtmltopdf versions later than 0.9.9. I experimented with setting different charsets but nothing seemed to make a difference. I am rendering via WickedPdf.

**Comment by ashkulz** [comment] 2015-01-08 19:30
If this is on OS X with the Carbon build, it looks like a duplicate of #1734

**Closed by ashkulz** 2015-01-08 19:30 UTC
