### ISSUE TITLE
Background color, border, and border-radius conflicting, only in header html

### ISSUE THREAD

**Issue by websiteduck** [wkhtmltopdf/wkhtmltopdf#3000] opened 2016-06-14 13:50 UTC
Running on centos 6.8 `wkhtmltopdf 0.12.3 (with patched qt)`

test.html:

```html
<!doctype html>
<html>
  <body>
    <div style="background-color: red; border: 1px solid black; border-radius: 5px;">
      Test
    </div>
  </body>
</html>
```

command:
`wkhtmltopdf --header-spacing 10 --header-html test.html test.html test.pdf`

resulting pdf:
https://www.dropbox.com/s/9t3e54gg45zuh27/test.pdf?dl=0
- It does the same thing if you use a css class instead of inline styles. 
- If you remove any one of the three properties then the header works as expected.
- If you use `--footer-html` instead of `--header-html` it works as expected.

**Comment by phily245** [comment] 2016-09-19 12:20
`--footer-html <url>`
[http://wkhtmltopdf.org/usage/wkhtmltopdf.txt](http://wkhtmltopdf.org/usage/wkhtmltopdf.txt)

**Comment by Schtorsk** [comment] 2016-12-13 11:00
I confirm I am facing the same bug.

I apply this css class to a simple div

.cartouche {
    width: 100%;
    height: 18px;
    display: block;
    background-color: #F4A23F;
    color: black;
    border: 1px solid #F08300;
    /*border-radius: 5px;*/
    font-family: Calibri, "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 15px;
    padding-top: 2px;
    margin-top: 25px;
    margin-bottom: 25px;
}

It works as expected, but if I uncomment the border-radius, the background disappear in the rendered pdf.

**Comment by Tomsgu** [comment] 2018-09-25 17:48
@websiteduck  @Schtorsk  does this still happens in 0.12.5 version?

**Comment by Schtorsk** [comment] 2018-09-26 14:18
I do not plan to upgrade the version we are using as everything is working great right now, sorry.

**Comment by Tomsgu** [comment] 2018-10-10 16:10
I can't reproduce it in 0.12.5 version on my localhost and since there is no feedback I am closing this issue. Please feel free to re-open it if you still experience it in a newest version.

**Closed by Tomsgu** 2018-10-10 16:10 UTC
Labels: NeedInfo
