### ISSUE TITLE
Generate recipients

### ISSUE THREAD

**Issue by AnderssonPeter** [wkhtmltopdf/wkhtmltopdf#3259] opened 2016-12-22 07:53 UTC
Hi i was thinking about using wkhtmltopdf to generate recipients pdf's.
Im my case they are 200 mm or 140 mm wide but the page height is as long as the content, is there any way to generate a PDF with a dynamic height so that i don´t get multiple pages?

Is there any `--page-size` i can use that would give the desired result?

**Comment by ashkulz** [comment] 2016-12-22 09:13
Duplicate of #1627

**Closed by ashkulz** 2016-12-22 09:13 UTC
