### ISSUE TITLE
wrong section in header/footer

### ISSUE THREAD

**Issue by nathanwebb** [wkhtmltopdf/wkhtmltopdf#3016] opened 2016-06-23 03:06 UTC
Hi,

When a page doesn't have any H1 tags, then the previous section is carried over. That creates a bug where the previous page had multiple sections. So the following takes place:
1. On the first page, the section is determined as being the topmost H1 tag.
2. On the first page, any additional H1 tags are ignored.
3. On the second page, there are no H1 tags, so the topmost H1 tag from the previous page is the "section". I suspect that subsections (and subsubsections) are similarly affected.

_If a page doesn't have any H1 tags, the bottom-most H1 tag of the previous page should be used as the section._
### Steps to reproduce

Use this command with a minimal example:

```
wkhtmltopdf --header-center "[section]" basic.html test.pdf
```

input file - basic.html

```
<div style="page-break-after:always;">
  <h1>Title Page</h1>
</div>
<div style="page-break-after:always;">
  <h1>My first section</h1>
  <p>This is a section</p>
  <h1>My second section</h1>
  <p>Here is some text, for the second section</p>
</div>
<div style="page-break-after:always;">
  <p>This is text in the second section. The header should say that it is the second section</p>
  <p>Here is some text, for the second section</p>
</div>
<div style="page-break-after:always;">
  <h1>My third Section</h2>
  <p>Here is some text, for the this section</p>
</div>
```
### Expected results

The third page header should say "My second section"

**Comment by garygreen** [comment] 2017-06-26 12:04
I'm also experiencing this, it would make sense to have the "latest" header be the actual section rather than the first one output on the page.

**Comment by garygreen** [comment] 2017-06-26 12:32
Seems like another issue is open #1654

**Comment by Tomsgu** [comment] 2018-09-25 18:16
Closing as a duplicate of #1654.

**Closed by Tomsgu** 2018-09-25 18:16 UTC
Labels: NeedInfo
