### ISSUE TITLE
DIV margin at top of page is ignored

### ISSUE THREAD

**Issue by jmfoleyjr** [wkhtmltopdf/wkhtmltopdf#2447] opened 2015-07-07 14:43 UTC
wkhtmltopdf version 0.12.1 and 0.12.2.1 on Slackware x64, 14.1. &lt;DIV&gt; margins at top of page are ignored:

&lt;body style="margin-top: 0"&gt;
&lt;div style="margin-top: 1.75in; border: 1px solid red"&gt;&lt;br/&gt;&lt;/div&gt;

I have this "margin-top: 1.75in" specified at the top of the page. Regardless of what I set the value to, 0.5in, 1.5in, 2in, ..., the value is ignored and the space at the top of the page is the same for all top-margin settings, i.e., no margin. Margins elsewhere (after the top-of-page) work correctly.

32bit wkhtmltopdf version 0.11.0 rc1 did not have this problem. Margins at top of page printed correctly.

**Comment by jmfoleyjr** [comment] 2015-07-07 16:21
More info ... I just downloaded and installed the 64bit 0.11.0 version. Top-margins at the top of the page work just fine on that version.

**Comment by ashkulz** [comment] 2015-07-23 07:03
Duplicate of #1606

**Closed by ashkulz** 2015-07-23 07:03 UTC
