### ISSUE TITLE
Websites rendered with JavaScript or Chart.js, PDFs comes Blank

### ISSUE THREAD

**Issue by hayatt143** [wkhtmltopdf/wkhtmltopdf#3810] opened 2018-02-06 16:54 UTC
I am trying `wkhtmltopdf` on Ubuntu 16.04 as a command with python3. But for a couple of websites is not working. The pdf created is completely blank.
Here is the command I am using 

`wkhtmltopdf https://www.sifma.org/resources/submissions/lisa-dolly-testimony-on-cat-implementation-and-cybersecurity-protocols/ output.pdf`

So nothing from [this ](https://www.sifma.org/)website gets converted to PDF.

**Comment by VincentFoulon80** [comment] 2018-06-22 11:05
@alloylab I have the same issue. "wkhtmltoimage -V" gives me "wkhtmltoimage 0.12.5 (with patched qt)".
I tried to render a google chart and the resulting image is empty. Even with --debug-javascript, --javascript-delay 20000 it doen't work. I am sure that older version, like 0.12.1 was working, except that javascript-delay wasn't working properly for me.

**Comment by Tomsgu** [comment] 2018-08-09 08:05
Duplicate of #1964.

**Closed by Tomsgu** 2018-08-09 08:05 UTC
Labels: NeedInfo
