### ISSUE TITLE
toc option produces bookmarks, but no toc page in pdf

### ISSUE THREAD

**Issue by barchambeault-edr** [wkhtmltopdf/wkhtmltopdf#4074] opened 2018-09-06 21:25 UTC
Ubuntu 16.04
wkhtmltopdf 0.12.5 (with patched qt)
command line:  wkhtmltopdf toc test.html test.pdf
text.html and test.pdf attached

[test.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2358812/test.zip)

**Comment by Tomsgu** [comment] 2018-09-07 06:49
Exactly closing as duplicate of #3953

**Closed by Tomsgu** 2018-09-07 06:49 UTC

**Comment by ashkulz** [comment] 2020-06-07 08:29
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
