### ISSUE TITLE
Rendering size issue

### ISSUE THREAD

**Issue by CitizenInsane** [wkhtmltopdf/wkhtmltopdf#3164] opened 2016-10-14 10:09 UTC
Taking care of removing any paddings or margins, I have created a basic html page containing a single table whose height is supposed to be 297mm (A4 paper height):

```html
<!DOCTYPE html>
<html>
  <head>
  <style>
    body 
    {
      padding: 0; /* Padding for content */
      margin: 0 auto; /* Margin from container */       
    }       
    table
    {
      padding: 2.5mm 5mm; /* Padding for content */       
      margin:0; /* Margin from container */

      width:100%;
      border-spacing:0;
      background-color:yellow;

      height:297mm;
    }
  </style>
  </head>
  <body>
    <table>
      <tr style="height:3%"><td style="background-color:RGB(235, 105, 11)">1</td></tr>
      <tr style="height:30%"><td style="background-color:RGB(47,52,57)">2</td></tr>
      <tr style="height:17%"><td style="background-color:RGB(94,98,102)">3</td></tr>
      <tr style="height:auto"><td style="background-color:RGB(255,255,255)">4</td></tr>
      <tr style="height:13%"><td style="background-color:RGB(47,52,57)">5</td></tr>
    </table>
  </body>
</html>
```

And I'm trying to render this in A4 PDF format using version **0.12.3.2** (again taking care of removing any margin and/or padding:

```
wkhtmltopdf.exe --page-size A4 -L 0 -R 0 -T 0 -B 0 .\testsize.html testsize.pdf
```

Anyway rendered table height does not seem to be 297mm in PDF document. It appears to be smaller:

![Rendered pdf](https://i.stack.imgur.com/FVzOK.png)

It is only when modifying table height to `height: 371mm` that I can have it to fill full A4 paper height in the PDF document (NB: 371mm/291mm is almost a x1.25 ratio).

NB: When displaying html code in chrome with zoom=x1, displayed height already doesn't match with A4 PDF document placed side-by-side and zoom also set to x1.

**Do you have any idea for where this ratio in rendering height comes from and how i may fix it ?**

**Comment by jokkopp** [comment] 2016-11-13 20:26
+1 i have the same problem

**Comment by martin-trajanovski** [comment] 2016-12-20 07:33
I think you should use **--disable-smart-shrinking** before --page-size and set the width and height on the html body

**Comment by willfaught** [comment] 2017-07-06 05:56
@martin-trajanovski Where is the --disable-smart-shrinking? I have version 0.12.4 and it says that option doesn't exist.

**Comment by martin-trajanovski** [comment] 2017-07-06 06:07
https://wkhtmltopdf.org/usage/wkhtmltopdf.txt search for --disable-smart-shrinking and there is description next to it.

**Comment by willfaught** [comment] 2017-07-06 06:15
@martin-trajanovski Whoa, that's way different than what I see on macOS:

```output
Global Options:
      --collate                       Collate when printing multiple copies
                                      (default)
      --no-collate                    Do not collate when printing multiple
                                      copies
      --copies <number>               Number of copies to print into the pdf
                                      file (default 1)
  -H, --extended-help                 Display more extensive help, detailing
                                      less common command switches
  -g, --grayscale                     PDF will be generated in grayscale
  -h, --help                          Display help
      --license                       Output license information and exit
  -l, --lowquality                    Generates lower quality pdf/ps. Useful to
                                      shrink the result document space
  -O, --orientation <orientation>     Set orientation to Landscape or Portrait
                                      (default Portrait)
  -s, --page-size <Size>              Set paper size to: A4, Letter, etc.
                                      (default A4)
  -q, --quiet                         Be less verbose
      --read-args-from-stdin          Read command line arguments from stdin
      --title <text>                  The title of the generated pdf file (The
                                      title of the first document is used if not
                                      specified)
  -V, --version                       Output version information and exit

Page Options:
      --print-media-type              Use print media-type instead of screen
      --no-print-media-type           Do not use print media-type instead of
                                      screen (default)

Contact:
  If you experience bugs or want to request new features please visit 
  <https://github.com/wkhtmltopdf/wkhtmltopdf/issues>
```

What am I seeing if what you linked to is the "real" one? I installed wkhtmltopdf with Homebrew, FOR WHAT IT'S WORTH.

**Comment by martin-trajanovski** [comment] 2017-07-06 06:24
Oh there you have a very poor list of options. I am on windows machine and there are lot of settings for wkhtmltopdf. Not sure how to help you.

**Comment by Tomsgu** [comment] 2018-06-19 14:32
It's because there is a difference between `wkhtmltopdf -h` and `man wkhtmltopdf`.

**Comment by Tomsgu** [comment] 2018-09-26 16:42
Closing as the issue is resolved by `--disable-smart-shrinking` option. The problem you're facing is that you use the unpatched version of wkhtmltopdf.

**Closed by Tomsgu** 2018-09-26 16:42 UTC
Labels: NeedInfo
