### ISSUE TITLE
wkhtmltopdf is not reading javascript (Django)

### ISSUE THREAD

**Issue by manishReddevil** [wkhtmltopdf/wkhtmltopdf#3723] opened 2017-11-17 04:44 UTC
I am trying to convert my Html page in Django to PDF and using 'Wkhtmltopdf' to do so. Everything is working as planned but it is not reading my bar chart in javascript. I have used simple js but still while converting to pdf, the charts are not shown.

I have used the following codes:

```python
response = PDFTemplateResponse(
    request=request,
    template=self.template,
    filename="hello.pdf",
    context=data,
    show_content_in_browser=False,
    cmd_options={'margin-top': 10,
        "zoom": 3,
        "viewport-size": "1366 x 513",
        'javascript-delay': 1000,
        'footer-center': '[page]/[topage]',
        "no-stop-slow-scripts": True},
)
return response
```
The CSS are also loaded just fine.

**Comment by Sicos1977** [comment] 2017-11-17 13:00
If you are on Windows can you then try this? It's something simular then wkHtmlToPdf but instead it uses the latest version of Google Chrome underwater.

https://github.com/Sicos1977/ChromeHtmlToPdf

**Comment by Tomsgu** [comment] 2018-08-09 08:07
Duplicate of #1964.

**Closed by Tomsgu** 2018-08-09 08:07 UTC
Labels: Duplicate
