### ISSUE TITLE
Valid characters escaped in HTML links

### ISSUE THREAD

**Issue by carlosgaldino** [wkhtmltopdf/wkhtmltopdf#4660] opened 2020-04-09 11:45 UTC
**wkhtmltopdf version(s) affected**: wkhtmltopdf 0.12.5 (with patched qt)

**OS information**
macOS 10.15.3

**Description**
When generating the pdf, links with fragments or question marks are escaped by default even though they are valid characters in a link.

**How to reproduce**
`wkhtmltopdf http://google.co.uk google.pdf`
Open the generated pdf and try to click on the Corona link and you will get a 404 because the link has been transformed in an invalid link.

The original link should be: https://www.google.com/url?q=https://www.google.co.uk/covid19/%3Futm_source%3Dgoogleuk%26utm_medium%3Ddesktophpp%26utm_campaign%3Dmicrosite&source=hpp&id=19017112&ct=3&usg=AFQjCNHYc9RzQ72FFPZWCvbH7xEDLjY3bA&sa=X&ved=0ahUKEwjVz8jgoNvoAhXNGuwKHX7MAMQQ8IcBCBE

The link on the pdf is: https://www.google.com/url?q=https://www.google.co.uk/covid19/%253Futm_source%253Dgoogleuk%2526utm_medium%253Ddesktophpp%2526utm_campaign%253Dmicrosite&source=hpp&id=19017112&ct=3&usg=AFQjCNHYc9RzQ72FFPZWCvbH7xEDLjY3bA&sa=X&ved=0ahUKEwj4g-PNn9voAhVK_KQKHbh7Cm4Q8IcBCAU

**Expected behavior**
Valid characters not to be escaped.

You can also reproduce this by placing a link in an HTML with a fragment: 
`<a href="https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/src/pdf/pdfarguments.cc#L138-L146">foo</a>` 

And the pdf will actually point to the following: `https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/src/pdf/pdfarguments.cc%23L138-L146`

Is this a known issue, or am I missing something by not setting an expected flag to avoid escaping the characters?

Thank you.

**Comment by mssmaks** [comment] 2020-04-22 14:43
I confirm. There is a problem. wkhtmltopdf escapes an already escaped link. As a result of which, it does not work.

**Comment by iSeeSwift** [comment] 2020-04-23 04:38
Hi,
I haven‘t yet looked into the code, but fwiw the same behavior also seems to occur when using Safari on macOS to Print/export to pdf.
(I was trying to generate links to pages in an pdf-document that to work in html, but not in the printed/exported version. the format for such links is ...page.html#page=42 and the # is escaped as described in the original post.) 

Hope this helps.
Since I am also generating the HTML I would also appreciate a workaround.

Thank you!

**Comment by ashkulz** [comment] 2020-06-09 02:03
Duplicate of #4406

**Closed by ashkulz** 2020-06-09 02:03 UTC

**Comment by ashkulz** [comment] 2020-06-09 02:04
Thanks for the analysis @mssmaks ... I'll be reviewing the PR and hopefully merging for the 0.12.7 release.

**Comment by bsod85** [comment] 2022-02-17 08:29
Hi! I don't think that this is a duplicate of #4406 
That issue is about incorrect anchor decoding and the attached PR only addresses that case.
From what I observed I think that the problem is more general as pointed by this issue and it's not fixed by that PR.
I am not familiar with cpp but by analyzing the code I think that the problem originates here:
https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/src/lib/pdfconverter.cc#L569
By reading QUrl class code and documentation I came to the conclusion that this row should have been
`QUrl href = QUrl::fromEncoded(h);` instead of `QUrl href(h);`
I'm not able to build a custom version to prove this hypotesis but does it at least make sense?
