### ISSUE TITLE
Page break in table row

### ISSUE THREAD

**Issue by Dolfik1** [wkhtmltopdf/wkhtmltopdf#3395] opened 2017-03-17 15:23 UTC
`page-break-before: always;` not working when applied to table rows

Example: https://gist.github.com/Dolfik1/ccd81ef02a265b6fb50d9bb4c4776ac9
[test.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/851024/test.pdf)

**Comment by sannek8552** [comment] 2017-09-11 14:18
+1

**Comment by andkorsh** [comment] 2017-09-14 03:58
@Dolfik1 @sannek8552 Take a look at my pull request - it should solve your problem https://github.com/wkhtmltopdf/qt/pull/36

**Comment by gmkhussain** [comment] 2018-06-26 05:30
use this classes for page break :
```
<style type="text/css" media="screen,print">
       /* Page Breaks */

/***Always insert a page break before the element***/
       .pb_before {
           page-break-before: always !important;
       }

/***Always insert a page break after the element***/
       .pb_after {
           page-break-after: always !important;
       }

/***Avoid page break before the element (if possible)***/
       .pb_before_avoid {
           page-break-before: avoid !important;
       }

/***Avoid page break after the element (if possible)***/
       .pb_after_avoid {
           page-break-after: avoid !important;
       }

/* Avoid page break inside the element (if possible) */
       .pbi_avoid {
           page-break-inside: avoid !important;
       }

   </style>
   
```
   
   
   
   
How to write html code see example.
```
<div class="page1 pb_after">
   content 1...
</div>
<div class="page2 pb_before pb_after">
   content 2.... <table>...</table> 
</div>
```

Table rows break... It works :)

**Comment by Tomsgu** [comment] 2018-06-29 13:48
Closing as it is duplicate of #1524.

**Closed by Tomsgu** 2018-06-29 13:48 UTC
Labels: NeedInfo
