### ISSUE TITLE
Generic linux build for 0.12.5

### ISSUE THREAD

**Issue by maguba** [wkhtmltopdf/wkhtmltopdf#3958] opened 2018-06-15 14:54 UTC
Version 0.12.5 doesn't have a generic build like wkhtmltox-0.12.5_linux-generic-amd64.tar.xz. Please, could it be made available?

**Comment by ashkulz** [comment] 2018-06-15 15:01
Duplicate of #3947

**Closed by ashkulz** 2018-06-15 15:02 UTC
