### ISSUE TITLE
UnknownNetworkError on WSL

### ISSUE THREAD

**Issue by mikerockett** [wkhtmltopdf/wkhtmltopdf#3826] opened 2018-02-22 16:49 UTC
I’m running the Fall Creators update of Windows 10, and have (even since prior updates) been unable to get wkhtmltopdf working. My distro is Ubuntu, and here’s what I get when an attempt to generate a PDF is made:

```
The exit status code '1' says something went wrong:
stderr: "Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
QSslSocket: cannot resolv ▶
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv3_client_method
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv3_server_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
[=========>                                                  ] 15%
[=============>                                              ] 22%
QSslSocket: cannot call  ▶
QSslSocket: cannot call unresolved function SSL_library_init
[============================================================] 100%
Counting pages (2/6)                                               
[============================================================] Object 1 of 1
Resolving links (4/6)                                                       
[============================================================] Object 1 of 1
Loading headers and footers (5/6)                                           
Printing pages (6/6)
[>                                                           ] Preparing
[============================================================] Page 1 of 1
Done       ▶
Exit with code 1 due to network error: UnknownNetworkError
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
"
stdout: ""
command: /usr/local/bin/wkhtmltopdf --lowquality --image-quality 100 --margin-bottom '10' --margin-left '10' --margin-right '10' --margin-top '10' --allow '/mnt ▶
```

Am I safe to assume this is something to do with open-ssl? If so, seems weird, as I’m up to date; as such, maybe a config issue?

**Comment by ashkulz** [comment] 2018-04-29 10:26
Duplicate of #3001, try the [preview binaries for linux](https://builds.wkhtmltopdf.org/0.12.5-dev/).

**Closed by ashkulz** 2018-04-29 10:26 UTC

**Comment by mikerockett** [comment] 2018-04-29 11:54
I've moved to a Mac, so not able to test anymore. Thanks though 👍
