### ISSUE TITLE
Exit with code 1 due to network error: UnknownNetworkError

### ISSUE THREAD

**Issue by alagiyanirav** [wkhtmltopdf/wkhtmltopdf#3923] opened 2018-05-19 15:46 UTC
Command:  wkhtmltopdf https://google.com google.pdf

Loading pages (1/6)
QSslSocket: cannot resolve CRYPTO_num_locks                  ] 10%
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv3_client_method
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv3_server_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_library_init
Error: Failed loading page https://google.com (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: UnknownNetworkError
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback

wkhtmltopdf 0.12.4 (with patched qt)
**wkhtmltopdf : wkhtmltopdf 0.12.4 (with patched qt)**

**Comment by ashkulz** [comment] 2018-05-19 17:02
Duplicate of #3001

**Closed by ashkulz** 2018-05-19 17:02 UTC

**Comment by alagiyanirav** [comment] 2018-05-21 06:33
Hi Ashish,
Thanks for your valuable feedback. 
I have already gone through #3001  but unable to find steps for the solution in Ubuntu 18.04.
I really appreciate your help.
Thanks

**Comment by pla1** [comment] 2018-11-21 18:53
@alagiyanirav `sudo apt install libssl1.0-dev` on Ubuntu 18.04 worked for me.

**Comment by ljromero** [comment] 2019-04-02 10:49
@pla1 This works for me too on Debian Stretch

**Comment by visahardik** [comment] 2020-06-12 12:49
I have same problem after installing `sudo apt install libssl1.0-dev`. 
Is there any other option. I am using `h4cc/wkhtmltopdf-amd64` to print PDF in ubuntu lamp localhost.

**Comment by ashkulz** [comment] 2020-06-12 13:04
Please use the latest version of wkhtmltopdf. If you're using some wrapper, please ask them to update their package, can't help you there.
