### ISSUE TITLE
H3 margin-top stripped from PDF when at top of visible element stack

### ISSUE THREAD

**Issue by Jovve** [wkhtmltopdf/wkhtmltopdf#2474] opened 2015-07-21 13:20 UTC
Rather odd results when attempting to pad the top most H3 element in either the --header-html file or the main body HTML, any margin-top settings are stripped from the element as if they never existed.  This may have something to do with "trimming" any blank space before the content begins.  However, this may cause problems if I am attempting to align elements when they are side-by-side and the top/bottom margins are used to finely adjust the vertical alignment to "center" the elements. How I can regain the control over when and where I want the margin-top?  What am I missing?

I have not tried this in the --footer-html section, but I am sure it will react the same.  

// Test example:
In this example, please note that the first and third H3 elements both have top margin of "100px" and the middle H3 has none.  The expected result is that both the first and third H3 elements should be displaced from the top by 100px each.  The actual results show the first H3 has its top margin stripped regardless of the setting.  Why?

Using 0.12.3-dev-79ff51e of the WKHTMLTOPDF builds.

// Command used to generate the PDF file.
C:\dos>wkhtmltopdf --debug-javascript "YOUR_DIR_HERE\pdfFile.html" "YOUR_DIR_HERE\p.pdf"

// The HTML code that is being used in the test named pdfFile.html

<pre>
<code>

&lt;!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
&lt;html&gt;&lt;head&gt;
&lt;meta http-equiv="Content-Type" content="text/html; charset=UTF-8"&gt;

&lt;style&gt;
.no-padding {
    padding: 0px;
}
.no-margin {
    margin: 0px;
}
.colorRed {
    color: #FF0000;
}
&lt;/style&gt;
&lt;/head&gt;
&lt;body style="width : 1024px;"&gt;
    &lt;!-- The main container --&gt;
    &lt;div class="container"&gt;

        &lt;h3 class="no-padding colorRed" style="margin: 100px 0 0 0;"&gt;H3 Header Section 1&lt;/h3&gt;
        &lt;h3 class="no-padding no-margin colorRed"&gt;H3 Header Section 2&lt;/h3&gt;
        &lt;h3 class="no-padding colorRed" style="margin: 100px 0 0 0;"&gt;H3 Header Section 3&lt;/h3&gt;

    &lt;/div&gt;
&lt;/body&gt;&lt;/html&gt;

</code>
</pre>

**Comment by Jovve** [comment] 2015-07-21 14:41
Too see the margin and padding more easily, the following is the html for the test case:

<pre>
<code>
&lt;!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"&gt;
&lt;html&gt;&lt;head&gt;
&lt;meta http-equiv="Content-Type" content="text/html; charset=UTF-8"&gt;

&lt;style&gt;
.no-padding {
    padding: 0;
}
.no-margin {
    margin: 0;
}
.colorRed {
    color: #FFFF00;
}
.background-colorCyan {
    background-color: #9966FF;
}
&lt;/style&gt;
&lt;/head&gt;
&lt;body style="width : 1024px;"&gt;
    &lt;!-- The main container --&gt;
    &lt;div class="container"&gt;

		&lt;h3 class="colorRed background-colorCyan" style="margin: 100px; padding: 50px;"&gt;Header Section&lt;/h3&gt;
		&lt;h3 class="no-padding no-margin colorRed background-colorCyan"&gt;Header Section&lt;/h3&gt;
		&lt;h3 class="colorRed background-colorCyan" style="margin: 200px; padding: 50px;"&gt;Header Section&lt;/h3&gt;

    &lt;/div&gt;


&lt;/body&gt;&lt;/html&gt;
</code>
</pre>

**Comment by Jovve** [comment] 2015-07-21 16:09
![marginissue](https://cloud.githubusercontent.com/assets/13034470/8805814/46ef09a4-2fa1-11e5-874d-3f6d000477f6.jpg)

**Comment by ashkulz** [comment] 2015-07-23 07:03
Looks like a duplicate of #1606

**Closed** 2018-08-22 18:04 UTC
Labels: Duplicate
