### ISSUE TITLE
running wkhtmltopdf with anonymous authentication turned off

### ISSUE THREAD

**Issue by sonarpatel** [wkhtmltopdf/wkhtmltopdf#2528] opened 2015-08-18 19:49 UTC
We have an application that uses windows authentication. We are planning to convert an HTML page from our application to a PDF. We get an unauthorized error when we try to generate PDF. PDF does get created but with unauthorized error message. Once I turn on anonymous authentication it works just fine. Since this application requires windows authentication to be turned on I need to have anonymous authentication turned off. Is there a way to make it work with anonymous authentication turned off? Application is installed on 2008 R2 server. We are using wkhtmltopdf version 0.12.0.0.

Thanks

**Comment by grungondola** [comment] 2016-11-28 19:44
I am encountering this same issue. The error message I get in the picture is:

> 401.2 - Unauthorized
> You are not authorized to view this page due to invalid authentication headers.

**Comment by ashkulz** [comment] 2016-11-29 06:33
Duplicate of #3184 -- if you can contribute a patch, that'd be great.

**Closed by ashkulz** 2016-11-29 06:33 UTC
