### ISSUE TITLE
ContentNotFound Eror

### ISSUE THREAD

**Issue by rickjedi** [wkhtmltopdf/wkhtmltopdf#2862] opened 2016-03-28 14:54 UTC
I'm using wkhtmltox to generate a screen capture on a dedicated server. The utility will properly render the pages when the pages are served by our VPS, but it throws an error when trying to render the screen capture when the pages are rendered by itself.

DEDICATED SERVER Attempt

[root@dedicated ~]# /usr/local/bin/wkhtmltoimage --width 1920 --height 1080 --load-error-handling ignore --disable-javascript 'http://domain-one/weather/index.php?display=5day&company_id=1&animated=false' /var/www/vhosts/domain-one/httpdocs/weather/screencaps/littletonco/screencap-5day.jpg
Loading page (1/2)
Rendering (2/2)
Done
Exit with code 1 due to network error: ContentNotFoundError

VPS Attempt

[root@dedicated ~]# /usr/local/bin/wkhtmltoimage --width 1920 --height 1080 --load-error-handling ignore --disable-javascript 'http://domain-two/index.php?display=5day&&animated=false' /var/www/vhosts/domain-two/httpdocs/weather/screencaps/littletonco/screencap-5day.jpg
Loading page (1/2)
Rendering (2/2)
Done

In both attempts, the wkhtmltox utility is running on the dedicated server and the pages rendered are just about identical except for the way the hostname is configured.

We want the wkhtmltox utlity to capture successfully the pages served by itself.

THE PAGE WE WANT but doesn't work
http://domain-one/weather/index.php?display=5day&company_id=1&animated=false

THE PAGE THAT WORKS but we don't want
http://domain-two/index.php?display=5day&&animated=false

**Comment by rickjedi** [comment] 2016-03-29 17:16
I'm looking for a resolution on this ASAP.

**Comment by benf-wspdigital** [comment] 2016-07-19 06:25
Duplicate of #2051.

**Comment by lesliev** [comment] 2016-07-29 03:53
Are you sure that adding company_id=1 doesn't require you to log in? I've had that problem - the web server either redirects or asks for HTTP BASIC authentication and wkhtmltopdf returns "content not found".

**Comment by rickjedi** [comment] 2016-07-29 03:57
The URLs are publicly accessible. The only difference is that the domains might be setup differently. One thing I did not check is the actual http headers being sent. This might be different. The client has since gone with another solution for this particular project, but I would like to know since I use this library often.

**Comment by Salmon-Bard** [comment] 2016-08-15 19:22
I had this issue too. Checked various option and found the root of this problem and most of the issues reported here on various network and content not found error.

The issue is mainly due to a bug in qtwebkit qt4 patched version source code used in wkhtmltopdf. qtwebkit is not able to correctly resolve browser dns redirection and multi dns calls to resource located on one or more resources within the page.  An upgrade to newer qtwebkit Qt5 and a revised batch will likely fix all theses bugs.

Until maintainers have time to work on this or someone with the expertise lends a hand (sadly not me of course :- ( )  a workaround I found fixes the issue.

 calling your page using server IP without domain names fixed the problem. so instead of using `http://mydoamin.com/page_url  `

in your wkhtmltopdf argument call
` http://xx.xx.xx.xx/page_url `

And if you have linked files in your webpage not loading try calling them through server IP and it will likely work.

hope you find this helpful.

**Comment by okohll** [comment] 2016-08-23 14:49
+1 for this bug - the biggest one in the product for me as it stops more complex pages containing references to other files from working

**Comment by madis** [comment] 2017-11-03 08:16
I'm having the same issue with the following line causing the pdf generation to fail

```html
<script async type="text/javascript" id="mini-profiler" src="/mini-profiler-resources/includes.js?v=12b4b45a3c42e6e15503d7b04810ff55" data-version="12b4b45a3c42e6e15503d7a03810ff33" data-path="/mini-profiler-resources/" data-current-id="g0pjro89w2as9velac1n" data-ids="g0pjro89w2as9velad1n,7097nomlzktye3oeidur" data-position="left" data-trivial="false" data-children="false" data-max-traces="20" data-controls="false" data-authorized="true" data-toggle-shortcut="Alt+P" data-start-hidden="false" data-collapse-results="true"></script>
```

Are there any known remedies for it or plans for a fix?

**Comment by Salmon-Bard** [comment] 2017-11-03 08:38
As suggested above , try using full path with IP or domain name  in your source 

` src="https://your server IP/path/mini-profiler-resources/includes.js?v=12b4b45a3c42e6e15503d7b04810ff55" `

it may work not guaranteed!!!!

**Comment by Mortivor** [comment] 2017-11-06 15:21
I'm using 0.12.1 (pretty old, I know) and I'm having the same bug. It's caused by a script-Tag with a "src" attribute (wanted to include some javascript from localhost). But, contrary to your hint, the "ContentNotFound" Error appear whether i'm using "http://localhost" or "http://127.0.0.1". The only working solution I found was to not include the javascript but instead to inline it's functionality. :/

**Comment by Tomsgu** [comment] 2018-08-08 12:12
Duplicate of #2051.

**Closed by Tomsgu** 2018-08-08 12:12 UTC
Labels: NeedInfo
