### ISSUE TITLE
total page count incorrect

### ISSUE THREAD

**Issue by rmuenzbe** [wkhtmltopdf/wkhtmltopdf#3831] opened 2018-02-26 09:23 UTC
Bug:
Normal page count works correctly (i.e. 53 pages). The total page counter stops one page before (i.e. 52).
This results in wrong page numbering: 53/52 at the end.
Where can this problem occur from and/or how to solve it?

Note:
Unfortunately cannot provide files in this case but can go through them if somebody has an idea..

**Comment by ndbabb** [comment] 2018-03-09 19:15
I also experienced this bug recently. It started when I added a section of HTML that I wanted to appear on its own page by adding the CSS property "page-break-before: always" to the containing DIV. My last page showed "5/4".

I can create some test code to reproduce when I have time.

**Comment by rmuenzbe** [comment] 2018-03-16 12:09
Yes indeed. This is the problem I encounter as well. Do you have any other suggestions or ideas how to overcome this? I do not have a workaround discovered yet.

**Comment by ashkulz** [comment] 2018-06-15 12:43
Duplicate of #2711

**Closed by ashkulz** 2018-06-15 12:43 UTC
