### ISSUE TITLE
Form fields are empty on printing

### ISSUE THREAD

**Issue by jimmyfakedev** [wkhtmltopdf/wkhtmltopdf#2819] opened 2016-03-01 09:14 UTC
Hi everybody,

As the title says, I have an issue when i try ton print pdf generate from wkhtmltopdf.exe.

I'm using version 0.12.3.1 with option --enable-forms.
I saw on [this discussion](https://groups.google.com/forum/#!topic/wkhtmltopdf-general/ebivj97OFbU) that if I edit my PDF with notepad and  add /F 4 on each object of Type /Annot and SubType /Widget my problem would be solved (and it is).

The real problem is that I'm using the wkhtmltopdf.exe on an asp.net website to generate pdf forms that can be send by email. I don't want that users changes pdf configuration manually.

Is there a way to solve this issue?

**Comment by cmichaelis** [comment] 2016-03-30 19:14
Just ran into the same problem - thanks for the quick tip on s:/Annot:/Annot /F 4:g -- that seems to work perfectly. If you're using ASP.NET to generate these, then you can probably do what I just did in my own app, although mine is in a different language... just generate it like normal, then crack open the PDF and make this substitution yourself in code before sending it on to the end user. Seems to work fine as a workaround.

**Comment by ashkulz** [comment] 2016-05-06 10:03
Duplicate of #2004, which has been fixed.

**Closed by ashkulz** 2016-05-06 10:03 UTC

**Comment by vrozkovec** [comment] 2016-11-16 16:25
Can you release it, please?

**Comment by ashkulz** [comment] 2016-11-18 11:48
@vrozkovec: indeed, a release is overdue. Will try to do it in the near future.

**Comment by ashkulz** [comment] 2016-11-23 08:29
[`0.12.4`](http://wkhtmltopdf.org/downloads.html#stable) has been released, which should contain the fix for this issue. Please report back if it is not solved with the above version.

**Comment by vrozkovec** [comment] 2016-11-23 14:22
Thank you, works perfect.
