### ISSUE TITLE
Vague javascript error logging

### ISSUE THREAD

**Issue by johnedo1234** [wkhtmltopdf/wkhtmltopdf#2230] opened 2015-03-03 20:30 UTC
Try this:

`wkhtmltopdf --load-error-handling abort --load-media-error-handling abort  --debug-javascript --window-status ready page page_throws.html page.pdf`

with page_throws.html:

```html
<!DOCTYPE html>
<html lang="en">
    <body>
        <script type="text/javascript">undef.undef;</script>
    </body>
    <h>page</h>
</html>
```

The resulting error message is too vague:

```
Loading pages (1/6)
Warning: undefined:0 ReferenceError: Can't find variable: undef   
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                      
```

Which file did the error occur in, and on what line??? Very frustrating to debug problems when you have lots of javascript files...

**Comment by mauvm** [comment] 2015-03-18 10:20
+1 for adding the stack trace.

**Comment by ashkulz** [comment] 2015-04-07 12:13
Duplicate of #2225

**Closed by ashkulz** 2015-04-07 12:13 UTC
