### ISSUE TITLE
ContentOperationNotPermittedError

### ISSUE THREAD

**Issue by momolog** [wkhtmltopdf/wkhtmltopdf#1937] opened 2014-09-01 13:15 UTC
When running wkhtmltopdf 0.12.1 (with patched qt) like this

    wkhtmltopdf --page-size A4 --encoding UTF-8 --orientation landscape /tmp/test.html /tmp/output.pdf

on a [document](https://gist.github.com/momolog/7b68a24bda9726ffd921#file-working) containing 

    <img src="http://example.com/test.jpg" />

(a non-existent image), one gets the following output

    Loading pages (1/6)
    Warning: Failed to load http://example.com/test.jpg (ignore)
    Counting pages (2/6)
    Resolving links (4/6)
    Loading headers and footers (5/6)
    Printing pages (6/6)
    Done

and a status code of 0 (success), a PDF is generated.

If, however the URL of the image [gets slightly changed](https://gist.github.com/momolog/7b68a24bda9726ffd921#file-broken) to something like 

    <img src="http://example.com/test.jpg?332534" />

(only added a random query param) one gets the following output

    Loading pages (1/6)
    Counting pages (2/6)
    Resolving links (4/6)
    Loading headers and footers (5/6)
    Printing pages (6/6)
    Done
    Exit with code 1 due to network error: ContentNotFoundError

and a status code of 1 (error). A PDF is generated nonetheless, but wrapper code will assume a non-recoverable error.

This is clearly very confusing behaviour and imho. a bug.

**Comment by zealfire** [comment] 2015-06-29 21:03
I was too getting same error. On further investigation I came to conclusion that inclusion of base tag in head section was cause of problem. I was writing a code like this:

`<base href=" \path\to\file" \>`
which was causing  `Exit with code 1 due to network error: ContentOperationNotPermittedError` but after removing it the error was removed. Any reasons for this?

**Comment by ashkulz** [comment] 2015-06-30 13:14
@momolog: the reason is simple, in the latter case one cannot guess that this is a request for an image just looking at the URL and hence we consider that it is a more severe error. This is a duplicate of #1855.

**Closed by ashkulz** 2015-06-30 13:14 UTC

**Comment by momolog** [comment] 2015-06-30 13:20
@ashkulz Thanks for pointing out, that this is a duplicate. 
I fail to see however, why a query parameter would change the expectation of what type of resource
`http://example.com/test.jpg?332534`
will yield.

**Comment by ashkulz** [comment] 2015-06-30 13:26
See [this comment](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1855#issuecomment-49289101) for an explanation.

**Comment by KlimczakM** [comment] 2016-04-28 14:26
Hello guys, any progress there by any chance? This is still troublesome...

**Comment by ashkulz** [comment] 2016-04-29 05:33
@KlimczakM: see the linked issue, it requires changes in Qt/WebKit.

**Comment by r3mafe** [comment] 2016-08-26 12:47
I had similar problem: generating PDF from within PHP was working fine, but a direct execution of wkhtmltopdf command in a console was throwing `ContentOperationNotPermittedError`.

The thing is - I was using url with user token, that later was used inside the code to authenticate on the server:
`https://atlas.ru/pdf/$2y$08$FyRmY8aR88AgjRY0DFbFCv===DD0W8L6D...`

And I found out that on some OS that address was not interpreted right and the token was malformed by the time in got to my js-script.

So, changing `$` to `%24` and `=` to `%3D` did the trick.

Maybe it will help someone.

**Comment by Hubro** [comment] 2016-10-31 04:17
I also got this error today. In my case it was because I'd made a change to my nginx config that blocked access to the website in question for the server that wxhtmltopdf was running on. Basically, wkhtmltopdf got a "401 Forbidden" when trying to open the URL, and that resulted in this error.
