### ISSUE TITLE
White 1 pixel right margin present when zeroing PDF margins

### ISSUE THREAD

**Issue by jerefrer** [wkhtmltopdf/wkhtmltopdf#3181] opened 2016-10-28 07:34 UTC
I'm reposting this issue https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1982 because I think it has mistakenly been marked as invalid after the person asking the question closed the issue.

For me this is still ongoing issue as I encountered the same bug with the latest version.

To recap, when zeroing the margins (`--margin-top 0 --margin-bottom 0 --margin-left 0 --margin-right 0`), there seems to always be a 1 pixel white margin at the right edge of portrait PDFs and at the bottom edge of portrait ones.

The only fix I found is to manually set page width/height.
For instance this works for portrait A4 PDFs: `--page-height 297mm --page-width 212mm`.

But as @MarcReniu pointed out this clearly is not an acceptable solution. I feel that this is clearly a bug that should not be there in the first place.

What do you think ?

**Comment by vicentenoriega** [comment] 2016-11-26 11:14
Hi jerefrer,

I'm experiencing that bug as well. I agree with you that this is clearly a bug.

The bug gets bigger and bigger if the PDF document has got more and more pages as that pixel margin is cumulative. On first page is 1 pixel margin as you say, but on the second page is 2px, third page 3px, etc...

I also realised that when we set page size A4, the generated PDF is not exactly 297mm X 210mm. It actually is 297.04mm X 209.90mm. I'm not sure if that may be causing the issue.

I hope someone how is contributing to develop this usufull software can give us some feedback about this issue.

Regards :)

**Comment by inakrin** [comment] 2016-12-12 03:08
+1

**Comment by xtcat** [comment] 2016-12-19 10:00
+1

**Comment by rmerk** [comment] 2017-01-23 15:40
+1

**Comment by brownerg** [comment] 2017-02-15 09:52
+1

**Comment by heraldsuva** [comment] 2017-02-23 00:46
same issue here, any solutions yet?

**Comment by Kn4ppster** [comment] 2017-04-04 10:32
+1

**Comment by alexandrekop** [comment] 2017-05-09 15:11
+1

**Comment by tchret** [comment] 2017-06-16 08:50
+1

**Comment by salamagd** [comment] 2017-09-21 11:32
:+1:

**Comment by trangtungn** [comment] 2018-06-22 09:16
+1

**Comment by Tomsgu** [comment] 2018-09-26 17:04
Closing as I can't reproduce the issue in 0.12.5. Please re-open this issue or comment if you still have the same problem. (I used the example from the connected issue)

**Closed by Tomsgu** 2018-09-26 17:04 UTC
Labels: NeedInfo

**Comment by lucasumberto** [comment] 2019-10-01 16:24
I'm having this problem on 0.12.5

PDF options:
page-width 120mm
page-height 200mm
margin-bottom 0
margin-top 0
margin-left 0
margin-right 0

CSS for the root element:
height: 200mm;
width: 100%;
margin: 0;
border: none;
padding: 0;

I tried the A4 size solution but it still have missing pixels on rigth and bottom margins.
[testpdf.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3676825/testpdf.pdf)

Edit:
The bottom margin was adjusted adding height to internal elements using mm units till it consume all the page, but it's not the same size that was defined on the pdf options... it's exactly 50.5mm more than what was defined on the pdf options, i tried the same with the width, but even if the content overflows the page it still have the left white line:
[testepdf2.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3677522/testepdf2.pdf)

**Comment by lucasumberto** [comment] 2019-10-01 17:41
I'm having this problem on 0.12.5

PDF options:
page-width 120mm
page-height 200mm
margin-bottom 0
margin-top 0
margin-left 0
margin-right 0

CSS for the root element:
height: 200mm;
width: 100%;
margin: 0;
border: none;
padding: 0;

I tried the A4 size solution but it still have missing pixels on rigth and bottom margins.

Edit:
The bottom margin was adjusted adding height to internal elements using mm units till it consume all the page, but it's not the same size that was defined on the pdf options... it's exactly 50.5mm more than what was defined on the pdf options, i tried the same with the width, but even if the content overflows the page it still have the left white line:
[testpdf.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3677781/testpdf.pdf)

**Comment by joshcomley** [comment] 2022-09-16 09:56
Thanks @lucasumberto - setting the DPI to 300 solved this for me
