### ISSUE TITLE
Error stacks

### ISSUE THREAD

**Issue by Mosho1** [wkhtmltopdf/wkhtmltopdf#2331] opened 2015-04-27 07:50 UTC
Hello, I'm having difficulties with my app and wkhtmltopdf. I tried using --debug-javascript but I am only getting cryptic error messages without proper file locations. Is it possible to output the whole error stack?

**Comment by ashkulz** [comment] 2015-04-27 08:58
Duplicate of #2225

**Closed by ashkulz** 2015-04-27 08:58 UTC
