### ISSUE TITLE
No text is displayed in the generated PDF on Alpine

### ISSUE THREAD

**Issue by costinel-draculet** [wkhtmltopdf/wkhtmltopdf#4719] opened 2020-06-15 09:06 UTC
**wkhtmltopdf version(s) affected**: 0.12.5

**OS information**
Alpine (using php:7.3-fpm-alpine)

**Description**
When generating a pdf on an alpine v3.11 distribution, the structure of the page is generated along with the images and assets, but all text is missing

**How to reproduce**
`apk add wkhtmltopdf`
`wkhtmltopdf --version`  ==>  `wkhtmltopdf 0.12.5`
`wkhtmltopdf https://google.com google.pdf` <-  check the generated pdf file

**Expected behavior**
PDF should contain both images and text.

**Possible Solution**  
Maybe use version 0.12.6, but could not found a working package for alpine.
This package build https://pkgs.alpinelinux.org/package/edge/community/x86_64/wkhtmltopdf seems to be broken as I get a lot of errors after install.

**Comment by ashkulz** [comment] 2020-06-15 09:29
This looks like a bug in the Alpine package and a duplicate of #4715

**Comment by ashkulz** [comment] 2020-06-15 09:30
wkhtmltopdf isn't yet packaged for Alpine, see wkhtmltopdf/packaging#2

**Closed by ashkulz** 2020-06-15 09:29 UTC
