### ISSUE TITLE
wkhtmltoimage: cannot render flash animations

### ISSUE THREAD

**Issue by mohdmohsin** [wkhtmltopdf/wkhtmltopdf#2310] opened 2015-04-17 11:27 UTC
Cannot render flash animations. Please let me know if I missed anything.

Command :
 wkhtmltoimage --enable-plugins  /home/test.html  /home/test.jpg

test.html File content

```
<div class="banner">
          <object type="application/x-shockwave-flash" data="flash.swf">
          <param name="movie" value="flash.swf" />
          </object>
</div>
```

**Comment by ashkulz** [comment] 2015-04-18 04:17
Do you have Flash for Firefox installed (i.e. one with NPAPI support)?

**Comment by schoren** [comment] 2015-06-26 15:22
Hello, I'm having the same issue on Mac OS 10.10. The only difference is that I get this message when I run this command

wkhtmltoimage --enable-plugins --javascript-delay 10000 --no-stop-slow-scripts "http://localhost/test.html" test.png

I get this output:

Loading page (1/2)
2015-06-26 12:13:17.677 wkhtmltoimage[1033:46640] Error loading /Library/Internet Plug-Ins/QuickTime Plugin.plugin/Contents/MacOS/QuickTime Plugin:  dlopen(/Library/Internet Plug-Ins/QuickTime Plugin.plugin/Contents/MacOS/QuickTime Plugin, 265): no suitable image found.  Did find:
	/Library/Internet Plug-Ins/QuickTime Plugin.plugin/Contents/MacOS/QuickTime Plugin: mach-o, but wrong architecture
Warning: SSL error ignored                                        
Rendering (2/2)                                                    
Done

What could be the cause of this? What can I do to fix it?

Thanks!

**Comment by ashkulz** [comment] 2015-06-29 04:46
I have no clue, as I don't have an OS X machine.

**Comment by Tomsgu** [comment] 2018-08-22 16:58
Closing as flash is almost on it's end, so I don't think there will be some fixes for it.

**Closed by Tomsgu** 2018-08-22 16:58 UTC
Labels: NeedInfo
