### ISSUE TITLE
Error QNetworkReplyImplPrivate::error when css class page-break-inside added to tables

### ISSUE THREAD

**Issue by rengare** [wkhtmltopdf/wkhtmltopdf#3374] opened 2017-03-07 15:01 UTC
**[EDIT]**
Probably I found  why this error occurs. I made a test today with low memory and cpu usage (turn off all unecessary processes) and it seems to work now, but still there is a bug somewhere.
//////
Hi, 
Im using wkhtmltopdf (ver: 0.12.4) in c# project on windows 10, and when I added css class:

`    <style>
        table, tr, td, th, tbody, thead, tfoot {
            page-break-inside: avoid !important;
        }
    </style>`

an error occurs:

`oading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
[=============>                                              ] 23%
[===================>                                        ] 33%
[======================>                                     ] 38%
[=========================>                                  ] 43%
[===========================>                                ] 45%
[============================================================] 100%
Counting pages (2/6)                                               
[============================================================] Object 1 of 1
Resolving links (4/6)                                                       
[============================================================] Object 1 of 1
Loading headers and footers (5/6)                                           
[=>                                                          ] 2%
[==>                                                         ] 4%
[===>                                                        ] 6%
[====>                                                       ] 8%
[======>                                                     ] 10%
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
[======>                                                     ] 10%
[========>                                                   ] 14%
[================>                                           ] 28%
[===================>                                        ] 32%
[===========================>                                ] 46%
[===========================>                                ] 46%
Warning: Failed to load http://localhost:16663/Patient/Pdf/logo-healthcare.png (ignore)
[============================>                               ] 48%
Warning: Failed to load http://localhost:16663/Patient/Pdf/logo.png (ignore)
[=============================>                              ] 49%
Warning: Failed to load http://localhost:16663/Patient/Pdf/line.png (ignore)
[==============================>                             ] 50%
[===============================>                            ] 52%
[===============================>                            ] 52%
[======================================>                     ] 64%
[======================================>                     ] 64%
[========================================>                   ] 68%
[=================================================>          ] 82%
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
[==================================================>         ] 84%
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
[====================================================>       ] 87%
Warning: Failed to load http://localhost:16663/Patient/Pdf/logo-healthcare.png (ignore)
[====================================================>       ] 88%
Warning: Failed to load http://localhost:16663/Patient/Pdf/line.png (ignore)
Warning: Failed to load http://localhost:16663/Patient/Pdf/logo.png (ignore)
[=======================================================>    ] 92%
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
[========================================================>   ] 94%
[============================================================] 100%
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This might be an indication of an iframe taking too long to load.
Printing pages (6/6)
[>                                                           ] Preparing
[============>                                               ] Page 1 of 5
[========================>                                   ] Page 2 of 5
[====================================>                       ] Page 3 of 5
[================================================>           ] Page 4 of 5
[============================================================] Page 5 of 5
Done                                                                      
Exit with code 1 due to network error: ProtocolUnknownError`

Someone had it before?

**Comment by alloylab** [comment] 2018-07-03 18:06
is this still an issue on 0.12.5?

**Comment by Tomsgu** [comment] 2018-08-07 07:28
`page-break-inside` is definitely not something that produces errors. 

Closing this issue, because it misses the minimal test case. The issue cannot be reproduced.

**Closed by Tomsgu** 2018-08-07 07:28 UTC
Labels: NeedInfo
