### ISSUE TITLE
Urgent : Difference in rendered pdf among two different versions

### ISSUE THREAD

**Issue by pratik-n** [wkhtmltopdf/wkhtmltopdf#3023] opened 2016-06-29 14:05 UTC
So I installed wkhtmltopdf (wkhtmltox-0.13.0-alpha-7b36694_linux-wheezy-amd64.deb) on Linux debian which generates the below 
![test3-page-001](https://cloud.githubusercontent.com/assets/19404985/16454564/dbec43d6-3e2e-11e6-922a-06c64697d18a.jpg)
But it requires xvfb support , without it, it generates error cannot connect to server X , also generates error , while running on a concurrency level of greater than 27.
So I used the Linux 0.12.3 (wkhtmltox-0.12.3_linux-generic-amd64.tar.xz ) .Its awesome, does not require xvfb support , but generates a different styled pdf(with larger fonts). As seen below,
![test2-page-001](https://cloud.githubusercontent.com/assets/19404985/16454572/e228d48a-3e2e-11e6-9a6e-446c6714bacd.jpg)
[The difference may not be visible clearly : the font size is increased , which results in distortion in my html pages. Initially which took 25% of page now occupies 50% of the page]
In the second case there is no issues at high concurrency, only it distorts the html as it increases the font and syles. Can you please check and provide a solution , how can I use the generic version, still generating pdf like the linux-wheezy since it generates correct pdf.

**Comment by suribit** [comment] 2016-07-11 09:41
I have the same problem. wkhtmltopdf version 0.12.2.1 on your computer installed Ubuntu 16.04 and Ubuntu 14.04 on the server. When generating on Ubuntu 14.04 all fonts are a little bit more.

**Comment by Tomsgu** [comment] 2018-09-20 16:52
Closing as it is duplicate of #2893.

**Closed by Tomsgu** 2018-09-20 16:52 UTC
Labels: NeedInfo
