### ISSUE TITLE
Need support to upgrade QTWebkit version

### ISSUE THREAD

**Issue by RazorNguyen** [wkhtmltopdf/wkhtmltopdf#2958] opened 2016-05-20 04:19 UTC
I'm a new comer. I don't know how to upgrade my Qt Webkit version to latest.
I did upgrade by reading in INSTALL.md. After I passed six steps (Install Visual Studio 2013 ---> Make sure that you....) but I don't know how to build. Please help me every one

**Comment by ashkulz** [comment] 2016-05-20 08:38
Duplicate of #2916

**Closed by ashkulz** 2016-05-20 08:38 UTC
