### ISSUE TITLE
Mismatched page count resulting in pages without headers, or less pages than reported total

### ISSUE THREAD

**Issue by tystol** [wkhtmltopdf/wkhtmltopdf#3653] opened 2017-09-16 22:42 UTC
Version: Reproducible on 0.12.3, 0.12.4 and latest master build
OS: Ubuntu 16.10

It seems there is a total page count calculation error, which occurs more frequently as pdfs start to get large (100+ pages) in size.

It can manifest in both directions (eg. The last page header (page 101) will report 101/102 pages, and page 102 will not exist. Or the 2nd last page (page 102) will report 102/102, and then the last page (103) will be missing a header completely).

Only seems to occur on Ubuntu (also tested on windows and could not repro).

Note I think it is related to the segfault reported in a range of other issues. We previously also experienced it crashing, and now after [applying this patch](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2894#issuecomment-215411312) to master, it no longer crashes, but in the cases that used to crash, they now result in this missing page headers issue.

Repro sample attached (within zip file - anonoymised version of one of our production reports):
[wkhtmltopdf-crash-repro.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1308022/wkhtmltopdf-crash-repro.zip)
Run (on Ubuntu):
`wkhtmltopdf --debug-javascript --disable-local-file-access --page-size A4 --margin-bottom 14 --margin-left 7 --margin-right 7 --margin-top 24 --orientation Landscape --title "Comparison Detail Report" --header-html /home/jsreport/header.html --footer-html /home/jsreport/footer.html /home/jsreport/content.html /home/jsreport/output.pdf`

Here is what it produces (notice the last 2 pages past 126/126 have no header or footer):
[0.12.5-patched_image_noargs.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1308025/0.12.5-patched_image_noargs.pdf)

**Comment by RowdyHowell** [comment] 2017-12-07 22:31
@ashkulz do you know of any progress on this?  I have the codebase pulled down now and can build it.  If you have any idea on where to start looking for the page count mismatch problems I can try to take a look.

**Comment by asaltiel72** [comment] 2018-01-17 15:58
@ashkulz @RowdyHowell Has any progress been made on this?

**Comment by RowdyHowell** [comment] 2018-01-18 04:49
No, I pulled down the repository and was able to compile, but never had time to make progress.

**Comment by ashkulz** [comment] 2018-06-04 03:05
Duplicate of #2711 which has a fix

**Closed** 2018-06-04 03:05 UTC
