### ISSUE TITLE
PDF Cover inserts blank header

### ISSUE THREAD

**Issue by RiddP** [wkhtmltopdf/wkhtmltopdf#2738] opened 2016-01-01 18:43 UTC
I have implemented custom swatches.  with below code
string cusomtSwitches = string.Format("--print-media-type  --allow {0} --header-html {0} --allow {1} --footer-html {1} --allow {2} cover {2}", Url.Action("PDFHeader", "Controller", new { data=""  }, Request.Url.Scheme), Url.Action("PDFFooter", "Controller", new { area = "" }, Request.Url.Scheme), Url.Action("PDFCover", "Controller", new { data="" }, Request.Url.Scheme));

My PDF is not generating properly. Cover page inserts some space on top and i suspects it is because of Header. If i remove header's html from header, Cover seems working perfectly fine and starts from top.
I can understand Cover must not have header and footer that's why i have implemented cover. but still there is some issue. 
If i can get full HTML before generating actual HTML, then I can debug where is issue. 
Is there any way to get full HTML before getting actual PDF with header and footer etc ?

**Comment by luiso1979** [comment] 2016-01-07 12:11
I'm having the same problem using wkhtmltopdf version 0.12.2.1 (with patched qt).

When setting the margins (top and bottom) to make the space for the header and footer, they also appear in the cover page (as blank space). In our case the cover page should have no margins (top and bottom).

My options are:
`--margin-top 10 --margin-bottom 10 --header-html url --footer-html url cover cover.html page.html`

Thanks in advance

**Comment by RiddP** [comment] 2016-01-07 18:03
How about your header and footer space ? We have 55px header and 20 px footer. we have to keep that margin in customswitches to show header and footer. but if we do so, we have 55 and 22 px space goes blank in cover page as well.

**Comment by krazyest** [comment] 2016-01-24 18:10
also related to https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2282

**Comment by mgw-wjp** [comment] 2017-06-16 07:09
+1

**Comment by Tomsgu** [comment] 2018-08-25 08:47
Closing as duplicate of #2282.

**Closed by Tomsgu** 2018-08-25 08:47 UTC
Labels: NeedInfo
