### ISSUE TITLE
CSS attribute display: space in inline-block causes line break

### ISSUE THREAD

**Issue by lafisrap** [wkhtmltopdf/wkhtmltopdf#3168] opened 2016-10-17 09:34 UTC
Following html code converted to pdf with:

> wkhtmltopdf test.html test.pdf

(wkhtmltopdf 0.12.3 (with patched qt))

```
<!DOCTYPE html>
<html lang="en">
<head>
<style>
.n { display: inline-block; }
</style>
</head>
<body>
<span class="n">Test Test</span> 
</body>
</html>     
```

ist displayed in one line on browsers and in two lines as pdf. (see browser.png and pdf.png)

![browser](https://cloud.githubusercontent.com/assets/3194815/19432613/a91d8e76-945d-11e6-8c7c-1069d10aaad5.png)
![pdf](https://cloud.githubusercontent.com/assets/3194815/19432612/a91acb00-945d-11e6-8c84-0fd75cd72755.png)

[test.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/532866/test.pdf)

**Comment by WillGibson** [comment] 2017-01-10 14:00
Ha! I just ended up here after Googling the same issue. Maybe I'll have to find a workaround for today's mission.

**Comment by icole** [comment] 2017-01-19 21:05
Just encountered this as well. Changing from `inline-block` to `inline` worked around it for now, but definitely seems to be an issue.

**Comment by ajoah** [comment] 2017-06-14 15:11
Apparently, it's a duplicate of https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2505

**Comment by Jmuccigr** [comment] 2017-06-14 17:16
If this really is a dup, can someone close it?

**Closed** 2018-08-08 12:09 UTC
Labels: Duplicate

**Comment by kambleaa007** [comment] 2022-03-17 08:31
I have same issue, what i did work around is,

```
.outer {
   display:table;
}
.inner-first {
   display:table-cell;
}
.inner-second {
   display:table-cell;
}
```
