### ISSUE TITLE
Random header dissapearence

### ISSUE THREAD

**Issue by 0lukasz0** [wkhtmltopdf/wkhtmltopdf#2083] opened 2014-12-01 18:19 UTC
Since update to 0.12 (now i'am using 0.12.2-dev-5dea253 - 64bit) we got wird behavior, some pages appear after last page and are blank, some pages are missing their headers.

I created gist with sample code: https://gist.github.com/0lukasz0/7b21ec0636b6a879ca6e. I tried using those command lines without margin and header spacing but problems are still there.

**Comment by 0lukasz0** [comment] 2015-01-05 10:10
@ashkulz any update on this issue?

**Comment by ashkulz** [comment] 2015-01-06 02:06
Didn't get a time to investigate this, won't happen for a month (releasing 0.12.2 and making alpha release for 0.13)

**Comment by 0lukasz0** [comment] 2015-02-11 21:07
@ashkulz we have confirmed that header are being rendered corectlly and all requests (for headers) contains data, someting happens during building page from main content and header. I have theory that it could have someting in common with header disapearing when header is prepended with whitespaces  - it could be some wierd encoding issue, something could be added before page. I double checked and all our pages are using UTF-8 encoding, but we do use some coulture specific chars in text.

When can we expect some update on this issue?

**Comment by mohamedazher** [comment] 2015-03-03 06:40
Hi,

I can say that i have almost the exact same issue. When using header-html and footer-html, i see that either the header or the footer goes missing (sometimes both) when the page is loaded.  

Its like 1st load, there is no header/footer, on 2nd load, only footer appears, 3rd load, both header and footer appear, 4th load only header, 5th, 6th, 7th works fine.

I dont see any blank pages, the main content always seems to load fine, but the header and footer html just work randomly.  

As 0lukasz0  metioned, it does look like an issue when building the page. The header/footer or both are missed out in the page building at random.

Also to point out, i have a external css link in the header and footer html. Not sure if it matters.

**Comment by wall-s** [comment] 2015-03-12 19:37
I have been having the same issue. In my header/footer HTML files I used external javascript and CSS files, linked using absolute URL's; the header/footer renders sometimes when using these, but not always. I'm using externals in the main content as well (using absolute URL), no problem there.

I decided that I would test that this was the problem by moving all of my data from the external files and just putting them directly in the HTML file. The problem seems to have resolved itself.

Why might wkhtmltopdf be having problems with linked files in the header/footer? Does it have to do with the use of absolute URL's to link CSS/JavaScript?

**Comment by 0lukasz0** [comment] 2015-03-13 16:50
@ashkulz can we have any info on this issue?

**Comment by jturbide** [comment] 2015-04-16 03:02
@0lukasz0 @wall-s I faced the exact same problem, some of my assets (css/js) were missing on my main page and that is what caused my header and my footer to randomly disappear. I had some randomly strange issues and I feel like when there's an error with the JS wkhtmltopdf becomes high as hell

**Comment by odony** [comment] 2015-04-24 14:13
We've been having a similar issue (using 0.12.1): we were loading an external file [`subst.js`](https://github.com/odoo/odoo/blob/8.0/addons/report/static/src/js/subst.js) in both our headers and footers. This file contains a common `subst()` function to put page numbers in header/footer. The results were random for the footer on documents with several pages: the whole footer was sometimes missing, and sometimes present on some pages, without changing anything, just reprinting the document.

It seems to be related to some kind of race condition, where the external JS file is not fully loaded when the footer is rendered. Perhaps this caused a JS error when the `body.onload="subst()"` was executed without the file loaded, or perhaps it was still waiting for the file and the DOM was not ready at all.
With 0.12.2.1, the problem is worse: external JS files seem not to be loaded at all (see #2183)

In either case we found we could work around the problem in two manners:
- Either by passing a longer `--javascript-delay` option to `wkhtmltopdf`, probably giving a better chance of having the `subst.js` file loaded when the rendering takes place. (Default delay is 200, it started working for us with 250ms, but your mileage may vary). This works for 0.12.1 at least (probably not for 0.12.2.1)
- Or by removing the external JS file and putting the declaration of the `subst()` function in the header/footer source directly, making sure it is always loaded. (This works in 0.12.1 and 0.12.2.1)

I haven't delved further in the source code to see how `--javascript-delay` is implemented and if there is possibly another way for `wkhtmltopdf` to know when a document is fully loaded, before rendering it. Maybe @ashkulz can shed some light on this?
Were there any commits between 0.12.1 and 0.12.2.1 that could have modified the synchronization/loading of external JS files?

BTW, there seem to be many other issues related to the same or a similar problem: #2284, #2269, #2183, perhaps #2307 and others..

**Comment by hbto** [comment] 2015-04-27 03:39
@odony & @ashkulz 
This workaround kind of works with reports to be printed that do not exceed 500 pages
around that number report does not bear header neither footer.

So inline script is being got rid somehow when printing too many pages.

Best Regards

**Comment by ashkulz** [comment] 2015-05-17 15:41
An example HTML/JS along with command-lines which fails some of the time would help me debug the issue.

**Comment by 0lukasz0** [comment] 2015-05-19 08:48
I updated gist with js which is generated, but to be honest I am sure problems do happen event without those javascripts (in my case they are generated and added to page if tokens like page or topage are used)

**Comment by SNSD1488** [comment] 2015-05-19 20:59
I've been having the same issue in wkhtmltopdf 0.12.2.1. I'm using `--header-html` and `--footer-html`. Right around page 500 (always within 5 pages of 500) both the footer and header stop appearing for me.

My footer uses javascript and the subst() function (declared in footer.html directly) to display the current page number and max page count. My header is static html and does not use javascript.

`--no-stop-slow-scripts` and `--javascript-delay` aren't making a difference for me. I've had 1000+ page PDFs on occasion generate fine with these options omitted, and I've had the headers and footers disappear when using absurd values like `--no-stop-slow-scripts --javascript-delay 60000`.

**Comment by SNSD1488** [comment] 2015-05-19 22:55
An update, I don't think the issue with >500 pages has anything to do with JavaScript. I got rid of my footer.html (which used javascript for subst()) and replaced it with `--footer-left`. I'm still using a static header.html.

Now it gets to page ~1000 (as before, always at almost exactly at this number) before the header ceases to appear.

It's almost as if it's able to include 1000 html headers/footers combined before it runs into some problem?

**Comment by hbto** [comment] 2015-06-10 02:28
In order to resolve issue regarding 500 pages,

configure:
/etc/security/limits.conf

add these lines

*                soft    nofile          4096
*                hard    nofile          4096

and:

/etc/pam.d/common-session 
and 
/etc/pam.d/common-session-noninteractive

add this line

session    required    pam_limits.so 

Best Regards.

**Comment by odony** [comment] 2015-06-10 09:56
Thanks @hbto! So in this case the problem simply comes from the default OS limits in terms of open files. `wkthmltopdf` probably keeps an open file for each rendered page, so rendering huge documents makes it reach the OS limit.
Note that if you don't want/need to use `pam_limits`, you can also simply add `ulimit -n 4096` or any other appropriate value in your Odoo startup script. It will be inherited by the `wkhtmltopdf` process when Odoo starts it.

**Comment by ashkulz** [comment] 2015-06-22 08:12
@odony: e02ff7efaf7b617986fc11c08a693e203c64a465 essentially made `--javascript-delay` default to zero for headers/footers, which exposed the underlying problem much more severely.

**Comment by odony** [comment] 2015-06-22 08:51
@ashkulz Thanks for the extra info! Is there any patch available to avoid this side effect of e02ff7e?

**Comment by ashkulz** [comment] 2015-06-22 09:01
I'll be pushing a fix which will bring back the `0.12.1` behavior, but according to odoo/odoo@3c61ee5c68e3796bb29d2521123f2a867c9cc157 it sometimes doesn't work for that version as well.

**Comment by jeff-h** [comment] 2015-07-08 01:50
I too have this issue. My theory is that it's related to the inclusion of *any* external JS or CSS resource.

I can cause this randomness easily. I used the sample header.html from http://wkhtmltopdf.org/usage/wkhtmltopdf.txt. Simply adding the following immediately after the ```head``` tag is enough to cause the problem.

```html
    <link type="text/css" rel="stylesheet" href="pdf-footer.css" media="all">
```
If I move this CSS inclusion *after* the ```<script>``` tag the problem goes away completely. Likewise, if I include the CSS directly in a ```style``` tag in the ```head``` then the problem goes away, both symptoms making me think this is a loading / timing issue. 

Since I wanted jQuery in mine (yeah, I know...) it was the same story again.

The fix for me, since I'm using gulpjs, was to use gulp-inline (https://www.npmjs.com/package/gulp-inline/) which pulls any referenced CSS & JS files inline into the HTML document, meaning no other resources have to be loaded with the file. This is working perfectly for me so far.

**Comment by ashkulz** [comment] 2015-07-08 03:16
@jeff-h: it is, see the related issue which was fixed. I'm keeping this open to track why the css/js doesn't get loaded even though page is reported as loaded.

**Comment by ashkulz** [comment] 2015-07-14 01:15
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which should contain a partial fix for this issue.

*Please note that the above downloads will be removed after the `0.12.3` release*.

**Comment by mrkmg** [comment] 2016-10-04 17:12
I was having the same problem, and increasing the javascript-delay from 200 to 400 fixed it.
I have no external javascript. Only the example subst function in the docs for page numbers.

**Comment by joantune** [comment] 2017-06-08 17:58
@jeff-h: you shouldn't have CSS after the <head> tag, right?

**Comment by jeff-h** [comment] 2017-06-09 09:44
It was a long time ago, but I'm pretty sure I was talking about the *opening* head tag (`<head>`), not the closing tag (`<\head>`).

**Comment by Tomsgu** [comment] 2018-07-25 08:39
Can you still reproduce the problem on 0.12.5?

**Comment by VenkateswaranCGI** [comment] 2018-08-02 11:41
Wkhtmltopdf vs Reportlap
Which is the best tool and provide advise.

**Comment by jturbide** [comment] 2018-08-02 12:49
Reportlab isn't free, and (RML) Report Markup Language™ is an XML-style language created by ReportLab. 
WkHtmlToPdf or WkHtmlToImage both works by crawling your HTML page directly using webkit.

**Comment by Tomsgu** [comment] 2018-08-22 15:09
Closing as this seems to be resolved. Please let us know if the issue persists in `0.12.5` version.

**Closed by Tomsgu** 2018-08-22 15:09 UTC
Labels: NeedInfo

**Comment by hrishikesh** [comment] 2018-12-05 15:48
@ashkulz, @Tomsgu :
I am getting exactly the  same issue, Getting random blank pages for same HTML content.

**Comment by grpanic** [comment] 2022-07-29 05:17
Still an issue.
Ubuntu 20.04
It seems that it cannot render reliably --header and --footer
If --footer is exluded then --header seems to work reliably
If --header is excluded then --footer works
Seems to be affected also by file size?
