### ISSUE TITLE
Issue in dynamic header and footer to each page in wikihtmltopdf

### ISSUE THREAD

**Issue by munish-usit** [wkhtmltopdf/wkhtmltopdf#2299] opened 2015-04-13 10:37 UTC
I need to give dynamic header to every page in wikihtmltopdf. Every page header should contain a section and subsection.

Currently, I am able to do this with code
```
<html><head><script>
  function subst() {
    var vars={};
    var x=window.location.search.substring(1).split('&');
    for (var i in x) {var z=x[i].split('=',2);vars[z[0]] = unescape(z[1]);}
    var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
    for (var i in x) {
      var y = document.getElementsByClassName(x[i]);
      for (var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
    }
  }
  </script></head><body style="border:0; margin: 0;" onload="subst()">
   <span class = "section"></span>
   <hr/>
   <span class = "subsesction"></span>
  </body></html>
```
But this code is failing under two test cases

1. If a single page contains two subsection. It picks the top section and print it in the header.Due to this the next page contains subsection of the previous page in the header.

2.If a page doesn't contain any subsection. It prints subsection of the previous page in the header.

**Comment by ashkulz** [comment] 2015-04-13 12:42
Looks like a duplicate of #1654 -- please do not open new issues every time, but reopen the existing issue (#2292).

**Closed by ashkulz** 2015-04-13 12:42 UTC
