### ISSUE TITLE
External Stylesheets not found when HTML comes from stdin.

### ISSUE THREAD

**Issue by saller** [wkhtmltopdf/wkhtmltopdf#2736] opened 2015-12-31 12:30 UTC
``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="foo.css">
</head>
<body>
    <h1>test</h1>
</body>
</html>
```

``` bash
cat foo.html | wkhtmltopdf - output.pdf

Loading pages (1/6)
Warning: Failed to load file:///var/folders/n6/_00zl8793_b52lnr23pg0r_40000gn/T/foo.css (ignore)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
```

Is there any way to use external stylesheets when using wkhtmlttopdf via stdin?

**Comment by iainctduncan** [comment] 2016-09-14 17:35
I'd like to know this too!

**Comment by PhilterPaper** [comment] 2016-09-15 15:15
Is `/var/folders/n6/_00zl8793_b52lnr23pg0r_40000gn/T/foo.css` the correct path to foo.css? If it is, my suspicion would be that perhaps wkHTMLtoPDF is adding **file://** in error, i.e., it's not going through the same interface as a remote file or page access (through a pseudo-browser), but as a regular local filesystem access (which has no idea what **file://** means). That would require a fix to wkHTMLtoPDF (or maybe to WebKit).

**Comment by morganzysman** [comment] 2018-05-22 12:19
Any updates on that ?

**Comment by Tomsgu** [comment] 2018-08-25 08:32
@morganzysman any answers on @PhilterPaper questions?

**Comment by Tomsgu** [comment] 2018-08-25 08:40
Closing as it seems to be a problem with the url. I can't reproduce the issue in 0.12.5 and there is no feedback since 2016.

**Closed by Tomsgu** 2018-08-25 08:40 UTC
Labels: NeedInfo

**Comment by giannidhooge** [comment] 2019-01-08 14:39
Same issue on `wkhtmltopdf 0.12.5 (with patched qt)`.

When I use an external stylesheet in the header or footer the header or footer just don't show. The page content is still showing and PDF generating without errors.
