### ISSUE TITLE
Text overlapping on one another.

### ISSUE THREAD

**Issue by GentlemanK** [wkhtmltopdf/wkhtmltopdf#3580] opened 2017-07-28 20:07 UTC
I am using latest wkhtmltopdf version 0.12.4.0 with Windows 7 64 bit OS.

I am very weak in HTML + CSS. Really sorry for that.

I see text is getting overlapped on 2nd page onwards.

Screenshot
![image](https://user-images.githubusercontent.com/27438421/28734277-29c7e7c6-73ae-11e7-9cb6-dbae0a1836c4.png)

HTML + PDF
[HtmlPDF.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/1184144/HtmlPDF.zip)

Command line parameters 

wkhtmltopdf.exe -g --disable-smart-shrinking  -T 14mm -B 14mm -L 14mm -R 14mm --margin-left .75 --margin-right .75 307791_912_5085993647_20170728104356751.html Test.pdf

Any help with change in CSS will greatly be appreciated.

**Comment by NathanCH** [comment] 2017-07-28 23:30
See #1524 for solutions to this problem.

**Comment by GentlemanK** [comment] 2017-07-31 11:00
tr {
    page-break-inside: avoid;
}

Last line on page cuts and goes to 2nd page. Please help.

**Comment by GentlemanK** [comment] 2017-07-31 12:16
This is working fine after removing parameter --disable-smart-shrinking.

**Comment by GentlemanK** [comment] 2017-07-31 14:07
Removing this parameters is shrinking the size of the PDF. If I use zoom 1.3 to increase size, original issue of overlap starts occuring again.

**Comment by NathanCH** [comment] 2017-07-31 17:29
Sounds like 'page-break-inside' CSS property is working as intended. What behavior do you want? If you want to fit everything onto a single page you may need to adjust your content.

**Comment by GentlemanK** [comment] 2017-08-01 08:13
page-break-inside:avoid works but last line @ bottom is getting cut. 

![image](https://user-images.githubusercontent.com/27438421/28815542-b5dc7c04-766f-11e7-8818-6cffaca30825.png)

**Comment by GentlemanK** [comment] 2017-08-04 15:22
Can someone please help me or confirm if this is the known issue?

**Comment by Tomsgu** [comment] 2018-06-20 07:14
Duplicate of #1524.
Please read the this issue. You can find some workarounds that can improve a situation, since there is no real fix yet.

**Closed** 2018-06-21 07:08 UTC
Labels: Duplicate
