### ISSUE TITLE
img tags with missing local file src attribute cause ContentNotFoundError 

### ISSUE THREAD

**Issue by tomchiverton** [wkhtmltopdf/wkhtmltopdf#1968] opened 2014-09-22 08:21 UTC
If the HTML passed to wkhtmltoimage contains

```html
<img alt="" border="0" height="30" src="6.1" style="display:block;" width="1" />
```

then it will fail with "Exit with code 1 due to network error: ContentNotFoundError", even though web browsers will silently ignore these types of errors and render anyway.

This is in "wkhtmltoimage 0.12.1 (with patched qt)". 
--load-error-handling or --load-media-error-handling don't seem to make a difference.

**Comment by peternijssen** [comment] 2015-12-18 15:41
Same issue here. Both on 0.12.1 as well as 0.12.2.1

**Comment by tomchiverton** [comment] 2015-12-18 18:23
Can you quote the HTML I failed to ?

**Comment by PhilterPaper** [comment] 2015-12-19 16:51
If you gave some HTML code, wrap backticks ` around it and it should show.

**Comment by PhilterPaper** [comment] 2015-12-20 22:14
So the image file "6.1" exists in the current directory, but isn't being picked up for some reason? I've heard of WebKit having problems sometimes with figuring out the path. *Do* make sure that the image is in the same directory as the HTML file. Or is it finding 6.1, but with a file extension of "1" it can't figure out how it should handle the image file? Maybe you could experiment to find the cause, such as giving a full http:/..... URL and path, or renaming it to 6.1.gif or whatever the correct type is, or both.

A 1x30 image? Sounds like someone is still doing table-based page layout (rather than CSS-based). If you don't have any control over the source, that could be a problem.

**Comment by tomchiverton** [comment] 2015-12-21 07:27
No the file is just not there at all 
-- 
Tom

**Comment by peternijssen** [comment] 2015-12-21 16:00
I see I have a slight different issue. I do have the src set with an actual file ("/images/logo.png" or similar) instead of "6.1"

**Comment by PhilterPaper** [comment] 2015-12-24 15:15
If your src starts with /, it is a known problem that wkHTMLtoPDF is going to search starting in the filesystem root, and usually won't find the desired file. You would have to change the src to either give a relative address, or the true full path. This has been discussed a number of times before.

**Comment by PhilterPaper** [comment] 2015-12-24 15:16
"No the file is just not there at all"
What then exactly do you mean by `src="6.1"`? Either the file exists in the current directory or it doesn't. If it doesn't exist, what are you trying to display there? If the web browser *is* finding an image file to render, what's different when you run wkHTMLtoPDF? Are you running with a different directory structure than the browser sees? You have me very confused.

**Comment by tomchiverton** [comment] 2015-12-24 17:56
"What then exactly do you mean by src="6.1"? Either the file exists in the current directory or it doesn't. If it doesn't exist, what are you trying to display there? "

It's not in the same folder as the HTML, no. Normal web browsers don't care and display a broken image. wkhtml throws a content not found error you can't override.

**Comment by PhilterPaper** [comment] 2015-12-24 21:49
OK, so if the browser can't find the image file, it uses a placeholder image; if wkHTMLtoPDF can't find the image file, it falls over dead. You want it to use some placeholder image instead? That sounds like an enhancement request rather than a bug. If the list of missing src files isn't large, you could try creating a 1px square white/transparent image for each missing file. At least that would get you through the run.

**Comment by tomchiverton** [comment] 2015-12-25 21:18
Shouldn't the various load error arguments be able to suppress the error? 
-- 
Tom

**Comment by peternijssen** [comment] 2015-12-29 13:44
```
  --load-media-error-handling <handler> Specify how to handle media files
                                      that fail to load: abort, ignore or skip
                                      (default ignore)
```

As far as I understood this setting, it makes sure that when an image fails to load, it ignores it rather then abort the whole PDF generation. 
However, looking at this issue it doesn't work or am I not understanding the setting correctly.

**Comment by Tomsgu** [comment] 2018-08-22 14:02
Closing as this is not an issue, but expected behaviour.

**Closed by Tomsgu** 2018-08-22 14:02 UTC
Labels: NeedInfo
