### ISSUE TITLE
Regression: page width handling broken from 0.12.3 to 0.12.4

### ISSUE THREAD

**Issue by msmuenchen** [wkhtmltopdf/wkhtmltopdf#3255] opened 2016-12-19 16:20 UTC
Hi,

between 0.12.3 and 0.12.4 the handling of documents with millimeter units in the CSS broke. I have attached two testcases - one "old", created with 0.12.3 and working as expected, and one "new", created from the same HTML.

The bug is that in the 12.3 version, the body tag completely fills the width of the 8cm page (and actually when printed on a receipt printer is 8cm wide), while the 12.4 version is also 8cm wide, but the body tag seems to have zoomed for some reason.

The command used in both cases is `wkhtmltopdf --page-width 80 --page-height 80 -T 0 -L 0 -B 0 -R 0 test.html test_xxx.pdf`, the platform is OS X 10.11, using the official binaries.

[test_new.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/661556/test_new.pdf)
[test_old.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/661555/test_old.pdf)

Source for the HTML:
```
<!doctype html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style type="text/css">
*,html {
        margin:0;
        padding:0;
        font-size:5mm;
        font-family:monospace;
}
body {
        width:8cm;
        box-sizing:border-box;
        outline:1px solid black;
}
    </style>
    <title>Lorem Ipsum</title>
</head>
<body>
<p>This is a test.</p>
<p>01234567890123456789012345</p>
</body>
</html>
```

**Comment by ashkulz** [comment] 2017-01-09 02:31
Looks like a duplicate of #3241 to me -- can you change the DPI settings as mentioned there and confirm that?

**Closed by ashkulz** 2017-01-09 02:31 UTC
