### ISSUE TITLE
Page first line is truncated sometimes in PDF

### ISSUE THREAD

**Issue by kobruleht** [wkhtmltopdf/wkhtmltopdf#3141] opened 2016-09-25 09:35 UTC
In some pages first line in created PDF is truncated:

![partiallineintopofpage](https://cloud.githubusercontent.com/assets/1274923/18814430/d3c7c504-831b-11e6-9ab0-0b40fd1e3602.png)

Line has proper height like other lines:

``` html
<!DOCTYPE html>
<html>
<head>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

         html, body {
            height: 100%;
            width: 100%;
        }

        .row {
            position: relative;
            clear: both;
        }

        .field {
            font-family: "Times New Roman";
            font-size: 10pt;
            background-color: transparent;
            overflow: hidden;
            word-break: break-all;
            z-index: 2;
        }
</head><body>
....
<div class='row'><div class='field' style='left:0.13cm;width:3.37cm;height:0.47cm;text-align:right;color:#000080;'>POS sale 136287</div>
</div>
<div class='row'><div class='field' style='left:3.68cm;width:1.82cm;height:0.47cm;'>30.01.2016</div>
</div>
<div class='row'>
<div class='field' style='left:5.55cm;width:4.45cm;height:0.47cm;'> Jaeostja </div>
</div>
<div class='row'><div class='field' style='left:10.03cm;width:2.53cm;height:0.47cm;text-align:right;'>0,15</div>
</div>
<div class='row'></div>
<div class='row'><div class='field' style='left:15.05cm;width:2.47cm;height:0.47cm;text-align:right;'>-26730,47
</div>

```

</body>
Full html to reproduce:
[partialline2.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/491556/partialline2.zip)

Result pdf: 
[result.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/491558/result.zip)

wkhtmltopdf Version:  0.12.2.1 (occurs in 0.12.3.2 also)
Operating System and Version:   Windows 10 Pro 1511

I tried to add

``` html
page-break-inside: avoid !important;
margin: 4px 0 4px 0;
```

to row and field classes as described in http://stackoverflow.com/questions/9288802/avoid-page-break-inside-row-of-table/17982110#17982110

but problem persists.

Posted also in http://stackoverflow.com/questions/39685685/how-to-show-first-line-in-page-without-truncation

**Comment by kamalsamra** [comment] 2016-09-27 11:37
@kobruleht i have seen your html structure you made it using position could you try to make it using float.I have tried it, and text does not cut.

**Comment by kobruleht** [comment] 2016-10-01 19:46
html is generated automatically from report layout. Report layout contains fields with absolute positions . It is difficult to re-factor existing code to fix wkhtmltopdf issue. Looking for solution so that html markup remains same. Styles can changed.

**Comment by manishshanker** [comment] 2016-10-06 12:22
If you can avoid overflow:hidden, that might fix the issue.

**Comment by kobruleht** [comment] 2016-10-09 13:33
Thank you. Users can draw boxes with any size in designer. Data which is coming to this box from database may be bigger than fits to box. 
In this case data which does not fit to div should not displayed. So aviding overflow:hidden is bit difficult: application shoud calculate how must text fix to box and not send more text. No idea how to implement this.

**Comment by kobruleht** [comment] 2016-10-12 09:37
I removed overflow:hidden from style. First line in some pages is still incorrect:

![truncated](https://cloud.githubusercontent.com/assets/1274923/19305225/aade83c0-9078-11e6-8aa2-b52305989f4e.png)

**Comment by DarshanKsheerasagar** [comment] 2017-02-17 06:11
Hello Is Any One got Solution of this issue...Replay me

**Comment by chenyuntc** [comment] 2017-05-27 14:40
looking forward to solutions for this problem.

**Comment by GentlemanK** [comment] 2017-07-31 11:08
Me too..  :-(

**Comment by sannek8552** [comment] 2017-09-11 13:08
The same issue

**Comment by henri44** [comment] 2017-09-26 16:31
same issue

**Comment by treyseals** [comment] 2018-02-08 22:09
same issue

**Comment by Tomsgu** [comment] 2018-06-20 07:14
Duplicate of #1524.
Please read the this issue. You can find some workarounds that can improve a situation, since there is no real fix yet.

**Closed** 2018-06-21 07:03 UTC
Labels: Duplicate

**Comment by Norris1z** [comment] 2022-08-23 18:29
Adding 
`    html,
    body {
        margin: 0;
        padding: 0;
        border: 0;
        font-size: 100%;
        font: inherit;
        vertical-align: baseline;
    }`

Fixed it for me.
