### ISSUE TITLE
Table columns goes to out of page

### ISSUE THREAD

**Issue by ponm** [wkhtmltopdf/wkhtmltopdf#2995] opened 2016-06-13 13:12 UTC
Guys can you help how to fix this issue?
![table-width](https://cloud.githubusercontent.com/assets/19732273/16008640/9493e25e-3196-11e6-9b30-251c4b600e29.jpg)

**Comment by PhilterPaper** [comment] 2016-06-13 14:20
**Duplicate of #2985. Please close immediately.**

**Closed** 2018-06-22 06:55 UTC
Labels: Duplicate
