### ISSUE TITLE
localhost is accessed through the proxy

### ISSUE THREAD

**Issue by nickrussler** [wkhtmltopdf/wkhtmltopdf#2130] opened 2015-01-05 16:39 UTC
It seems that localhost is accessed through the proxy, when one is specified.

Thank you very much for this awesome tool btw. :+1:

**Comment by ashkulz** [comment] 2015-01-06 02:04
Duplicate of #1565, a patch is needed to implement this behavior.

**Closed** 2015-01-13 09:30 UTC
Labels: Duplicate

**Comment by ashkulz** [comment] 2015-06-06 09:57
A patch regarding this has been merged and should be available in the next release (0.12.3).

**Comment by ashkulz** [comment] 2015-07-14 01:27
A preview for the next release [`0.12.3-dev-79ff51e`](http://wkhtmltopdf.org/downloads.html#testing) is available, which should contain the fix for this issue. Please report back if it is not solved with the above version.

*Please note that the above downloads will be removed after the `0.12.3` release*.
