### ISSUE TITLE
TOC page is not generated in 0.12.5

### ISSUE THREAD

**Issue by VitaliyMF** [wkhtmltopdf/wkhtmltopdf#3989] opened 2018-07-02 16:16 UTC
New wkhtmltopdf 0.12.5 doesn't render TOC content in comparing to previous 0.12.4:

```
> wkhtmltopdf toc toc_test.html toc.pdf
```

[toc_test.html.zip](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2155947/toc_test.html.zip)
[toc_12_4.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2155948/toc_12_4.pdf)
[toc-12_5.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/2155951/toc-12_5.pdf)

**Comment by ashkulz** [comment] 2018-07-02 16:52
Duplicate of #3953, use the dev build.

**Closed by ashkulz** 2018-07-02 16:52 UTC

**Comment by ashkulz** [comment] 2020-06-07 08:26
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.

**Comment by VitaliyMF** [comment] 2020-06-09 18:01
@ashkulz I've performed some tests with 0.12.6 RC (Win-x86):

- TOC generation works as in 0.12.4
- page breaks inside table with tr td th { page-break-inside:avoid; } works as in 0.12.4
- page header/footer with page numbers are ok

Also I use wkhtmltopdf for PDF exports in SeekTable (this is a BI tool); it seems 0.12.6 (windows build) works just fine - tables, pivot tables and charts, all this looks good in PDF. I didn't tested Linux build of wkhtmltopdf yet, hope will have a time for that tomorrow.
