### ISSUE TITLE
wkhtmltopdf for a single page return

### ISSUE THREAD

**Issue by lonnietc** [wkhtmltopdf/wkhtmltopdf#2825] opened 2016-03-06 23:28 UTC
Greetings All,

I have just started looking at wkhtmltopdf and wkhtmltoimage but noticed something interesting.

When I use wkhtmltopdf on a long scrolling webiste like yahoo.com, it seems to go through multiple passes as well as returns multiple pages in the pdf file while the image version returns a huge image.

Is there a way to get wkhtmltopdf to return just the first single page size of the website in a pdf or better yet in an image like a png?

The things is that I am getting too much information returned and need just a single page worth of information. I know that this is a relative term, but I hope that you get the idea.

thanks,
Lonnie

**Comment by PhilterPaper** [comment] 2016-03-07 15:14
There have been a number of requests for wkHTMLtoPDF to return just selected pages(s), but I don't think there's a way to do that directly. You certainly *could* generate the full multi-page PDF, and then use some PDF utility (e.g., PDFtk) to select out the desired page(s).

There is a related utility (wkHTMLtoPNG) to output a PNG file instead. Have you looked at that? It really would make no sense to output a huge single-page PDF, as the whole idea of PDF is to map output to physical media.

**Comment by ashkulz** [comment] 2016-11-24 06:56
Duplicate of #1627

**Closed by ashkulz** 2016-11-24 06:56 UTC
