### ISSUE TITLE
[0.12.4] very high resolution on Sierra

### ISSUE THREAD

**Issue by WayneUong** [wkhtmltopdf/wkhtmltopdf#3376] opened 2017-03-08 00:34 UTC
I did a fresh install on a new Mac and test with:
`wkhtmltopdf google.com test.pdf`

The result has very high resolution:

[test.pdf](https://github.com/wkhtmltopdf/wkhtmltopdf/files/826260/test.pdf)

**Comment by khkremer** [comment] 2017-03-12 17:22
Take a look here: #3241

**Comment by Tomsgu** [comment] 2018-08-08 09:15
Closing as it's a duplicate of #3241.

**Closed by Tomsgu** 2018-08-08 09:15 UTC
Labels: NeedInfo
