### ISSUE TITLE
File Fails with non .HTML extension

### ISSUE THREAD

**Issue by roadtripguy** [wkhtmltopdf/wkhtmltopdf#2201] opened 2015-02-11 22:38 UTC
When a file has a different extension than .HTML it results in a failure.

With .tmp extension:

C:\Users\THEUSER>"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" --page-size letter --footer-center " Page [page] of [topage] " "C:\Users\THEUSER\AppData\Local\Temp\tmp70.tmp" "C:\Users\THEUSER\AppData\Local\Temp\tmpF23C.pdf"

Loading pages (1/6)
Error: Failed loading page file:///C:/Users/THEUSER/AppData/Local/Temp/tmp70.t
mp (sometimes it will work just to ignore this error with --load-error-handling
ignore)
Exit with code 1, due to unknown error.

With .HTML extension

C:\Users\THEUSER>"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" --page-size letter --footer-center " Page [page] of [topage] " "C:\Users\THEUSER\AppData\Local\Temp\tmp70.html" "C:\Users\THEUSER\AppData\Local\Temp\tmpF23C.pdf"
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

**Comment by ashkulz** [comment] 2015-03-17 13:35
Duplicate of #1866

**Closed by ashkulz** 2015-03-17 13:35 UTC
